### ISSUE TITLE
关于 GPLv3 链接库污染

### ISSUE THREAD

**Issue by kecrily** [ArtalkJS/Artalk#101]
使用 GPLv3 的模块会对程序本身造成污染[^1]，这也包括了通过 `<script>` 进行引用，相较于其他不会因通过模块使用的评论程序而言，似乎降低了一定的竞争力。单从提供评论功能这一需求而言似乎没有必要使用 Artalk 并被 GPLv3 污染的必要性。

是否可以考虑切换到不因使用链接库而被污染的 LGPLv3 或其他许可？

[^1]: Free Software Foundation. *[GNU GENERAL PUBLIC LICENSE](https://www.gnu.org/licenses/gpl-3.0.en.html)* (3rd). June 29 2007. Sect. 5C. "You must license the entire work, as a whole, under this License to anyone who comes into possession of a copy. This License will therefore apply, along with any applicable section 7 additional terms, to the whole of the work, and all its parts, regardless of how they are packaged. This License gives no permission to license the work in any other way, but it does not invalidate such permission if you have separately received it".

**Comment by qwqcode** [comment]
感谢你的提议，这对 Artalk 很有帮助！

LGPL v3 是相较于 GPL v3 更为宽松的开源协议[^1]，它允许仅对程序进行调用 (`<script>` 引入) 而不是包含或修改其源代码时，无需开源。

我打算将 Artalk 的 LICENSE 从 GPL v3 换成 LGPL v3。

[^1]: A larger work using the licensed work through interfaces provided by the licensed work may be distributed under different terms and without source code for the larger work.
