### ISSUE TITLE
Artalk Error Failed to load comments TypeError: Failed to fetch  Retry

### ISSUE THREAD

**Issue by zhao2022-Ux** [ArtalkJS/Artalk#1016]
Artalk Error
Failed to load comments
TypeError: Failed to fetch

Retry

**Comment by qwqcode** [comment]
检查一下可信域名是否配置正确

https://artalk.js.org/zh/guide/backend/config.html#%E5%8F%AF%E4%BF%A1%E5%9F%9F%E5%90%8D-trusted-domains

duplicate of #977

**Comment by zhao2022-Ux** [comment]
> 检查一下可信域名是否配置正确
> 
> https://artalk.js.org/zh/guide/backend/config.html#%E5%8F%AF%E4%BF%A1%E5%9F%9F%E5%90%8D-trusted-domains
> 
> Duplicate of #977

谢谢
