### ISSUE TITLE
赞同功能异常

### ISSUE THREAD

**Issue by Chadwuo** [ArtalkJS/Artalk#1021]
/api/v2/votes/comment/1820/up，请求404了

Docker 部署，使用的版本是v2.9.1

我看[官网](https://artalk.js.org/zh/guide/intro.html)上也同样问题

**Comment by qwqcode** [comment]
Nightly 新版修改了这个 API（但 Nightly 版本还未正式发布），如果你用的是 Nightly 的前端代码，后端也需要升级到 Nightly。

<img width="932" alt="image" src="https://github.com/user-attachments/assets/c26d2204-f6ea-462e-bfae-6f940a3c1af7">

官网是因为暂时还没有更新后端到 Nightly 版本，但前端代码是和仓库最新代码同步的。

**Comment by Chadwuo** [comment]
谢谢
