### ISSUE TITLE
表情无法加载

### ISSUE THREAD

**Issue by penndu** [ArtalkJS/Artalk#117]
加入了参数emoticons: "https://cdn.dusays.com/info.json",

报错如下：

![image](https://user-images.githubusercontent.com/46226528/164712980-fc1ef18a-9a3b-427f-9bd3-b83f2f325406.png)

**Comment by xiamuguizhi** [comment]
上次有人也碰到这个了，不知道什么情况！！我用着就是正常！！
`https://i.xiamuyourenzhang.cn/biaoqingbao.json`

**Comment by qwqcode** [comment]
你的 JSON 格式有误，
![image](https://user-images.githubusercontent.com/22412567/164713569-f7b15c75-dbc2-453d-af22-b1f0b4233725.png)

**Comment by qwqcode** [comment]
![image](https://user-images.githubusercontent.com/22412567/164713660-66e6445d-225c-466b-8c86-6e3759fdf284.png)

可以去网上找一些 JSON 验证工具，检验一下你的 JSON 格式，这样就是 OK 的

```
[
  {
    "name": "表情",
    "type": "image",
    "items": [
      { "key": "再见", "val": "https://npm.elemecdn.com/sticker-heo@0.17.2/Sticker-100/%E5%86%8D%E8%A7%81.png"}
    ]
  }
]
```

**Comment by penndu** [comment]
> ![image](https://user-images.githubusercontent.com/22412567/164713660-66e6445d-225c-466b-8c86-6e3759fdf284.png)
> 
> 可以去网上找一些 JSON 验证工具，检验一下你的 JSON 格式，这样就是 OK 的：
> 
> ```
> [
>   {
>     "name": "表情",
>     "type": "image",
>     "items": [
>       { "key": "再见", "val": "https://npm.elemecdn.com/sticker-heo@0.17.2/Sticker-100/%E5%86%8D%E8%A7%81.png"}
>     ]
>   }
> ]
> ```

非常感谢！

**Comment by qwqcode** [comment]
> > ![image](https://user-images.githubusercontent.com/22412567/164713660-66e6445d-225c-466b-8c86-6e3759fdf284.png)
> > 可以去网上找一些 JSON 验证工具，检验一下你的 JSON 格式，这样就是 OK 的：
> > ```
> > [
> >   {
> >     "name": "表情",
> >     "type": "image",
> >     "items": [
> >       { "key": "再见", "val": "https://npm.elemecdn.com/sticker-heo@0.17.2/Sticker-100/%E5%86%8D%E8%A7%81.png"}
> >     ]
> >   }
> > ]
> > ```
> 
> 非常感谢！

哈哈，没问题的话这个 issue 就关闭了
