### ISSUE TITLE
评论框和控制中心表情不同

### ISSUE THREAD

**Issue by penndu** [ArtalkJS/Artalk#123]
这是评论框的。

![image](https://user-images.githubusercontent.com/46226528/164991475-dbd86ff3-f37b-4255-8e89-0bd3be6015a7.png)

这是控制中心。

![image](https://user-images.githubusercontent.com/46226528/164991456-5e4ef958-43a5-4766-bdc0-44abcfab863d.png)

**Comment by qwqcode** [comment]
这确实是个bug🤣 因为侧边栏独立拆分了，没有考虑到

**Comment by penndu** [comment]
> 这确实是个bug🤣 因为侧边栏独立拆分了，没有考虑到

是走js吧，目前没办法独立设置吧？

**Comment by qwqcode** [comment]
我觉得可以后端增加一个配置项，在后端配置表情包，这样前后端都能生效

**Comment by penndu** [comment]
> 我觉得可以后端增加一个配置项，在后端配置表情包，这样前后端都能生效

我感觉特别行！

**Comment by qwqcode** [comment]
而且也方便管理，不用去改动前端了

**Comment by penndu** [comment]
> 而且也方便管理，不用去改动前端了

没错！

**Comment by penndu** [comment]
docker后端什么时候更新呢？

**Comment by qwqcode** [comment]
https://artalk.js.org/guide/backend/fe-control.html
