### ISSUE TITLE
如何去除 waline 评论导入后的无用回复 @AT 标签

### ISSUE THREAD

**Issue by penndu** [ArtalkJS/Artalk#124]
![image](https://user-images.githubusercontent.com/46226528/164991519-f68c156e-5997-48ce-a64c-302c8748f8a2.png)

**Comment by qwqcode** [comment]
🤔 我觉得这个可以删掉，可以用正则表达式删掉

**Comment by penndu** [comment]
> thinking 我觉得这个可以删掉，可以用正则表达式删掉

那我都删掉吧！

**Comment by qwqcode** [comment]
我写了段 JS 正则表达式删除这个回复的，一会儿我加到 Artransfer 在线版里面，但是需要把 `.artrans` 重新数据库导一遍。

```js
`<a href="#123456" clsss="test-class">@TEST USER</a>`.replace(/<a\s+(?:[^>]*?\s+)?href="#(\d+)?"[^>]*>@(.*?)<\/a>/ig, '')
```

**Comment by penndu** [comment]
> 我写了段 JS 正则表达式删除这个回复的，一会儿我加到 Artransfer 在线版里面，但是需要把 `.artrans` 重新数据库导一遍。
> 
> ```js
> `<a href="#123456" clsss="test-class">@TEST USER</a>`.replace(/<a\s+(?:[^>]*?\s+)?href="#(\d+)?"[^>]*>@(.*?)<\/a>/ig, '')
> ```

非常感谢！

**Comment by qwqcode** [comment]
https://artransfer.netlify.app/

这里上传从 waline 导出的 `.artrans` 文件就可以删掉 `@`

![image](https://user-images.githubusercontent.com/22412567/165012358-c97f2aba-3147-45ed-9a11-c3b67b39f37e.png)

**Comment by penndu** [comment]
> https://artransfer.netlify.app/
> 
> 这里上传从 waline 导出的 `.artrans` 文件就可以删掉 `@`
> 
> ![image](https://user-images.githubusercontent.com/22412567/165012358-c97f2aba-3147-45ed-9a11-c3b67b39f37e.png)

收到！

**Comment by qwqcode** [comment]
这个功能我之后直接加在 waline 导出 Artrans 的 [Artransfer-CLI](https://github.com/ArtalkJS/Artransfer-CLI) 里面

**Comment by penndu** [comment]
> 这个功能我之后直接加在 waline 导出 Artrans 的 [Artransfer-CLI](https://github.com/ArtalkJS/Artransfer-CLI) 里面

相信会有更多的人转来！

**Comment by qwqcode** [comment]
看起来没什么问题，issue 就关闭咯~

**Comment by penndu** [comment]
> 看起来没什么问题，issue 就关闭咯~

好嘞！
