### ISSUE TITLE
[Feature request] 在博客首页获取评论数与阅读数

### ISSUE THREAD

**Issue by leirock** [ArtalkJS/Artalk#153]
目前只有在文章页，可以设置 `<span id="ArtalkPV"></span>` 获取文章阅读数；而评论数只显示在评论区域。

但是无法：

- 在文章页其他地方获取评论数，例如在标题下显示文章发布时间的位置显示评论数
- 在首页（index）的文章列表中也可以获取到评论数和文章阅读数。

是否可以通过以下方式实现

```html
<span class="artalk-comment-count" data-path="< pageKey >" /> 条评论
<span class="ArtalkPV" data-path="< pageKey >" /> 次阅读
```

希望的效果：https://pinlyu.com

**Comment by qwqcode** [comment]
https://github.com/ArtalkJS/Artalk/commit/617279573bca2baf1686a0a7517eac6987c3c56e

**Comment by leirock** [comment]
@qwqcode 

因为文档没有更新，我看了一下更新的代码，更新前后端以后添加了

```njk
<span id="ArtalkCount" data-page-key="{{ url_for(post.path) }}" ></span>
<span id="ArtalkPV" data-page-key="{{ url_for(post.path) }}" ></span>
```

但是依然没有效果，不知道是什么原因。

是参考 Waline 的 Hexo NexT 的插件写的插件实现引入 Artalk，插件代码见 [leirock/hexo-next-artalk](https://github.com/leirock/hexo-next-artalk)，博客源代码见 [leirock/blog](https://github.com/leirock/blog/tree/artalk)。

**Comment by qwqcode** [comment]
其他页面需要 new Artalk 传入配置参数才能有效

**Comment by leirock** [comment]
> 其他页面需要 new Artalk 传入配置参数才能有效
> 
> 并且需要确保在 new Artalk 之前已存在 #ArtalkPV 或 #ArtalkCount 元素

好像是按照你说的这样的，但是没有显示。这里是我的博客演示链接，你有空可以看看哪里有问题：

首页（没有加载评论数、阅读数）：https://leirock.github.io
文章页（可以加载阅读数，评论数不加载）：https://leirock.github.io/post/60/

**Comment by qwqcode** [comment]
<img width="516" alt="image" src="https://user-images.githubusercontent.com/22412567/169637466-2640fb0c-3cb4-4dc5-9ab5-ef5b969215c9.png">

首页的位置 new Artalk 的时候携带了一个 el 参数，然而并没有这个元素

你需要修改：**在首页的时候，不带 el 参数；仅在评论页面的时候才加上 el 参数。**

另一个问题是后端的 BUG：使用默认站点后端 API 忘记了做处理，我刚刚已经修好了 (https://github.com/ArtalkJS/ArtalkGo/commit/8924afdadd6af6e45ebe0ecce50d7100948bc949)

**Comment by qwqcode** [comment]
可以试试新发布的 ArtalkLite 精简版本 (默认关闭表情包、投票、UA 徽标功能，去掉了 marked 依赖)，JS 文件大小仅 20.22KB

https://cdn.jsdelivr.net/npm/artalk@2.3.0/dist/ArtalkLite.js
https://cdn.jsdelivr.net/npm/artalk@2.3.0/dist/ArtalkLite.css

**Comment by leirock** [comment]
我调整了一下引入的方式，现在能显示了，不过好像现在这种引入的方式在启用 PJAX 情况下，从首页进入文章页后评论框无法显示，搞不定，你能不能帮忙看看应该怎么改？

插件：[leirock/hexo-next-artalk](https://github.com/leirock/hexo-next-artalk/blob/main/artalk.njk)
博客：https://leirock.github.io/

**Comment by qwqcode** [comment]
OK 我看看

**Comment by qwqcode** [comment]
搞定了，你可以 merge
