### ISSUE TITLE
转换数据时出现了报错

### ISSUE THREAD

**Issue by penndu** [ArtalkJS/Artalk#181]
[Comment.0.zip](https://github.com/ArtalkJS/Artalk/files/8868755/Comment.0.zip)

![image](https://user-images.githubusercontent.com/46226528/172809669-588d5707-6941-4c72-a6e1-f366c86f90ef.png)

**Comment by qwqcode** [comment]
已修复，https://github.com/ArtalkJS/Artransfer/commit/9aa883c628b0dae3cd0e8e0c0529d05d43990660

感谢反馈！♥

https://artransfer.netlify.app/
