### ISSUE TITLE
我又来了，这次是控制中心打不开

### ISSUE THREAD

**Issue by penndu** [ArtalkJS/Artalk#182]
如图，评论可以正常显示，提交也没问题，但控制中心会报错！

![image](https://user-images.githubusercontent.com/46226528/172847460-d28d7474-12d4-4d15-910d-26891de27d34.png)

**Comment by penndu** [comment]
管理员就不行，神马情况~

**Comment by qwqcode** [comment]
好奇怪 🤔🤔

**Comment by penndu** [comment]
> 好奇怪 🤔🤔

![image](https://user-images.githubusercontent.com/46226528/172851605-b1b4923c-47e4-401f-bc78-866cf0129525.png)
脸有点疼~
