### ISSUE TITLE
界面会考虑适配移动端码？

### ISSUE THREAD

**Issue by rangujie** [ArtalkJS/Artalk#204]

**Comment by qwqcode** [comment]
移动端界面目前已适配，似乎并没有什么问题，你能具体说明有什么问题吗？

**Comment by rangujie** [comment]
> 移动端界面目前已适配，似乎并没有什么问题，你能具体说明有什么问题吗？
不好意思, 我的锅，之前嵌入有点问题 ，已经解决了
