### ISSUE TITLE
建议更换或者提供选择Gravatar服务器

### ISSUE THREAD

**Issue by SatoSouta** [ArtalkJS/Artalk#21]
https://gravatar.loli.net/ 在部分地区无法访问，可以更换为v2ex：https://cdn.v2ex.com/gravatar/ 或者提供给用户自行选择服务器使用

**Comment by qwqcode** [comment]
感谢反馈，已替换Gravatar服务器地址并更新 README.md 🥳

Artalk 自定义 Gravatar 源地址方法可参考：[传送门](https://github.com/ArtalkJS/Artalk#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%A4%B4%E5%83%8F-gravatar-%E9%95%9C%E5%83%8F%E6%BA%90)
