### ISSUE TITLE
侧边栏控制中心/通知中心表情问题

### ISSUE THREAD

**Issue by BowenYoung** [ArtalkJS/Artalk#224]
![表情](https://p.qlogo.cn/hy_personal/3e28f14aa051684253d96f4f8d327ad4013b4af6342b5fee4ea11cca6430ec92/0.png)
如图，侧边栏控制中心点击表情，显示的是默认表情而不是配置的表情。

**Comment by qwqcode** [comment]
可在后端配置：

```
frontend:
  emoticons: "表情包 JSON 文件 URL"
```

参考：https://artalk.js.org/guide/backend/fe-control.html

**Comment by BowenYoung** [comment]
哦哦，也就是说仅在前端配置，侧边栏表情包并不会修改🤣感谢了
