### ISSUE TITLE
部署后，提示：{"success":false,"msg":"无效请求，Origin 无法获取","data":{}}

### ISSUE THREAD

**Issue by iwyang** [ArtalkJS/Artalk#244]
使用Docker Compose部署，打开后端提示：`{"success":false,"msg":"无效请求，Origin 无法获取","data":{}}`

**Comment by qwqcode** [comment]
https://artalk.js.org/guide/backend/config.html#%E5%8F%AF%E4%BF%A1%E5%9F%9F%E5%90%8D-trusted-domains

**Comment by qwqcode** [comment]
#687 #707
