### ISSUE TITLE
导入数据不显示

### ISSUE THREAD

**Issue by iwyang** [ArtalkJS/Artalk#250]
为什么从twikoo导入的数据在控制中心能看到，在相应页面却没有，无法显示呢？

**Comment by iwyang** [comment]
导入的时候，需要提供 “目标站点名”, “目标站点 URL”,我这里目标站点为 “blog”， URL 为 “[https://www.iots.vip"，](https://www.iots.vip%22%2C/) 导入后会发现一个问题，由于我们前面前端使用的 page_key 为相对路径, 但是 Artalk 的导入功能在写入数据的时候又默认会拼接 “目标站点 URL” 进 page_key 字段，这样就会导致旧的评论无法在文章页面中展示，我们需要手动将数据库中的 comments 表中的 page_key 改成相对路径。这样导入的评论就能正常展示了（感觉应该算是一个 BUG，已经跟作者提了）。
　　连接数据库执行如下 SQL（如果你用的是 sqlite，那么直接用 navicat 打开它就行啦）：
```
update `comments` set page_key=REPLACE(page_key, 'https://www.iots.vip/', '/');
```
参考：https://www.iots.vip/post/hexo-artalk-comment.html

**Comment by JadeVane** [comment]
By the way, in the example given by the document, 'pageKey' uses an absolute path, so to synchronize to change to a relative path, the change is very simple, just leave it blank:

```javascript
<script>
  Artalk.init({
    el:        '#Comments',
    pageKey:   '',          // <-- 这里留空
    pageTitle: '{{ . Title }}',
    server:    '{{ $. Site.Params.artalk.server }}',
    site:      '{{ $.Site.Params.artalk.site }}',
  })
</script>
```
