### ISSUE TITLE
请求控制中心可以修改更多的配置

### ISSUE THREAD

**Issue by cqbzljt** [ArtalkJS/Artalk#252]
比如邮箱通知，垃圾评论检测甚至是管理员密码（只能自己改自己）之类的，YAML 里面的内容都可以安排上

（主要还是因为我的数据不在我这里，让别人改比较麻烦

**Comment by qwqcode** [comment]
已更新增加前端配置功能

https://github.com/ArtalkJS/Artalk/releases
