### ISSUE TITLE
增加可选配置将 “a.com/1/” 和 “a.com/1” 识别为相同页面

### ISSUE THREAD

**Issue by qwqcode** [ArtalkJS/Artalk#271]
### Discussed in https://github.com/ArtalkJS/Artalk/discussions/213

<div type='discussions-op-text'>

<sup>Originally posted by **penndu** July  6, 2022</sup>
判断URL时，a.com/1/和a.com/1被识别为不同的页面，希望可识别为相同页面。</div>

**Comment by inkss** [comment]
`a.com/1/` 不是包含隐含的 `a.com/1/index.html` 吗？

**Comment by qwqcode** [comment]
1

**Comment by qwqcode** [comment]
考虑到一致性和复杂度，决定放弃实现该。按照 Web URL 规定，`a.com/1/` 和 `a.com/1` 本来不是相同的页面。
