### ISSUE TITLE
希望增加个人中心

### ISSUE THREAD

**Issue by inkss** [ArtalkJS/Artalk#279]
- 需求：允许用户通过邮箱验证码验证用户身份，验证后的用户评论逻辑类似管理员登录。
- 理由：
  1. 避免身份盗用，验证用户需登录后方可操作。
  1. 实名用户体系可满足境内相关政策要求。
  1. 可以增加用户自主申请个性化徽标等功能。

**Comment by LeenHawk** [comment]
身份验证对合规性的确很重要。。。

**Comment by qwqcode** [comment]
用户通过邮箱验证身份功能目前已实现：#840

之后将继续逐步完善，增加更多用户中心的功能
