### ISSUE TITLE
头像链接兼容

### ISSUE THREAD

**Issue by rangujie** [ArtalkJS/Artalk#287]
用户可以加一个头像地址字段吗？原有用户有自己的头像，但现在都是统一的gravatar

**Comment by monsterxcn** [comment]
你说的 `头像地址字段` 是不是这个东西？

https://github.com/ArtalkJS/Artalk/blob/caf690fe9ef4fd3af9e5ec2f0c928dffe2a61734/packages/artalk/types/artalk-config.d.ts#L34-L40

commit 1de9565e55e8bff499cc83396105fa07610c8ffb 修改了默认头像源为 [Cravatar](https://cravatar.cn/)，你可以自己在前端配置中定义你要的 `mirror`，比如改回之前的：

```diff
new Artalk({
  gravatar: {
-   mirror: 'https://cravatar.cn/avatar/',
+   mirror: 'https://sdn.geekzu.org/avatar/',
  }
}
```

**Comment by monsterxcn** [comment]
我认为你说的那个不是 artalk 应该做的工作，而是头像镜像源应该做的，比如这个 Cravatar 就是优先返回 QQ 头像其次才是 Gravatar。

**Comment by rangujie** [comment]
原有系统的用户有自己的头像，现在评论都是Gravatar头像，对应不了，我在试试还有其他办法不
