### ISSUE TITLE
vscode保存浏览器自动更新问题

### ISSUE THREAD

**Issue by Yangjb18375324102** [ArtalkJS/Artalk#323]
![image](https://user-images.githubusercontent.com/35518525/204954852-c45899a4-b3f3-4118-9ba0-0d9511d83ebf.png)

**Comment by Yangjb18375324102** [comment]
手动刷新一次浏览器不会出问题

**Comment by qwqcode** [comment]
我猜测这可能和 HMR (Hot Module Replacement) 功能有关，在刷新的时候反复执行 `new Artalk` 导致的问题

可以关闭 HMR 改为自动 reload 临时解决这个问题，

或者你可以尝试修改一下你的 webpack 之类的配置，我暂时不知道怎么修改 Artalk 以更好地兼容 HMR 😢
