### ISSUE TITLE
markdown处理问题

### ISSUE THREAD

**Issue by thun888** [ArtalkJS/Artalk#33]
在折腾表情时发现它没法显示，品了一会发现是表情引用路径有特殊符号"-“导致的👀
![image](https://user-images.githubusercontent.com/63234268/125575955-54760ab1-ac9b-4574-a26d-5061db878605.png)

**Comment by monsterxcn** [comment]
现在能具体描述你是如何「折腾」的吗？比如 `src/assets/emoticons.json` 是如何编写的呢？我尝试了你引用的仓库中部分表情，本地测试是没有问题的。

![image](https://user-images.githubusercontent.com/22407052/140291432-129219a2-7819-465b-b73b-ff7e20d34e76.png)

**Comment by monsterxcn** [comment]
不过话说回来，时隔近 4 个月，我觉得你应该已经解决这个问题了吧 ![huaji](https://cdn.jsdelivr.net/gh/thun888/Coolapk-Emoji@master/coolapk_emotion_66_doujiyanhuaji.png)

**Comment by thun888** [comment]
> 不过话说回来，时隔近 4 个月，我觉得你应该已经解决这个问题了吧 ![huaji](https://camo.githubusercontent.com/21253b35addf273592e96ff0b0c4938216e29f6e958db16a9aec609658fc0360/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f7468756e3838382f436f6f6c61706b2d456d6f6a69406d61737465722f636f6f6c61706b5f656d6f74696f6e5f36365f646f756a6979616e6875616a692e706e67)

抱歉这么久才看到，我尝试复现该问题，但在1.0.6版本中没有出现任何问题
![image](https://user-images.githubusercontent.com/63234268/147854166-cdad6901-e1a6-42a0-9691-982b19e23a1c.png)
（该releases）

![Snipaste_2022-01-01_23-36-57](https://user-images.githubusercontent.com/63234268/147854231-3c29ee08-7776-4548-9add-23e5d56b40a7.png)
不过我找出当时的备份后发现那时用的是1.07版本，成功复现~
![image](https://user-images.githubusercontent.com/63234268/147854263-39cbcb3a-b962-420d-9843-93bd1e073b86.png)
![image](https://user-images.githubusercontent.com/63234268/147854281-b3d91cdd-c2d2-4af6-a4e3-ad323217ebf8.png)
Gif:
![14dsf353gf](https://user-images.githubusercontent.com/63234268/147854291-1b2032e1-0ddf-40e8-b57b-2470002e50b5.gif)

可能是作者无意间敲了个bug吧
![68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f7468756e3838382f436f6f6c61706b2d456d6f6a69406d61737465722f636f6f6c61706b5f656d6f74696f6e5f36365f646f756a6979616e6875616a692e706e67](https://user-images.githubusercontent.com/63234268/147854333-c669a90d-be2d-47dd-921a-eb5291e4c6e9.png)

**Comment by qwqcode** [comment]
好神奇哦 🤣 （疑惑
