### ISSUE TITLE
能否增加点击量统计功能

### ISSUE THREAD

**Issue by LanceMoe** [ArtalkJS/Artalk#339]
Artalk 用来做博客评论区蛮好用的，可否做个简单的页面点击量统计？

每次前端拉取评论，计数器加一即可。感觉挺有用的，实现起来似乎也不难。

**Comment by qwqcode** [comment]
这个功能？
https://artalk.js.org/guide/frontend/pv.html

**Comment by LanceMoe** [comment]
> 这个功能？
> https://artalk.js.org/guide/frontend/pv.html

感谢，应该没啥问题了～
