### ISSUE TITLE
Docker images add support for Linux/ARM

### ISSUE THREAD

**Issue by DejavuMoe** [ArtalkJS/Artalk#357]
I saw that ArtalkGo has pre-compiled binaries for Linux ARM/ARM64, can you add a Docker image support for ARM/ARM64 architecture to the project, thanks.

**Comment by Nesxc** [comment]
> 好主意。目前我们正在进行单存储库重构。之后，我们将在将来的版本中添加此类支持。

i need armxx64 docker version too,pls support arm

**Comment by qwqcode** [comment]
We're currently developing a new version of Artalk with improved performance, but it hasn't been released yet.

The development process has been slow as I've been occupied with school exams recently 😢, and we want to make sure the new version is thoroughly tested for stability before releasing it. Rest assured, future releases will still support the arm64 platform. 😎

I apologize for the delay. The old v2.3.0 backend has now been recompiled and made available on Docker Hub at:

https://hub.docker.com/r/artalk/artalk-go/tags

This Artalk Docker image supports both arm64 and amd64 platforms. 😁

If you have any questions, don't hesitate to reach out. We appreciate your support of Artalk! 😉
