### ISSUE TITLE
[Bug] `destroy` function for artalk to avoid memory leak in SPA

### ISSUE THREAD

**Issue by Mister-Hope** [ArtalkJS/Artalk#373]
Artalk needs an destroy method to remove all event listerner and callback functions to prevent memory increasing.

Also, the destroy method should remove extra dom besides cleaning the original object.

E.g.: `div.atk-layer-wrap` it inserts during initialization.

<img width="514" alt="image" src="https://user-images.githubusercontent.com/33315834/216566649-9937a125-0d2c-49e0-a2bf-4a71540ecf26.png">

**Comment by qwqcode** [comment]
Thanks for the issue, it's really helpful!

**Comment by inkss** [comment]
为什么不尝试去掉 id 选择器部分？移除 `#ctx-${ctx.cid}` 和 `id="ctx-${ctx.cid}"`

https://github.com/ArtalkJS/Artalk/blob/3b99a588f77c232c225024147e41713c6dae254e/ui/packages/artalk/src/layer/layer.ts#L151-L156

**Comment by qwqcode** [comment]
> 为什么不尝试去掉 id 选择器部分？移除 `#ctx-${ctx.cid}` 和 `id="ctx-${ctx.cid}"`
> 
> https://github.com/ArtalkJS/Artalk/blob/3b99a588f77c232c225024147e41713c6dae254e/ui/packages/artalk/src/layer/layer.ts#L151-L156

因为当初设计是想多个 Artalk 实例互不干扰，一页有多个互相隔离的独立 Artalk 实例，例如两个评论框，他们不会因为公用相同的 Layer Wrap 元素而造成干扰。

但这个功能似乎并没有什么用，既增加了代码复杂度，难以维护，又为前端部署带来问题，以后想直接删掉这个特性，只允许一个页面创建一个 Artalk 实例，类似单例模式的实现。

**Comment by qwqcode** [comment]
v2.5.0 (2023-03-10) 新版已发布

https://github.com/ArtalkJS/Artalk/releases
