### ISSUE TITLE
[ 🐛 BUG 反馈 ] 关于评论穿梭框二次设置之后不生效的问题

### ISSUE THREAD

**Issue by eryajf** [ArtalkJS/Artalk#431]
## 前提

程序集成了评论框穿梭的功能，默认情况下，这个配置如为：`editorTravel: true`。

## 问题

当我无意之中，点击取消了这个配置勾选，而后又想启用，此时发现，前端传递给后端的值变成了 `editorTravel: 1`，也就导致了这个功能即便是选中了，也无法正常使用。

如下：

<img width="694" alt="image" src="https://user-images.githubusercontent.com/33259379/221345184-c1e1bffc-9d84-4e7f-93c7-a52e77a4345b.png">

## 解决

从后端或者前端解决这个字段的类型问题。

**Comment by qwqcode** [comment]
v2.5.0 (2023-03-10) 新版已发布

https://github.com/ArtalkJS/Artalk/releases
