### ISSUE TITLE
文章页关闭评论时报错

### ISSUE THREAD

**Issue by inkss** [ArtalkJS/Artalk#44]
msg: "Param `id` is required"

```log
DEBUG POST /api/get ip=172.17.0.1 latency=2.7617ms referer=http://localhost:4000/ status=200 user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

ERROR 响应: POST /api/admin/page-edit ==> "Param `id` is required" host=127.0.0.1:8080 id= ip=172.17.0.1 referer=http://localhost:4000/ status=200 user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

DEBUG POST /api/admin/page-edit ip=172.17.0.1 latency=535.1µs referer=http://localhost:4000/ status=200 user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
```

**Comment by qwqcode** [comment]
可提供下前端和后端版本吗？之前确实存在这个问题，但已经修复了

**Comment by inkss** [comment]
后端 docker 部署，前端 `v2.0.4`

![Images list_21-10-30_20-59-13](https://user-images.githubusercontent.com/31947043/139533776-1db0d3e6-5531-48e3-82b0-07ce23fbf1ce.png)

**Comment by qwqcode** [comment]
官网最新部署目前没有存在这个问题，能够提供更多细节吗？感谢

**Comment by qwqcode** [comment]
好的，让我想想（思考🤔

**Comment by inkss** [comment]
当前使用的配置文件（没怎么修改）：

<details><summary>conf.yml</summary>

```yml
# HTTP Server
host: "0.0.0.0"

# 端口
port: 23366

# 加密密钥
app_key: "iiiiii"

# 调试模式
debug: true

# 时区
timezone: "Asia/Shanghai"

# 数据文件
db:
  type: "sqlite" # 支持 mysql, sqlite, pgsql, sqlserver
  dsn: "./data/artalk-go.db"

# 日志
log:
  enabled: true # 总开关
  filename: "./data/artalk-go.log" # 日志文件路径

# 允许跨域访问的域名
allow_origins:
  - "*" # '*' 跨域无限制
# - 'http://localhost:8080'

# SSL
ssl:
  enabled: false
  cert_path: ""
  key_path: ""

# 默认站点名
site_default: "默认站点"

# 管理员账户
admin_users:
  - name: "admin"
    email: "admin@example.com"
    password: "1q2w3e4r"
    badge_name: "管理员"
    badge_color: "#FF6C00"

# 登录超时 (单位：秒)
login_timeout: 259200

# 评论审核
moderator:
  pending_default: false # 发表新评论默认为 “待审状态”
  akismet_key: "" # 启用 akismet.com 反垃圾

# 验证码
captcha:
  enabled: true # 总开关
  always: false # 总是需要验证码
  # ↓ 在 {comment_timeout} 秒内，操作次数超过 {comment_limit} 次激活验证码
  action_timeout: 60
  action_limit: 3

# 邮件通知
email:
  enabled: false # 总开关
  send_type: "smtp" # 发送方式 [smtp, ali_dm, sendmail]
  send_name: '{{reply_nick}}' # 发信人昵称
  send_addr: "example@qq.com" # 发信人地址
  mail_subject: "[{{site_name}}] 您收到了来自 @{{reply_nick}} 的回复"
  mail_subject_to_admin: '[{{site_name}}] 您的文章 "{{page_title}}" 有新回复'
  mail_tpl: "default" # 邮件模板文件
  smtp:
    host: "smtp.qq.com"
    port: 587
    username: "example@qq.com"
    password: ""
  ali_dm: # https://help.aliyun.com/document_detail/29444.html
    access_key_id: "" # 阿里云颁发给用户的访问服务所用的密钥 ID
    access_key_secret: "" # 用于加密的密钥
    account_name: "example@example.com" # 管理控制台中配置的发信地址
```

</details>

**Comment by qwqcode** [comment]
原因查明了，原来是**编辑页面**的时候，如果页面**未被初始化过**，就会报错。
现在修改了后端代码，**编辑页面**操作，若检测到页面**未创建**，先创建一下。
**页面创建**操作，之前仅仅只会在**提交评论**的时候执行，所以就会出现错误。

https://github.com/ArtalkJS/ArtalkGo/commit/3d9ece48fa6df94860d7279189d1301b9a555683

版本号依旧是 v2.0.2，但已替换更新，docker 目前可以重新 pull 下镜像并创建容器。

https://artalk.js.org/guide/backend/docker.html#%E5%8D%87%E7%BA%A7

**Comment by qwqcode** [comment]
感谢反馈！问题还存在吗？期待回复

**Comment by inkss** [comment]
thx, 已经解决了，🤣。

**Comment by qwqcode** [comment]
https://github.com/volantis-x/hexo-theme-volantis/commit/e1923e8bdad08741a985011e269352c7592d29fe#diff-f1fc18ed01f67d93775611148783d175908ac3ce496b6f9360755a8e7bb8de67R20

ohh 对了！`pageUrl` 属性现在已经被移除了，`pageKey` 直接为完成的 URL 用于区分页面

好欸！感谢使用 Artalk！

**Comment by inkss** [comment]
好的，期待文档更完善哈 😁

**Comment by qwqcode** [comment]
> 好的，期待文档更完善哈 😁
> 
> > pageKey 直接为完成的 URL 用于区分页面
> 
> 相对链接比绝对连接好些吧，变更域名的时候比记录完整的地址好一些呀

是这样的，Artalk 加入了”多站点“功能，填写完整链接能够更准确的定位到页面，包括发送邮件之类的。变更域名后端通过批量替换处理。

配置说明已加上：https://artalk.js.org/guide/frontend/config.html

Artalk 仍然有很多不完善的地方，会慢慢完善的，哈哈

**Comment by xiamuguizhi** [comment]
@qwqcode 用 `window.location.href; //返回整个url字符串(在浏览器中就是完整的地址栏)，例如：www.xxx.com/index.php?class_id=3&id=2 `  js获取完整的也可以把？一些静态博客 应该用的到 我也打算试试这个

**Comment by inkss** [comment]
> 填写完整链接能够更准确的定位到页面

可是站点本身有地址呀，如果需要访问，利用站点设置里的 url 和页面的 url 拼接呗，可以做个判断如果地址包含了站点 url 的内容就不处理，反之拼接下。（是不是现在就是这样处理的？

**Comment by qwqcode** [comment]
> > 填写完整链接能够更准确的定位到页面
> 
> 可是站点本身有地址呀，如果需要访问，利用站点设置里的 url 和页面的 url 拼接呗，可以做个判断如果地址包含了站点 url 的内容就不处理，反之拼接下。（是不是现在就是这样处理的？

多站点功能是后来加入的，怎么实现更易用目前还在探索中，感谢您提出的建议，并期待更为深入的探讨。

如果站点**只有一个**域名的情况下，PageKey 不用填写完整 URL，后端可以根据这**一个域名**拼接字符串。也就是说，PageKey 是**可以填写 “相对路径”** 的。

（因为用到 PageKey 的地方有点多，**之前**时间不太充裕，直接填写**完整 URL** 作为 PageKey 不用拼接就可以摸鱼了，省去了不少代码，哈哈。我觉得这个可以有，拼接字符串这种方式将在**下一版中加入**，已经安排上了）

【站点 (Site) “本身就有的地址”】目前作用是：
    1. “Referer 合法性检测”：后端判断来自前端的请求 Header Referer 是否合法（阻止其他域名下进行非法提交）
    2. 后端设计支持：一个**站点**（项目）能有**多个域名**（多个  Site URL）（判断多个 Referer）
    3. 如果不设置 Site URL，则任何域名都可以请求，没有 “Referer 合法性检测”
    3. 依赖 PageKey 来生成邮件中的“回复”链接。（如果仅仅依靠 Site URL 来拼接字符串，如果有多个 Site URL，根据第一个 Site URL 拼接的链接是不准确的，不知道具体是哪一个网站）
    4. 依赖 PageKey 后端读取页面数据，爬取页面 `<title>` 后端显示页面标题
    5. 主要是为了**多站点**支持**多域名**，如果 PageKey 填写完整 URL，能够更加准确。

后端可以对原来**包含域名**的 PageKey 进行批量替换，因此 PageKey 完整URL换域名是不太繁琐的。

## 总结：

后续更新后端程序：

**PageKey 不再强制要求填写完整 URL，可“相对路径“也可”完整URL“**

1. 若一个站点有**多个域名**，PageKey 如果填 “相对路径”，会根据 **第一个域名** 拼接字符串。如果填 “完整链接”，会根据这个链接来，这样就能够更准确。（一个站点有多个域名，PageKey 推荐填写完整URL，但不强制要求）

2. 若一个站点只有**单个域名**，PageKey 填写 “相对路径”，就能够根据这个域名 **拼接生成** URL，这样拼接的很灵活，后端也能直接换域名。

3. 站点不允许 **没有域名**。

4. 添加单独的配置项：控制开启关闭 “Referer 合法性检测”。

**Comment by qwqcode** [comment]
> @qwqcode 用 `window.location.href; //返回整个url字符串(在浏览器中就是完整的地址栏)，例如：www.xxx.com/index.php?class_id=3&id=2 ` js获取完整的也可以把？一些静态博客 应该用的到 我也打算试试这个

`window.location.href` 是可以获取到 URL 的 query 部分的。

**Comment by inkss** [comment]
做一个Saas平台吗?

**Comment by monsterxcn** [comment]
> 做一个Saas平台吗?

哈哈我觉得目前是没有这个能力的，只是说很多人可能已经在使用各种不花钱的地方托管静态博客，大概率是不愿意自己另外购置服务器部署 Artalk 后端的。这个时候我们公开后端，供大家尝鲜体验。

使用我们计划未来公开的后端，有人可能觉得数据被掌握在别人手里不安全不信任。这个时候我觉得理想情况是：一个小圈子里有一个人拥有服务器部署了 Artalk 后端，该圈子里的小伙伴们可以和他联系，直接使用私有部署的后端，大家的数据在朋友手上，顾虑可能会更少。

眼下 Artalk 后端多站点支持还在持续跟进，像旧版本的 Artalk 的话多站点支持属于“能用”的状态，新版本希望做到“好用”的状态！是吧 @qwqcode 😉
