### ISSUE TITLE
[Bug]artalk占满内存

### ISSUE THREAD

**Issue by LeenHawk** [ArtalkJS/Artalk#458]
artalk启用之后就一直占越来越多内存：
<img width="705" alt="image" src="https://user-images.githubusercontent.com/127599173/224595791-b8343e79-6db2-4415-96b7-f5ccdcf0d004.png">
最多的时候把我服务器占满了(>2G)。。。

部署设置：
Debian sid+nginx反代+hexo+next+hexo-next-artalk

**Comment by qwqcode** [comment]
你有打开IP归属地功能吗？

**Comment by qwqcode** [comment]
如果你的评论比较多，请考虑更换 Redis 缓存。为了性能考虑 IP 归属地功能也会占用一部分内存。内存占用和缓存与 IP 归属地缓存功能有关。

`>2G` 的情况我没有遇到过，况且你截图上显示内存占用 `328.2M`，你能提供更多信息吗？

**Comment by qwqcode** [comment]
内存占用过高可能是你的服务器遭受了 DDoS 攻击，可以尝试使用 WAF 防火墙对非法请求进行拦截。

你可以看看你的 Nginx 访问日志，验证这一猜想。

**Comment by LeenHawk** [comment]
> 如果你的评论比较多，请考虑更换 Redis 缓存。为了性能考虑 IP 归属地功能也会占用一部分内存。内存占用和缓存与 IP 归属地缓存功能有关。
> 
> `>2G` 的情况我没有遇到过，况且你截图上显示内存占用 `328.2M`，你能提供更多信息吗？

我查查看，就一条评论都没有啊。。。

**Comment by LeenHawk** [comment]
> 内存占用过高可能是你的服务器遭受了 DDoS 攻击，可以尝试使用 WAF 防火墙对非法请求进行拦截。
> 
> 你可以看看你的 Nginx 访问日志，验证这一猜想。

好像就是我一刷新页面就会涨几M。。。

**Comment by LeenHawk** [comment]
> 内存占用过高可能是你的服务器遭受了 DDoS 攻击，可以尝试使用 WAF 防火墙对非法请求进行拦截。
> 
> 你可以看看你的 Nginx 访问日志，验证这一猜想。

我怀疑是Ip数据文件路径没写就会内存溢出（好傻的问题hhh

**Comment by LeenHawk** [comment]
> > 内存占用过高可能是你的服务器遭受了 DDoS 攻击，可以尝试使用 WAF 防火墙对非法请求进行拦截。
> > 你可以看看你的 Nginx 访问日志，验证这一猜想。
> 
> 我怀疑是Ip数据文件路径没写就会内存溢出（好傻的问题hhh），明天没溢出就应该是这个问题了

**Comment by LeenHawk** [comment]
> 内存占用过高可能是你的服务器遭受了 DDoS 攻击，可以尝试使用 WAF 防火墙对非法请求进行拦截。
> 
> 你可以看看你的 Nginx 访问日志，验证这一猜想。

请问一下一般默认打开IP缓存会占多少内存啊，300M正常吗，昨天晚上主要是半夜突然内存爬满了

**Comment by qwqcode** [comment]
我这边 100MB 左右，你可以看看 Artalk 日志或 Nginx 日志

**Comment by LeenHawk** [comment]
> 我这边 100MB 左右，你可以看看 Artalk 日志，有报错吗

切成redis了，好像搞定了，大概是Debian Sid可能有啥问题，之前都没报错，估计可能哪设置成我DDOS我自己了

**Comment by LeenHawk** [comment]
> 我这边 100MB 左右，你可以看看 Artalk 日志，有报错吗

作者君，能不能帮我看下我[博客](https://blog.leenhawk.com/posts/%E7%AC%AC%E4%B8%80%E7%AF%87%E5%8D%9A%E6%96%87/%E7%AC%AC%E4%B8%80%E7%AF%87%E5%8D%9A%E6%96%87/)是啥情况，挪到hugo就连不上了，应该有正确置入啊，artalk又没动。。。

**Comment by dianso** [comment]
我是debian11+goblog+artalk 评论不多，每天访问量1W PV左右，内存使用在700-1G左右。。

**Comment by DejavuMoe** [comment]
有类似的情况

- [x] Debian 12 (ARM64) 上使用 Docker 部署
- [x] 使用 Nginx 反代（Docker 外部） 
- [x] 刚切换到 Artalk 不久，评论数据不多 
- [x] 启用 IP 归属地，IP 数据库文件使用默认路径（后台配置界面「数据文件路径」留空）
- [x] 未启用 Redis 缓存

运行一周后 RAM 占用达到 2 个 GB 以上
<img width="597" alt="SCR-20230617-tvco" src="https://github.com/ArtalkJS/Artalk/assets/57177121/f7446f0d-1d88-4acc-a488-d14f47fad3f5">
手动重新启动容器后占用暂时恢复正常
<img width="595" alt="SCR-20230617-tvnt-2" src="https://github.com/ArtalkJS/Artalk/assets/57177121/2c3d0597-524d-433d-93f5-1e6cf91558ee">

过几天再看看……

**Comment by GoodBoyboy666** [comment]
如果使用redis的话情况会好很多，我总共200条评论占用28.5MB的内存

**Comment by DejavuMoe** [comment]
不知道是不是玄学，按照 @LeenHawk 的把 IP 数据库地址填了一下，最近一个多月都稳定在 300 多 MB 左右，暂时没有出现内存无限增大的情况了
<img width="732" alt="image" src="https://github.com/ArtalkJS/Artalk/assets/57177121/20996ac5-04aa-4518-ab2f-ca8ec802b2c3">

**Comment by qwqcode** [comment]
Artalk 之前默认启用缓存，以获得更好的性能提升，但对于普通博客网站来说，感知不强，且占用内存过多，这对于在轻量级服务器上部署并不友好。

由于纯 SQLite 不带缓存即可满足日常需求，新版 v2.6.0 将**默认禁用缓存**，经测试内存占用仅有 10~20MB 左右（如图）。

<img width="1237" alt="image" src="https://github.com/ArtalkJS/Artalk/assets/22412567/2e47e7e4-adde-4770-8d74-6a8f754866fc">

对于性能要求较高的网站，可以在设置手动启用缓存。内建缓存使用了 Go 依赖 [bigcache](https://github.com/allegro/bigcache)  (可能会占用较多内存)，你也可以选择使用 Redis。

新版对后端程序进行大量重构，并且添加了许多单元测试，以提高扩展性和稳定性（#560）。后续的版本将持续对 SQL 关联查询进行优化，例如解决 N+1 查询问题，以获得更好的性能。

相关内容：

- https://github.com/allegro/bigcache/issues/369
- https://utcc.utoronto.ca/~cks/space/blog/programming/GoNoMemoryFreeing
- https://go.dev/blog/pprof
- https://stackoverflow.com/questions/97197/what-is-the-n1-selects-problem-in-orm-object-relational-mapping

**Comment by dianso** [comment]
感谢，内存占用，确实少了。
看了下新的配置文件，默认关闭缓存了。
配置文件里面也少了ip数据库那些选项。

**Comment by dianso** [comment]
感谢，内存占用，确实少了。
看了下新的配置文件，默认关闭缓存了。
配置文件里面也少了ip数据库那些选项。
