### ISSUE TITLE
PageKey 允许填写 ”相对路径“ 或 ”完整URL“

### ISSUE THREAD

**Issue by qwqcode** [ArtalkJS/Artalk#47]
> > 填写完整链接能够更准确的定位到页面
> 
> @inkss 可是站点本身有地址呀，如果需要访问，利用站点设置里的 url 和页面的 url 拼接呗，可以做个判断如果地址包含了站点 url 的内容就不处理，反之拼接下。（是不是现在就是这样处理的？

> 感谢来自 @inkss 的建议，https://github.com/ArtalkJS/Artalk/issues/44#issuecomment-956247120

多站点功能是后来加入的，怎么实现更易用目前还在探索中，感谢您提出的建议，并期待更为深入的探讨。

如果站点**只有一个**域名的情况下，PageKey 不用填写完整 URL，后端可以根据这**一个域名**拼接字符串。也就是说，PageKey 是**可以填写 “相对路径”** 的。

（因为用到 PageKey 的地方有点多，**之前**时间不太充裕，直接填写**完整 URL** 作为 PageKey 不用拼接就可以摸鱼了，省去了不少代码，哈哈。我觉得这个可以有，拼接字符串这种方式将在**下一版中加入**，已经安排上了）

【站点 (Site) “本身就有的地址”】目前作用是：
    1. “Referer 合法性检测”：后端判断来自前端的请求 Header Referer 是否合法（阻止其他域名下进行非法提交）
    2. 后端设计支持：一个**站点**（项目）能有**多个域名**（多个  Site URL）（判断多个 Referer）
    3. 如果不设置 Site URL，则任何域名都可以请求，没有 “Referer 合法性检测”
    3. 依赖 PageKey 来生成邮件中的“回复”链接。（如果仅仅依靠 Site URL 来拼接字符串，如果有多个 Site URL，根据第一个 Site URL 拼接的链接是不准确的，不知道具体是哪一个网站）
    4. 依赖 PageKey 后端读取页面数据，爬取页面 `<title>` 后端显示页面标题
    5. 主要是为了**多站点**支持**多域名**，如果 PageKey 填写完整 URL，能够更加准确。

后端可以对原来**包含域名**的 PageKey 进行批量替换，因此 PageKey 完整URL换域名是不太繁琐的。

## 总结：

后续更新后端程序：

**PageKey 不再强制要求填写完整 URL，可“相对路径“也可”完整URL“**

1. 若一个站点有**多个域名**，PageKey 如果填 “相对路径”，会根据 **第一个域名** 拼接字符串。如果填 “完整链接”，会根据这个链接来，这样就能够更准确。（一个站点有多个域名，PageKey 推荐填写完整URL，但不强制要求）

2. 若一个站点只有**单个域名**，PageKey 填写 “相对路径”，就能够根据这个域名 **拼接生成** URL，这样拼接的很灵活，后端也能直接换域名。

3. 站点不允许 **没有域名**。

4. 添加单独的配置项：控制开启关闭 “Referer 合法性检测”。

_Originally posted by @qwqcode in https://github.com/ArtalkJS/Artalk/issues/44#issuecomment-956294742_

**Comment by inkss** [comment]
Go 我不熟悉，没看程序，看了一下数据库设计， 按照现有设计，sites 和 pages 是一对多，他们与 comments 表也是一对多。如果 pages 表中 key 不唯一且允许多站点的话，sites 与 pages 应该加关联表改为多对多，comments 只与 pages 表关联（主键 id）。

这样对应你总结的情况：
1.2. **不管前端 pagekey 填入的是完整还是相对地址，后端处理的时候只用 url 部分**：也就是 host 部分查 sites 表取 sites id（查一个），url 部分查 pages 表取 pages id（查多个），在关联表中寻找是否关联了，找到的话就利用 pages id 在 comments 表找当前页评论信息。
3.sites 表的 urls 应该也设置成唯一。
4.Referer 检测利用关联表处理。

![Snipaste_21-11-02_03-54-09](https://user-images.githubusercontent.com/31947043/139732943-def52d33-adca-4079-b233-ccda2fcc845e.png)
![Container instance_21-11-02_03-56-42](https://user-images.githubusercontent.com/31947043/139733286-a4f6f6a1-d7a5-426d-b7e7-eea4961dd8df.png)

此外，逻辑上每个页面至少得有一条关联站点的记录，这样子方便批量解绑/绑定站站点。
