### ISSUE TITLE
非管理员用户通知中心出现error

### ISSUE THREAD

**Issue by 0Vessel0** [ArtalkJS/Artalk#474]
Artalk版本  v2.5.2
如题，管理员用户控制中心正常，非管理员用户通知中心出现错误
![Snipaste_2023-03-29_01-20-41](https://user-images.githubusercontent.com/109258462/228319510-f9e05e62-cab1-4e57-b72d-6a4a60f94709.png)
但实际上trusted_domains已配置
日志：
![image](https://user-images.githubusercontent.com/109258462/228320718-f9aa8c1d-b634-44a6-ada8-a89acb9a10e6.png)

**Comment by mosuzi** [comment]
> Artalk版本 v2.5.2 如题，管理员用户控制中心正常，非管理员用户通知中心出现错误 ![Snipaste_2023-03-29_01-20-41](https://user-images.githubusercontent.com/109258462/228319510-f9e05e62-cab1-4e57-b72d-6a4a60f94709.png) 但实际上trusted_domains已配置 日志： ![image](https://user-images.githubusercontent.com/109258462/228320718-f9aa8c1d-b634-44a6-ada8-a89acb9a10e6.png)

是用docker部署的还是普通部署？
方便的话贴一下请求头和配置的trusted_domains

**Comment by 0Vessel0** [comment]
> 

1.使用docker部署
2.请求头为：user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.62
3.trusted_domains如图：
![image](https://user-images.githubusercontent.com/109258462/230373977-37bbd38d-20aa-4846-b850-374c2e9c7af2.png)

**Comment by 0Vessel0** [comment]
> > Artalk版本 v2.5.2 如题，管理员用户控制中心正常，非管理员用户通知中心出现错误 ![Snipaste_2023-03-29_01-20-41](https://user-images.githubusercontent.com/109258462/228319510-f9e05e62-cab1-4e57-b72d-6a4a60f94709.png) 但实际上trusted_domains已配置 日志： ![image](https://user-images.githubusercontent.com/109258462/228320718-f9aa8c1d-b634-44a6-ada8-a89acb9a10e6.png)
> 
> 是用docker部署的还是普通部署？ 方便的话贴一下请求头和配置的trusted_domains

1.使用docker部署
2.请求头为：user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.62
3.trusted_domains如图：
![image](https://user-images.githubusercontent.com/109258462/230374141-f27c3750-1aae-4e2d-a0ce-420096716436.png)

**Comment by mosuzi** [comment]
请求头里 referer 或者 Origin 的值是啥呢？
另外，你可以使用以下命令直接查看容器中的配置值，看是否正确
```shell
docker exec -it artalk bash
vi /data/artalk.yml
```

**Comment by 0Vessel0** [comment]
> 请求头里 referer 或者 Origin 的值是啥呢？ 另外，你可以使用以下命令直接查看容器中的配置值，看是否正确
> 
> ```shell
> docker exec -it artalk bash
> vi /data/artalk.yml
> ```

`referer=https://artalk.myvessel.top/sidebar/ `
请问一下trust_domains里填写的域名是需要加上端口号吗？

**Comment by mosuzi** [comment]
如果是80或者443就不要，其他的端口要的，而且你的三级域名也要加上
看你的referer，你的受信域名应该填："https://artalk.myvessel.top"

**Comment by 0Vessel0** [comment]
> 如果是80或者443就不要，其他的端口要的，而且你的三级域名也要加上 看你的referer，你的受信域名应该填："https://artalk.myvessel.top"

非常感谢，加上三级域名之后解决。我以为这里填写的是实际使用评论组件的域名。
