### ISSUE TITLE
希望能增加官方托管，愿意付费使用

### ISSUE THREAD

**Issue by shuibaco** [ArtalkJS/Artalk#475]
很喜欢Artalk的界面设计和侧边栏通知中心，数据迁移似乎也非常周到。自部署对我这种生活博主来说太复杂了，所以希望能提供官方托管，愿意在合理范围内付费。

**Comment by LeenHawk** [comment]
不太行，@qwqcode 应该在国内上大学吧，你得先有个ICP经营许可证，要不就把国内ip屏蔽了，把网站设到国外，要不然这种评论类收费托管几乎百分百会让他去喝茶的（qwq的博客没公安备案，不收费就算了，收费网站百分百会被查）

**Comment by LeenHawk** [comment]
并且UGC按规定要搞专人审查，尤其是这种批量托管，合规性过不去的。。。

**Comment by LeenHawk** [comment]
qwq要搞的话不能搞托管方式，而是调查一下大家喜欢咋部署，出收费辅助部署之类的

**Comment by LeenHawk** [comment]
说到底saas和自托管看起来功能一致，但是实际差别非常非常大

**Comment by s0urcelab** [comment]
> 不太行，@qwqcode 应该在国内上大学吧，得先有个ICP经营许可证，要不就把国内ip屏蔽了，把网站设到国外，要不然这种评论类收费托管几乎百分百会让他去喝茶的（qwq的博客没公安备案，不收费就算了，收费网站百分百会被查）

同意，没有相关服务运营经验不要轻易尝试，CN互联网特色不可不尝
