### ISSUE TITLE
启用IP属地记录，会导致后端崩溃

### ISSUE THREAD

**Issue by mosuzi** [ArtalkJS/Artalk#479]
ARtalk 版本：2.5.2
OS：centos 7.9
部署方式：docker

配置：
>ip_region:
   enabled: true
   db_path: "./data/ip2region.xdb"
   precision: "province"

只要ip转属地打开，就会崩溃，不打开就没事，报错如下图

![image](https://user-images.githubusercontent.com/43341701/230318882-7460d278-575c-41be-be07-0d09f75355c4.png)

**Comment by qwqcode** [comment]
您有根据文档说明下载 IP 归属地数据库吗？

https://artalk.js.org/guide/frontend/ip-region.html

**Comment by mosuzi** [comment]
原来如此
