### ISSUE TITLE
版本升级带来的困扰，如果可以优化会更好

### ISSUE THREAD

**Issue by fanszoro** [ArtalkJS/Artalk#486]
目前artalk在快速迭代中，但是前端部署使用的cdn地址也需要相应频繁修改。有没有办法在使用后端镜像部署时，后端镜像更新后，前端使用的cdn资源也能实时同步更新？例如前端部署时添加latest版本的资源

**Comment by qwqcode** [comment]
目前暂时的解决方案是您可以使用 Artalk 程序中内置的 JS、CSS 资源文件而非 CDN 资源。

https://artalk.js.org/guide/backend/fe-control.html#%E5%9C%A8%E5%89%8D%E7%AB%AF%E5%BC%95%E5%85%A5%E5%86%85%E7%BD%AE%E8%B5%84%E6%BA%90

**Comment by LeenHawk** [comment]
> 目前artalk在快速迭代中，但是前端部署使用的cdn地址也需要相应频繁修改。有没有办法在使用后端镜像部署时，后端镜像更新后，前端使用的cdn资源也能实时同步更新？例如前端部署时添加latest版本的资源

呃，你有用nginx吧，使用反向代理啊，比如artalk站点是artalk.example.com,nginx反代可以设置成：
```json
    location /artalk.example.com/dist {
		rewrite ^/artalk.example.com/dist/(.*) https://artalk.example.com/dist/$1 permanent;
	}
```
然后把资源设成：
```
https://artalk.example.com/dist/Artalk.css
https://artalk.example.com/dist/Artalk.js
```
就行了
