### ISSUE TITLE
在Windows server 2022上启动不了，但不报错

### ISSUE THREAD

**Issue by MiaoXsong** [ArtalkJS/Artalk#487]
运行之后不报错，但是秒退
<img width="486" alt="1681352886995" src="https://user-images.githubusercontent.com/96432890/231631887-7f8c6155-f049-49d6-a145-e40316db4c76.png">

**Comment by qwqcode** [comment]
可能是你服务器有什么安全策略把 Artalk 进程强制结束了，我尝试了 Win Server 2016 (x86_64) 和 Win 11 (x86_64) 均未出现问题。

![SCR-20230414-dgb](https://user-images.githubusercontent.com/22412567/231920311-58330a91-0d9a-4a60-a4f7-f4970a486960.png)

<img width="963" alt="image" src="https://user-images.githubusercontent.com/22412567/231920301-e2956d4b-42ad-40ea-943d-2bbc3d7b9b84.png">
