### ISSUE TITLE
退出登录按钮

### ISSUE THREAD

**Issue by musnows** [ArtalkJS/Artalk#488]
如题，目前后台管理界面似乎没有退出登录按钮。想退出登录（更换管理员账户）就只能清除浏览器缓存，希望能加上

>PS：也可能是我没找到，勿怪

**Comment by GoodBoyboy666** [comment]
> 

我也没找到，我每次都是手动清除cookie

**Comment by qwqcode** [comment]
👀 不好意思，忘记加这个按钮了

即将发布新版 v2.8.0，已经加上，感谢反馈！👀
