### ISSUE TITLE
hexo-butterfly主题获取artalk最新评论的头像问题

### ISSUE THREAD

**Issue by musnows** [ArtalkJS/Artalk#490]
如题，在使用hexo-butterfly侧边栏最新评论功能时，传回的头像所使用的avatar为
`https://sdn.geekzu.org/avatar/`，最终导致显示的头像和实际评论栏中头像不一致（还有些用户不显示头像）

但我在`artalk-go.yml`中并没有搜索到这个url，前端配置中我使用的是`https://cravatar.cn/avatar/`

请问这是artalk的api中的问题，还是hexo-butterfly主题的问题？

![image](https://user-images.githubusercontent.com/87506951/232947667-73121c39-e4d9-49f4-b87a-80b983372766.png)

**Comment by qwqcode** [comment]
您好，

在您使用 hexo-butterfly 侧边栏最新评论功能时，头像所使用的 avatar 链接确实是：`https://sdn.geekzu.org/avatar/`，而不是您在 artalk.yml 中配置的 `https://cravatar.cn/avatar/`。因此导致头像与评论栏中的头像不一致，同时有些用户的头像也无法显示。

为了解决这个问题，我建议您在 Artalk 设置界面中修改 `frontend.gravatar.mirror` 配置项，使其与 hexo-butterfly 侧边栏最新评论功能使用的头像服务保持一致。同时，我想介绍一下 Gravatar。

Gravatar 是一种全球公认头像服务，可以让用户在不同的网站上使用同一个头像。只要用户在 Gravatar 官网上注册一个账户并上传头像，其他网站就可以通过 Gravatar API 来获取用户的头像。这样可以避免在不同网站上反复上传头像的麻烦。

感谢您对我的开源项目的支持和反馈，如果您还有其他问题或建议，请随时联系我。

**Comment by musnows** [comment]
> 您好，
> 
> 在您使用 hexo-butterfly 侧边栏最新评论功能时，头像所使用的 avatar 链接确实是：`https://sdn.geekzu.org/avatar/`，而不是您在 artalk.yml 中配置的 `https://cravatar.cn/avatar/`。因此导致头像与评论栏中的头像不一致，同时有些用户的头像也无法显示。
> 
> 为了解决这个问题，我建议您在 Artalk 设置界面中修改 `frontend.gravatar.mirror` 配置项，使其与 hexo-butterfly 侧边栏最新评论功能使用的头像服务保持一致。同时，我想介绍一下 Gravatar。
> 
> Gravatar 是一种全球公认头像服务，可以让用户在不同的网站上使用同一个头像。只要用户在 Gravatar 官网上注册一个账户并上传头像，其他网站就可以通过 Gravatar API 来获取用户的头像。这样可以避免在不同网站上反复上传头像的麻烦。
> 
> 感谢您对我的开源项目的支持和反馈，如果您还有其他问题或建议，请随时联系我。

感谢！

**Comment by modiqi** [comment]
补充下，

Cravatar 是中国公认头像服务，可以让用户在不同的网站上使用同一个头像。只要用户在 Cravatar.cn 官网上注册一个账户并上传头像，其他网站就可以通过 Cravatar API 来获取用户的头像。这样可以避免在不同网站上反复上传头像的麻烦。

而且 Cravatar 的头像完全由国内开发者维护服务器均在境内，速度更快，不仅支持 Gravatar 头像回源，还可获取到用户的QQ头像、支持webp 、内容合规风险审核等优化功能。
