### ISSUE TITLE
「报告问题」将已通过的评论设置为“审阅”时，评论者IP将消失

### ISSUE THREAD

**Issue by aaro-n** [ArtalkJS/Artalk#491]
运行环境及版本：Docker， Artalk(v2.5.4 / b71b22f)已是最新版
问题重现： 评论正常展示，评论者IP已经记录（正常显示所在城市），当将评论内容标记为“审阅”时，界面不在显示评论者所在城市，标记为“已审”后也不会展示评论者所在城市。
其他建议：能不能添加“垃圾箱”功能，有些评论内容不太适合展示，标记为“审阅”又看着不爽

**Comment by qwqcode** [comment]
感谢反馈！
