### ISSUE TITLE
好像不支持 Nginx 子目录反代

### ISSUE THREAD

**Issue by eallion** [ArtalkJS/Artalk#495]
测试发现好像不支持 Nginx 子目录反代。如：
```
https://artalk.ababababab.com/sub_artalk
```

**Comment by qwqcode** [comment]
你好，

您提到 Artalk 不支持 Nginx 子目录反代，但我们需要更多信息才能帮助您解决问题。您是否已正确配置了 Nginx？如果您已经进行了正确的配置，请提供更多详细信息，例如描述一下 Artalk 出现的反应，什么功能不正常，是否能提供错误日志，以便我们更好地帮助您解决问题。

此外，以下是一个 Nginx 配置示例，供您参考：

```bash
Copy code
location /sub_artalk {
    proxy_pass http://localhost:8000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
```

请注意，这只是一个基本示例，具体的配置取决于反代的应用程序和服务器的设置。您可能需要根据您的具体情况进行适当的修改。

**Comment by eallion** [comment]
- Nginx 配置应该是没问题的，在用的友商产品差不多的配置稳定运行中。
- 用 `sub_artalk` 子目录反代后，访问子目录，还是会重定向到根目录。
`https://artalk.ababababab.com/sub_artalk` -> `https://artalk.ababababab.com/sidebar` 并且404。
不是访问的`https://artalk.ababababab.com/sub_artalk/sidebar`
- 访问 `https://artalk.ababababab.com/sub_artalk/dist/Artalk.js` 静态资源能访问到
- 手动指定登录地址：`https://artalk.ababababab.com/sub_artalk/sidebar/#/login`能出现登录框，但是不能登录。

**Comment by qwqcode** [comment]
请尝试如下 Nginx 配置：

```nginx
location /sub/ {
    proxy_redirect off;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass http://127.0.0.1:23366/;
}
```

请注意 `location /sub/` 末尾需要带上斜杠，`http://127.0.0.1:23366/` 末尾也需要带上斜杠。我已在自己的服务器尝试该配置，且 Artalk 正常使用。

---

在 nginx 配置中，`location /sub/` 表示匹配以 `/sub/` 开头的请求路径，而 `proxy_pass http://127.0.0.1:23366/;` 则表示将请求转发到 `http://127.0.0.1:23366/` 地址。

带斜杠和不带斜杠的区别在于，斜杠的存在影响了请求的匹配和转发。如果 `location /sub/` 后面带有斜杠，表示匹配以 `/sub/` 开头的路径，如 `/sub/hello/world`；如果不带斜杠，表示匹配以 `/sub` 开头的路径，如 `/subhello/world`。这就是路径匹配的区别。

而 `proxy_pass` 后面的地址如果带有斜杠，表示将请求转发到指定的路径下，如 `http://127.0.0.1:23366/` 表示将请求转发到 `http://127.0.0.1:23366/` 下；如果不带斜杠，表示将请求转发到指定的地址上，如 `http://127.0.0.1:23366` 表示将请求转发到 `http://127.0.0.1:23366` 上。这就是转发地址的区别。

综上所述，带斜杠和不带斜杠的区别在于路径匹配和转发地址的不同。在实际应用中，需要根据具体需求来选择合适的方式。

**Comment by eallion** [comment]
确实是这个问题，现在正常了。

**Comment by eallion** [comment]
如果有可能还是建议在应用里做兼容处理，带不带行尾slash都定向到`/`

**Comment by qwqcode** [comment]
> 如果有可能还是建议在应用里做兼容处理，带不带行尾slash都定向到`/`

这是 Nginx 的配置问题，你所有的子目录代理都应该这样配置吧

**Comment by eallion** [comment]
我的意思是，`/abc/123/api/conf`和`/abc/123/api/conf/`都定向到`/abc/123/api/conf/`，防呆设计，忽略用户是否输入了末尾的`/`。
