### ISSUE TITLE
全新 UI 设计 Sidebar Layer (通知中心+控制台)

### ISSUE THREAD

**Issue by qwqcode** [ArtalkJS/Artalk#50]
![](https://user-images.githubusercontent.com/22412567/140274501-7ba90995-35dc-4748-b4ec-e2d2755576c4.png)

**Comment by xiamuguizhi** [comment]
强的！！

**Comment by qwqcode** [comment]
新版 v2.1 现已发布，欢迎体验 🥳

https://github.com/ArtalkJS/Artalk/releases/tag/v2.1.1
