### ISSUE TITLE
upgit 上传失败 和 页面标题 不正常问题

### ISSUE THREAD

**Issue by jerryc127** [ArtalkJS/Artalk#501]
配置
```
# Upload
img_upload:
  # Enable image upload
  enabled: true
  # Image storage
  path: "./data/artalk-img/"
  # Image size limit (unit: MB)
  max_size: 5
  # Image link base path (default: "/static/images/")
  public_path: null
  # Upgit config
  upgit:
    # Enable Upgit
    enabled: true
    # Command line arguments
    exec: "./data/upgit/upgit -c ./data/upgit/config.toml -t ./data/artalk-img"
    # Delete local image after upload success
    del_local: false
```

报错
```
2023-05-01 14:32:35.541339494 +0800 CST m=+0.000774285[INFO ] Started
2023-05-01 14:32:35.541542455 +0800 CST m=+0.000977246[INFO ] uploader: github
2023-05-01 14:32:35.541668335 +0800 CST m=+0.001103126[INFO ] uploading #TASK_0 ./data/artalk-img/20230501-143235.537.png
2023-05-01 14:32:36.150980453 +0800 CST m=+0.610415244[INFO ] failed to upload #TASK_0 ./data/artalk-img/20230501-143235.537.png : unexpected status code 422. response: {"message":"path contains a malformed path component","errors":[{"resource":"Commit","field":"path","code":"invalid"}],"documentation_url":"https://docs.github.com/rest/reference/repos#create-or-update-file-contents"}

```

**Comment by qwqcode** [comment]
你好，

这个问题可能出在 Upgit 对 Github API 的调用上。

从错误日志中可以看到，上传图片时出现了unexpected status code 422的错误。这意味着Github API在上传文件时返回了一个无效的状态码。根据错误信息，似乎是path contains a malformed path component，这可能意味着您上传的文件路径包含了不合法的字符。

为了解决这个问题，您可以尝试修改上传文件的路径或文件名，确保它们不包含特殊字符或不合法的字符。请检查upgit的配置是否正确，确保您已经正确地配置了upgit。另外，您也可以尝试使用其他的上传方式或API，或者查阅Github API文档以获取更详细的错误信息和解决方法。

如果您还有其他问题或建议，请随时联系我。

**Comment by jerryc127** [comment]
> 你好，
> 
> 
> 
> 这个问题可能出在 Upgit 对 Github API 的调用上。
> 
> 
> 
> 从错误日志中可以看到，上传图片时出现了unexpected status code 422的错误。这意味着Github API在上传文件时返回了一个无效的状态码。根据错误信息，似乎是path contains a malformed path component，这可能意味着您上传的文件路径包含了不合法的字符。
> 
> 
> 
> 为了解决这个问题，您可以尝试修改上传文件的路径或文件名，确保它们不包含特殊字符或不合法的字符。请检查upgit的配置是否正确，确保您已经正确地配置了upgit。另外，您也可以尝试使用其他的上传方式或API，或者查阅Github API文档以获取更详细的错误信息和解决方法。
> 
> 
> 
> 如果您还有其他问题或建议，请随时联系我。

文件名应该是 artalk 生成的吧

**Comment by pluveto** [comment]
路径不合法，检查一下 upgit 的配置，例如仓库名称

**Comment by jerryc127** [comment]
> 路径不合法，检查一下 upgit 的配置，例如仓库名称

这个没问题，我试着单独上传一张图片
upgit 单独上传一张图片，会自动重命名再上传，都上传成功。
上传文件夹，不会重命名。。估计 artalk生成的图片名称不符合github的命名吧

**Comment by pluveto** [comment]
你可以打开 verbose 模式看看生成的路径是怎样的

**Comment by jerryc127** [comment]
```
[2023-05-09.20:16:09.260121]  INFO 服务重启完毕
[2023-05-09.20:16:17.370384] ERROR IMG_UPLOAD: [upgit] upgit output: [TRACE] LocalPaths = ['./data/artalk-img/20230509-201617.091.png']
        TargetDir = './data/artalk-img'
        Verbose = true
        Wait = false
        ConfigFile = './data/upgit/config.toml'
        Clean = false
        Raw = false
        NoLog = false
        Uploader = ''
        OutputType = 'stdout'
        OutputFormat = 'url'
        ApplicationPath = ''
[TRACE] default_uploader = 'github'
        rename = '{year}/{month}/upgit_{year}{month}{day}_{unixts}{ext}'
        [output_formats]
        bbcode = '[img]{url}[/img]'
        html = '<img src="{url}" loading="lazy" />'
        markdown = '![{url_fname}]({url})'
        markdown-simple = '![]({url})'
        url = '{url}'
[INFO ] uploader: github
[INFO ] uploading #TASK_0 ./data/artalk-img/20230509-201617.091.png
[TRACE] PUT https://api.github.com/repos/jerryc127/CDN/contents/./data/artalk-img/20230509-201617.091.png
[TRACE] response body: {"message":"path contains a malformed path component","errors":[{"resource":"Commit","field":"path","code":"invalid"}],"documentation_url":"https://docs.github.com/rest/reference/repos#create-or-update-file-contents"}
[INFO ] failed to upload #TASK_0 ./data/artalk-img/20230509-201617.091.png : unexpected status code 422. response: {"message":"path contains a malformed path component","errors":[{"resource":"Commit","field":"path","code":"invalid"}],"documentation_url":"https://docs.github.com/rest/reference/repos#create-or-update-file-contents"}
Failed: unexpected status code 422. response: {"message":"path contains a malformed path component","errors":[{"resource":"Commit","field":"path","code":"invalid"}],"documentation_url":"https://docs.github.com/rest/reference/repos#create-or-update-file-contents"}
[2023-05-09.20:16:17.370543] ERROR 响应: POST /api/img-upload ==> "通过 upgit 上传图片失败" host=localhost id= ip=219.77.212.94 referer=https://blog.crazywong.com/ status=200 user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.35

```

**Comment by qwqcode** [comment]
1. 你可以尝试在前端对 `pageTitle` 进行指定，确保获取到正确的页面标题。

    可参考：[官方文档 - 前端配置](https://artalk.js.org/guide/frontend/config.html#pagetitle)

2. 如果在前端未指定 `pageTitle`，则将自动获取 `document.title`。

    你可以检查你页面 html 代码，查看是否 `<title>标签</title>` 的值是否有误
    （你给出截图中的标题可能是因为 title 值已对特殊字符进行转义，被 Artalk 错误读取所导致）


如果做过以上检查和尝试，问题仍然存在，能提供一下这条评论对应页面在数据库中的原始数据吗？这样能确定究竟是 Artalk 生成邮件存在问题，还是你前端配置有误导致的问题。

**Comment by jerryc127** [comment]
> 

我没有指定，而且 title 也正常

我看了下控制中心，title 也是被转义的

![image](https://github.com/ArtalkJS/Artalk/assets/16351105/ba2292e9-8766-4f36-a9f0-1a8f14c2135c)


我是用 Artransfer-CLI 迁移 waline 的数据的
看了下迁移后的 artrans 文件，也是转义过的

**Comment by qwqcode** [comment]
那可能是迁移时候的问题，和邮件模版没有关系

你可以点击顶部的刷新按钮刷新一下 title 试试

**Comment by jerryc127** [comment]
> 那可能是迁移时候的问题，和邮件模版没有关系
> 
> 你可以点击顶部的刷新按钮刷新一下 title 试试

刷新后，显示的还是 转义后的

![image](https://github.com/ArtalkJS/Artalk/assets/16351105/91178ad3-4b43-4d10-86c8-99834fdac3c8)

**Comment by qwqcode** [comment]
我看了看你页面的 HTML 代码，title 标签内容被转义了。你可以尝试修改你的主题，让 title 内容不转义为 HTML 实体。然后再点击一键刷新按钮。

![SCR-20230510-jnk](https://github.com/ArtalkJS/Artalk/assets/22412567/46ce011e-e420-4184-b62f-0624e9b80163)

**Comment by qwqcode** [comment]
参考代码：

```js
// 引入 mysql 模块
const mysql = require('mysql');

// 创建数据库连接
const connection = mysql.createConnection({
  host: 'localhost', // 数据库主机地址
  user: 'root',      // 数据库用户名
  password: 'password',  // 数据库密码
  database: 'artalk' // 数据库名
});

// 连接数据库
connection.connect();

// SQL 查询语句，查询 pages 表中的所有数据
const sql = 'SELECT * FROM pages';

// 执行 SQL 查询语句
connection.query(sql, (error, results, fields) => {
  if (error) throw error;

  // 遍历查询结果
  results.forEach((row) => {
    // 将 title 列中的 HTML 内容实体反解析为原始内容
    const decodedTitle = decodeHtmlEntity(row.title);

    // 更新数据库中的数据，将解析后的数据写回 title 列
    connection.query(
      'UPDATE pages SET title = ? WHERE id = ?',
      [decodedTitle, row.id],
      (error, results, fields) => {
        if (error) throw error;
        console.log(`Updated row ${row.id}: ${row.title} -> ${decodedTitle}`);
      }
    );
  });

  // 关闭数据库连接
  connection.end();
});

// 解析 HTML 内容实体的函数
function decodeHtmlEntity(str) {
  const doc = new DOMParser().parseFromString(str, 'text/html');
  return doc.documentElement.textContent;
}
```

在使用 JavaScript 连接 MySQL 数据库之前，需要确保已经安装并启动了 MySQL 数据库，也需要安装 mysql 模块，可以使用 npm 包管理器进行安装，安装命令为：`npm install mysql`。

在上述代码中，我们首先创建了一个数据库连接，然后使用 SQL 查询语句查询了 pages 表中的所有数据，并遍历查询结果。对于每一行数据，我们使用 decodeHtmlEntity 函数将 title 列中的 HTML 内容实体反解析为原始内容，并使用 SQL 更新语句将解析后的内容写回数据库中。最后关闭数据库连接。

**Comment by qwqcode** [comment]
如果你是用的是 SQLite 数据库，可以尝试以下脚本：

```js
// 引入 sqlite3 模块
const sqlite3 = require('sqlite3').verbose();

// 创建数据库连接
const db = new sqlite3.Database('./mydatabase.db');

// SQL 查询语句，查询 pages 表中的所有数据
const sql = 'SELECT * FROM pages';

// 执行 SQL 查询语句
db.all(sql, [], (error, rows) => {
  if (error) throw error;

  // 遍历查询结果
  rows.forEach((row) => {
    // 将 title 列中的 HTML 内容实体反解析为原始内容
    const decodedTitle = decodeHtmlEntity(row.title);

    // 更新数据库中的数据，将解析后的数据写回 title 列
    db.run(
      'UPDATE pages SET title = ? WHERE id = ?',
      [decodedTitle, row.id],
      function(error) {
        if (error) throw error;
        console.log(`Updated row ${row.id}: ${row.title} -> ${decodedTitle}`);
      }
    );
  });

  // 关闭数据库连接
  db.close();
});

// 解析 HTML 内容实体的函数
function decodeHtmlEntity(str) {
  const doc = new DOMParser().parseFromString(str, 'text/html');
  return doc.documentElement.textContent;
}
```

**Comment by qwqcode** [comment]
> > > ```
> > > [2023-05-09.20:16:09.260121]  INFO 服务重启完毕
> > > [2023-05-09.20:16:17.370384] ERROR IMG_UPLOAD: [upgit] upgit output: [TRACE] LocalPaths = ['./data/artalk-img/20230509-201617.091.png']
> > >         TargetDir = './data/artalk-img'
> > >         Verbose = true
> > >         Wait = false
> > >         ConfigFile = './data/upgit/config.toml'
> > >         Clean = false
> > >         Raw = false
> > >         NoLog = false
> > >         Uploader = ''
> > >         OutputType = 'stdout'
> > >         OutputFormat = 'url'
> > >         ApplicationPath = ''
> > > [TRACE] default_uploader = 'github'
> > >         rename = '{year}/{month}/upgit_{year}{month}{day}_{unixts}{ext}'
> > >         [output_formats]
> > >         bbcode = '[img]{url}[/img]'
> > >         html = '<img src="{url}" loading="lazy" />'
> > >         markdown = '![{url_fname}]({url})'
> > >         markdown-simple = '![]({url})'
> > >         url = '{url}'
> > > [INFO ] uploader: github
> > > [INFO ] uploading #TASK_0 ./data/artalk-img/20230509-201617.091.png
> > > [TRACE] PUT https://api.github.com/repos/jerryc127/CDN/contents/./data/artalk-img/20230509-201617.091.png
> > > [TRACE] response body: {"message":"path contains a malformed path component","errors":[{"resource":"Commit","field":"path","code":"invalid"}],"documentation_url":"https://docs.github.com/rest/reference/repos#create-or-update-file-contents"}
> > > [INFO ] failed to upload #TASK_0 ./data/artalk-img/20230509-201617.091.png : unexpected status code 422. response: {"message":"path contains a malformed path component","errors":[{"resource":"Commit","field":"path","code":"invalid"}],"documentation_url":"https://docs.github.com/rest/reference/repos#create-or-update-file-contents"}
> > > Failed: unexpected status code 422. response: {"message":"path contains a malformed path component","errors":[{"resource":"Commit","field":"path","code":"invalid"}],"documentation_url":"https://docs.github.com/rest/reference/repos#create-or-update-file-contents"}
> > > [2023-05-09.20:16:17.370543] ERROR 响应: POST /api/img-upload ==> "通过 upgit 上传图片失败" host=localhost id= ip=219.77.212.94 referer=https://blog.crazywong.com/ status=200 user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.35
> > > ```
> > 
> > 
> > 尝试将 `img_upload.upgit.exec` 配置项中 `-t` 参数值从 `./data/artalk-img` 修改为 `data/artalk-img`：
> > ```diff
> > - exec: "./data/upgit/upgit -c ./data/upgit/config.toml -t ./data/artalk-img"
> > + exec: "./data/upgit/upgit -c ./data/upgit/config.toml -t data/artalk-img"
> > ```
> 
> 谢谢 解决了
> 

upgit 那边可以处理 `-t` 参数拼接生成的请求 URL，将 `https://api.github.com/repos/jerryc127/CDN/contents/./data/artalk-img/20230509-201617.091.png` 链接中的 `/./` 相对路径这个特殊字符去掉，避免 GitHub API 请求发生异常。

(cc @pluveto)

**Comment by jerryc127** [comment]
> 如果你是用的是 SQLite 数据库，可以尝试以下脚本：
> 
> ```js
> // 引入 sqlite3 模块
> const sqlite3 = require('sqlite3').verbose();
> 
> // 创建数据库连接
> const db = new sqlite3.Database('./mydatabase.db');
> 
> // SQL 查询语句，查询 pages 表中的所有数据
> const sql = 'SELECT * FROM pages';
> 
> // 执行 SQL 查询语句
> db.all(sql, [], (error, rows) => {
>   if (error) throw error;
> 
>   // 遍历查询结果
>   rows.forEach((row) => {
>     // 将 title 列中的 HTML 内容实体反解析为原始内容
>     const decodedTitle = decodeHtmlEntity(row.title);
> 
>     // 更新数据库中的数据，将解析后的数据写回 title 列
>     db.run(
>       'UPDATE pages SET title = ? WHERE id = ?',
>       [decodedTitle, row.id],
>       function(error) {
>         if (error) throw error;
>         console.log(`Updated row ${row.id}: ${row.title} -> ${decodedTitle}`);
>       }
>     );
>   });
> 
>   // 关闭数据库连接
>   db.close();
> });
> 
> // 解析 HTML 内容实体的函数
> function decodeHtmlEntity(str) {
>   const doc = new DOMParser().parseFromString(str, 'text/html');
>   return doc.documentElement.textContent;
> }
> ```

感谢解答
这个方法治标不治本，只能更新旧的文章，如果有新的，依旧会是转义的标题

经过你的提醒，我发现是我用的 gulp-html-minifier-terser 压缩html时，把中文转义了。
现已更改，可以显示中文了

感谢你的帮助，这个评论很棒

**Comment by qwqcode** [comment]
很高兴听到你已经解决了这个问题并且感谢我的帮助。如果你还有其他问题，随时在这个issue下留言或者创建新的issue。谢谢！

**Comment by jerryc127** [comment]
突然想起一个问题，数据库使用的问题。

我用 aaPanelLinux panel ,创建了一个数据库 mysql
其余配置如下
![image](https://github.com/ArtalkJS/Artalk/assets/16351105/47e7b1d3-c2ee-44ee-8d42-38500e47868f)


为什么把 artalk设置了的 mysql 会连接不上？

**Comment by qwqcode** [comment]
> 突然想起一个问题，数据库使用的问题。
> 
> 我用 aaPanelLinux panel ,创建了一个数据库 mysql 其余配置如下 ![image](https://user-images.githubusercontent.com/16351105/237300800-47e7b1d3-c2ee-44ee-8d42-38500e47868f.png)
> 
> 为什么把 artalk设置了的 mysql 会连接不上？

如果你的 Artalk 是通过 docker 方式部署，可以修改配置连接 MySQL 数据库地址为 `172.17.0.1` 替换 `127.0.0.1` 以访问宿主机的 MySQL 服务。

参考：https://docs.docker.com/network/network-tutorial-standalone/

**Comment by jerryc127** [comment]
> > 突然想起一个问题，数据库使用的问题。
> > 我用 aaPanelLinux panel ,创建了一个数据库 mysql 其余配置如下 ![image](https://user-images.githubusercontent.com/16351105/237300800-47e7b1d3-c2ee-44ee-8d42-38500e47868f.png)
> > 为什么把 artalk设置了的 mysql 会连接不上？
> 
> 如果你的 Artalk 是通过 docker 方式部署，可以修改配置连接 MySQL 数据库地址为 `172.17.0.1` 替换 `127.0.0.1` 以访问宿主机的 MySQL 服务。
> 
> 参考：https://docs.docker.com/network/network-tutorial-standalone/

要把 mysql 的 permission 改成 everyone ， 才可以用 172.17.0.1 访问
这是正常的么？mysql 的 permission 不能是 localhost ?

**Comment by qwqcode** [comment]
> > > 突然想起一个问题，数据库使用的问题。
> 
> > > 我用 aaPanelLinux panel ,创建了一个数据库 mysql 其余配置如下 ![image](https://user-images.githubusercontent.com/16351105/237300800-47e7b1d3-c2ee-44ee-8d42-38500e47868f.png)
> 
> > > 为什么把 artalk设置了的 mysql 会连接不上？
> 
> > 
> 
> > 如果你的 Artalk 是通过 docker 方式部署，可以修改配置连接 MySQL 数据库地址为 `172.17.0.1` 替换 `127.0.0.1` 以访问宿主机的 MySQL 服务。
> 
> > 
> 
> > 参考：https://docs.docker.com/network/network-tutorial-standalone/
> 
> 
> 
> 要把 mysql 的 permission 改成 everyone ， 才可以用 172.17.0.1 访问
> 
> 这是正常的么？mysql 的 permission 不能是 localhost ?

你可以把 permission 改成 everyone，然后防火墙禁止外网访问 3306 端口；或者看看能否单独允许 172.17.0.1 访问。

**Comment by jerryc127** [comment]
> 者看看能否单独允许 172.17.0

改成 everyone 也可以吧，禁用的话，不然用电脑连接 Mysql 连接不上。


应该没什么问题了
最后提一个 feat 吧
就是希望导出的时候，可以单独导出一个站点的内容
