### ISSUE TITLE
评论投票逻辑问题

### ISSUE THREAD

**Issue by monsterxcn** [ArtalkJS/Artalk#51]
**现状**

用户可以同时给某条评论点一个赞、点一个踩

**预期**

用户点赞应该消除曾经点过的踩，点踩应该消除曾经点过的赞

**复现**

进入 https://artalk.js.org ，任选一条评论，点赞并点踩，观察到赞和踩的数值最终同时 +1

**Comment by qwqcode** [comment]
已在 v2.1.0 版本中修复
