### ISSUE TITLE
添加WeAvatar支持

### ISSUE THREAD

**Issue by DevHaoZi** [ArtalkJS/Artalk#511]
doc: [https://weavatar.com/doc](https://weavatar.com/doc)

**Comment by qwqcode** [comment]
接入兼容 Gravatar API 的头像服务可以修改前端配置：`https://weavatar.com/avatar/`

<img width="388" alt="image" src="https://github.com/ArtalkJS/Artalk/assets/22412567/af615143-eb27-489d-98b7-8f6b13c52292">
