### ISSUE TITLE
database disk image is malformed

### ISSUE THREAD

**Issue by kkfive** [ArtalkJS/Artalk#522]
rtalk    | ERROR INSERT INTO `users` (`created_at`,`updated_at`,`deleted_at`,`name`,`email`,`link`,`password`,`badge_name`,`badge_color`,`last_ip`,`last_ua`,`is_admin`,`site_names`,`receive_email`,`is_in_conf`) VALUES ("2023-06-09 10:34:56.869","2023-06-09 10:34:56.869",NULL,"222","i@tt.tt","","","","","","",false,"",true,false) RETURNING `id` [386.038µs] error=database disk image is malformed
artalk    | ERROR Create User error: database disk image is malformed
artalk    | ERROR Cannot get user or page
artalk    | ERROR 响应: POST /api/add ==> "评论失败" host=10.0.8.10:23366 id=158ff1a30cbb137474872332dcfe4c9c ip=36.112.126.78 referer=http://localhost:8080/ status=200 user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.37

**Comment by qwqcode** [comment]
https://www.cnblogs.com/netlyf/p/4586515.html

**Comment by kkfive** [comment]
不太行

**Comment by kkfive** [comment]
不太行  新的导不进去 
![image](https://github.com/ArtalkJS/Artalk/assets/82026204/03cfe659-63b0-4eab-9bf3-93ca6af04cf3)
已 tg 联系您
