### ISSUE TITLE
How to find admin password or reset admin password?

### ISSUE THREAD

**Issue by TinoGuo** [ArtalkJS/Artalk#524]
I set up the admin half years ago but I forgot the password. There is no entry to reset or find password, can u guide me how to achieve it? thx

**Comment by qwqcode** [comment]
https://artalk.js.org/guide/backend/multi-site.html

execute command below to reset admin account password:

```bash
./artalk admin
```

or using docker:

```bash
docker exec -it artalk artalk admin
```
