### ISSUE TITLE
部署失败，没法打开后端

### ISSUE THREAD

**Issue by misaka-fans** [ArtalkJS/Artalk#529]
使用docker部署之后打开http://your_domain:8080显示无法访问此页面

用的阿里云自带的docker

可以正常创建管理员账户，但是后端http://your_domain:8080打不开，请问应该如何解决awa

**Comment by ning0818** [comment]
把your_domain改成你自己的域名！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！

**Comment by misaka-fans** [comment]
> 把your_domain改成你自己的域名！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！

@ning0818 这个我知道！！！
换成自己的域打不开啊

**Comment by ning0818** [comment]
> > 把your_domain改成你自己的域名！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！
> 
> @ning0818 这个我知道！！！ 换成自己的域打不开啊

用ip

**Comment by misaka-fans** [comment]
> > > 把your_domain改成你自己的域名！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！
> 
> > 
> 
> > @ning0818 这个我知道！！！ 换成自己的域打不开啊
> 
> 
> 
> 用ip

也会显示服务器无响应，但是阿里云上看服务器好好的，而且我这里ssh连接它没有任何问题

**Comment by ning0818** [comment]
> 8080

安全组放开8080端口

> > > > 把your_domain改成你自己的域名！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！
> > 
> > 
> > > 
> > 
> > 
> > > @ning0818 这个我知道！！！ 换成自己的域打不开啊
> > 
> > 
> > 用ip
> 
> 也会显示服务器无响应，但是阿里云上看服务器好好的，而且我这里ssh连接它没有任何问题

**Comment by qwqcode** [comment]
看来问题似乎解决了，感谢热心网友的解答，issue没问题就关闭啦，感谢使用 Artalk，祝您生活愉快！
