### ISSUE TITLE
无法升级？

### ISSUE THREAD

**Issue by ning0818** [ArtalkJS/Artalk#530]
他没检索到新版本
![image](https://github.com/ArtalkJS/Artalk/assets/117955401/ef9c284f-0bb6-4c1a-9916-4823da3e7e68)

**Comment by qwqcode** [comment]
由于 v2.3.0 版本之前进行过一次代码仓库迁移，版本过旧的 Artalk 无法执行自动升级（upgrade）命令，但您可以手动更新 Artalk，谢谢。

您可以参考：https://artalk.js.org/guide/deploy.html
