### ISSUE TITLE
文章title获取不准确的bug

### ISSUE THREAD

**Issue by eryajf** [ArtalkJS/Artalk#532]
貌似当我一次更新两篇文章的时候，文章的title获取就总是有问题的，如下图

<img width="545" alt="image" src="https://github.com/ArtalkJS/Artalk/assets/33259379/a32b15c7-337e-40a6-97a6-a7d27c578564">

**Comment by qwqcode** [comment]
问题依然存在吗？可以检查下前端的 `pageKey` 参数是否正确配置
