### ISSUE TITLE
不能自己建表？

### ISSUE THREAD

**Issue by Sincejunly** [ArtalkJS/Artalk#541]
![image](https://github.com/ArtalkJS/Artalk/assets/96775034/e40d18f0-592e-4aa1-a872-2b4e57eef753)
mysql刚建空数据库，居然不能自己建表了

**Comment by qwqcode** [comment]
重启 Artalk 试试？

**Comment by Sincejunly** [comment]
> 重启 Artalk 试试？

试了下不行，用phpmyadmin建的默认，以前没问题的。

**Comment by Sincejunly** [comment]
> 重启 Artalk 试试？

旧版可以，已测
