### ISSUE TITLE
更新提示怎么关？

### ISSUE THREAD

**Issue by Sincejunly** [ArtalkJS/Artalk#542]
前端的更新提示

**Comment by qwqcode** [comment]
https://artalk.js.org/guide/frontend/config.html#%E7%89%88%E6%9C%AC%E6%A3%80%E6%B5%8B

**Comment by Sincejunly** [comment]
> https://artalk.js.org/guide/frontend/config.html#%E7%89%88%E6%9C%AC%E6%A3%80%E6%B5%8B

好的谢谢，作者好活跃啊
