### ISSUE TITLE
Valine评论导入错误

### ISSUE THREAD

**Issue by JadeVane** [ArtalkJS/Artalk#561]
试着导入Valine的评论，但是一直报错，可能跟版本有关？这个Valine以前是用Leancloud国际版部署的

![图片](https://github.com/ArtalkJS/Artalk/assets/34258753/1f13ed82-c8da-465e-847d-4b15a3987720)

想自己写脚本转的，但没找到`id`和`rid`的生成规则，这个有在文档里面写吗，对Go不熟悉，看源码就搞不来了

**Comment by qwqcode** [comment]
能提供部分 Json 文件内容吗？

如果你熟悉 JS 也可以看看前端 Artransfer 工具的代码哦：

https://github.com/ArtalkJS/Artransfer/blob/master/src/encoder/ValineEncoder.ts
