### ISSUE TITLE
BUG：sidebar-页面-编辑key变更后出错

### ISSUE THREAD

**Issue by dianso** [ArtalkJS/Artalk#581]
BUG：sidebar-页面-编辑key变更后出错

比如我的页面原来是a.com/1，我转移了页面，将其改为a.com/2，这样原来页面的评论浏览量都会转移过来

但是数据库里只更改了pages表的key值，accessible_url值并未更改

会出现这么一种情况，在sidebar-页面点击修改后的页面，还会跳转到a.com/1

如果有人在a.com/2留言后，在sidebar-页面点击评论，打开的还是a.com/1

目前我是用sqlite3 /*/artalk.db
然后手动执行sql语句来同时修改两个值

希望后期可以同时修改

**Comment by qwqcode** [comment]
`accessible_url` 预期应该为动态计算值，之前某个版本没有排除这个字段导致持久化保存到了数据表中。

`accessible_url` 这个数据表字段目前的最新版已经是移除了，问题应该已经解决。

**Comment by dianso** [comment]
我看最新版的artalk.db，依然有这个字段，是需要手动删除吗
