### ISSUE TITLE
panic: time: missing Location in call to Time.In

### ISSUE THREAD

**Issue by rashidgaliev** [ArtalkJS/Artalk#583]
Artalk (v2.6.2/a0892fc)

 -> A Selfhosted Comment System.
 -> https://artalk.js.org

docker image: artalk/artalk-go:latest

-------------------------------

panic: time: missing Location in call to Time.In

goroutine 35 [running]:
time.Time.In(...)
        /usr/local/go/src/time/time.go:1146
github.com/gofiber/fiber/v2/middleware/logger.New({0xc0007a3ad0, 0x1, 0x1})
        /go/pkg/mod/github.com/gofiber/fiber/v2@v2.48.0/middleware/logger/logger.go:39 +0x7d8
github.com/ArtalkJS/Artalk/server.Serve(0xc0006ff8c0)
        /source/server/server.go:55 +0xf0
github.com/ArtalkJS/Artalk/cmd.NewServeCommand.func1(0xc00041ec00?, {0xc000517300?, 0x0?, 0x8?})
        /source/cmd/server.go:24 +0xb2
github.com/spf13/cobra.(*Command).execute(0xc00041ec00, {0xc000517280, 0x8, 0x8})
        /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0xc00041e900)
        /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/ArtalkJS/Artalk/cmd.(*ArtalkCmd).Launch.func2()
        /source/cmd/base.go:151 +0x25
created by github.com/ArtalkJS/Artalk/cmd.(*ArtalkCmd).Launch in goroutine 1
        /source/cmd/base.go:150 +0xbc

**Comment by qwqcode** [comment]
Greetings, could you kindly verify whether your time zone settings have been configured correctly? For instance, please ensure they are set to values like "America/New_York" or "Asia/Shanghai." 😄

You can refer to this link for more information: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

We've taken your valuable feedback into account and made adjustments to the error messages to make them less confusing. Your input is greatly appreciated as we continue to improve this open-source project. Thank you!

**Comment by rashidgaliev** [comment]
Hello!

TZ | Asia/Shanghai - from portainer Container details.

**Comment by qwqcode** [comment]
Can you try upgrading to the latest version that was just released (v2.6.3) and see if the error still there?

**Comment by rashidgaliev** [comment]
Hi! After update to v2.6.3 everything is OK! Thanks!

**Comment by qwqcode** [comment]
Alright, the issue has been resolved, and this issue is now closed.
