### ISSUE TITLE
手机游览器，有个别不能正常显示或加载？？

### ISSUE THREAD

**Issue by xiamuguizhi** [ArtalkJS/Artalk#59]
##  系统自带游览器  无法正常显示

![](https://vkceyugu.cdn.bspapp.com/VKCEYUGU-2fa930c8-feec-4942-ac88-ba3781377bb0/3f5563ba-d849-4170-b6ad-895c4c0698e0.jpg)

## 夸克游览器  无法正常显示

![](https://vkceyugu.cdn.bspapp.com/VKCEYUGU-2fa930c8-feec-4942-ac88-ba3781377bb0/c7a2ecea-d30f-4ba3-ace0-ca8c5365354a.jpg)

## QQ系列正常显示评论， X 浏览器也正常显示

![](https://vkceyugu.cdn.bspapp.com/VKCEYUGU-2fa930c8-feec-4942-ac88-ba3781377bb0/7436dfee-0025-41ac-a622-f2a1351957c3.jpg)

是否是游览器内核问题导致的还是其他？   今天有人给我反馈了我才知道  我用的QQ游览器显示正常，我以为可能就自己博客出现这个问题 ，试了一下官网的文档 评论 也是一样 不能正常显示...

**Comment by qwqcode** [comment]
感谢反馈，我看看

**Comment by xiamuguizhi** [comment]
@qwqcode 现在是 修复了吗

**Comment by xiamuguizhi** [comment]
已修复~

系统自带游览器 夸克 显示正常！！

**Comment by qwqcode** [comment]
v2.1.2 已发布 🥳
