### ISSUE TITLE
前端样式 `发送评论`按钮 和 `Powered By` 样式重叠在一起 

### ISSUE THREAD

**Issue by zkeq** [ArtalkJS/Artalk#590]
点击回复时, 复现 (此时发送评论按钮失效无法点击):

<img width="370" alt="image" src="https://github.com/ArtalkJS/Artalk/assets/62864752/a586a272-a8c7-4c9d-9ccf-331aedf98364">

复现地址: https://artalk.js.org/guide/backend/email.html

<img width="1414" alt="image" src="https://github.com/ArtalkJS/Artalk/assets/62864752/9fe7bbfd-8c30-46b5-9be7-f0bee4236a7c">

此样式错误只出现在电脑端 手机端无此bug

**Comment by qwqcode** [comment]
感谢反馈！
