### ISSUE TITLE
bug：更新前端配置会导致重复提交（事件重复绑定）

### ISSUE THREAD

**Issue by TooBug** [ArtalkJS/Artalk#592]
调用`.update(conf)`方法，会发生：

- 触发`conf-loaded`事件
- 调用`initEditorFuncs()`方法
- 调用`submitBtn()`方法
- 为提交按钮绑定click事件

于是每次调用`.update(conf)`方法时，按钮都会被绑定一次事件，导致重复提交和重复评论。

https://github.com/ArtalkJS/Artalk/blob/2dc3bc8934130fd316bff61f85dfe0188f68a178/ui/packages/artalk/src/editor/funcs.ts#L75

可能的修复方法（不太确认整体架构，放在哪里比较好）：

- 判断内部初始化状态，已初始化的不重复绑定事件
- 保留事件绑定的处理函数，在绑定前先解绑前一次绑定的事件
- 清除旧的UI再重新渲染和绑定

**Comment by TooBug** [comment]
@qwqcode 大佬，有建议吗？要不你说个思路，我有空来贡献个PR？

**Comment by qwqcode** [comment]
非常感谢你提供的思路和热心回复！😁

`conf-loaded` 事件会有多次被触发的情况：1、当调用 init 函数时；2、当调用 update 函数时。

已查明二次触发 `conf-loaded` 事件会出现问题，事件触发时有 set 和 add 操作。set 不会有问题，但 add 的操作应该只允许一次（例如 el.addEventListener）。

目前的解决方案是：在 editor 组件增加了 unmount 方法，当二次触发 `conf-loaded` 事件时，先执行 unmount 删掉已经绑定的事件，然后再重新绑定，避免多次 add 导致重复提交和重复评论。

目前前端的代码仍需优化，有很多地方违反了如 SRP、OCP 的设计原则，代码有点多，有挺多历史包袱，重构比较头疼，单元测试也还没写 🥲

我将继续尝试改进，整理代码架构，期待你的指导，欢迎 PR 😉

**Comment by TooBug** [comment]
哇，你的解决方案非常完整！感谢快速响应解决，期待新版本发布。👍
