### ISSUE TITLE
文档中兼容性处高效缓存 Memory cache

### ISSUE THREAD

**Issue by penndu** [ArtalkJS/Artalk#60]
和 Redis 并级应该是 Memcached，是不是单词写错了？

**Comment by qwqcode** [comment]
目前 Artalk 处于开发阶段，暂不对性能做过多要求，故还没未做过多数据缓存处理，暂时不支持 Redis 和 Memcached。

目前只是使用集成到 go 程序里面的库（[allegro/bigcache](https://github.com/allegro/bigcache)），以程序内置 in-memory 的方式进行小部分的缓存。

将来会做更多的性能优化，以满足更高的性能要求。
