### ISSUE TITLE
在 Vitepress 开发环境中所有功能完全正常,但是编译静态文件会出错

### ISSUE THREAD

**Issue by KevinYouu** [ArtalkJS/Artalk#608]
**会提示错误 ReferenceError: window is not defined**

<img width="938" alt="image" src="https://github.com/ArtalkJS/Artalk/assets/46970005/8720b3cf-d0be-4c34-803c-8b74000da992">

**Comment by qwqcode** [comment]
Vitepress 的编译是 Node 的服务器端渲染没有 window 对象。

但你可以把 Artalk 封住成一个组件，并把这个组件用 `<ClientOnly>` 标签包裹，参考：https://vitepress.dev/guide/ssr-compat#ssr-compatibility

相关问题：

- https://github.com/vuejs/vitepress/issues/596
- https://github.com/vuejs/vitepress/issues/1689

---

备选方案，你可以参考我的解决方案，直接在页面加载后创建 `<script>` 标签引入 Artalk：https://github.com/ArtalkJS/Artalk/blob/master/docs/.vitepress/theme/Artalk.vue

目前 Artalk 暂未实现官方的 Vue、React 组件，如果你有更好的解决方案，欢迎分享~

**Comment by qwqcode** [comment]
嗨！我更新了说明文档，你可以试试集成到 Vitepress 中

https://artalk.js.org/guide/frontend/import-blog.html#vitepress

---

由于文档将进行 SSR 渲染，因此需通过 import() 函数异步引入 Artalk，否则会导致构建失败。

```ts
import('artalk').then(({ default: Artalk }) => {
  artalk = Artalk.init({
    //...
  })
})
```

参考文件：[.vitepress/theme/Artalk.vue](https://github.com/ArtalkJS/Artalk/blob/master/docs/.vitepress/theme/Artalk.vue)
