### ISSUE TITLE
回复楼层评论，评论框跟随到相对应的回复楼层

### ISSUE THREAD

**Issue by xiamuguizhi** [ArtalkJS/Artalk#61]
![](https://camo.githubusercontent.com/1183cd0a0f39b45a41351de482d25f4e0590422b471dc640185200b1ffc72dde/68747470733a2f2f766b6365797567752e63646e2e6273706170702e636f6d2f564b4345595547552d32666139333063382d666565632d343934322d616338382d6261333738313337376262302f34393431383032382d663663312d346336332d626634382d6132643164643761323564352e706e67)

**Comment by qwqcode** [comment]
https://github.com/ArtalkJS/Artalk/commit/bb9260758724c329550faaf763383546583ec9e4

该功能已在 v2.1.3 更新中加入，并为默认打开状态：Artalk 配置 `editorTravel: true`

![](https://user-images.githubusercontent.com/22412567/142655016-1c680604-4e19-4f96-b6d0-d305d977c831.jpg)

![](https://user-images.githubusercontent.com/22412567/142655024-4fdb1f9e-4d09-4bb8-b148-c0bef032b80c.jpg)

**Comment by qwqcode** [comment]
侧边栏也同时支持，跨站点+跨页面 快速回复

**Comment by xiamuguizhi** [comment]
@qwqcode 强的，太肝了 凌晨我都还看到你更新！！ 

这就换上去 哈哈。
