### ISSUE TITLE
前端配置中-无评论显示文字-可以输入html 标签

### ISSUE THREAD

**Issue by dianso** [ArtalkJS/Artalk#610]
前端配置中-无评论显示文字-可以输入html 标签

比如填写：

<img src="https://v2.jinrishici.com/one.svg?font-size=20&color=GoldenRod" style="max-width:100%; display: block; margin: 0 auto;">

```
<img src="https://v2.jinrishici.com/one.svg?font-size=20&color=GoldenRod" style="max-width:100%; display: block; margin: 0 auto;">
```

来实现随机显示诗词，这样有风险么？

**Comment by qwqcode** [comment]
确实存在安全隐患，但是风险来源于网站管理员，而非普通用户的设置。

为提高整体安全性，新版已做了 HTML 非安全标签属性的过滤处理。

感谢反馈！
