### ISSUE TITLE
无法使用环境变量模式在 Koyeb 部署

### ISSUE THREAD

**Issue by ccbikai** [ArtalkJS/Artalk#612]
Koyeb 支持 Docker 部署，但是不支持配置存储卷，启动的时候报错。

期望 Docker 运行时不强依赖 /data 目录

`Failed to create target file: open /data/artalk.yml: no such file or directory`

<img width="1149" alt="image" src="https://github.com/ArtalkJS/Artalk/assets/2959393/7d2470e3-1a6c-46e6-a35c-d558887c59c7">

**Comment by LeenHawk** [comment]
有一个办法，你改一下部署命令，把外置项目的config.yml复制到容器里就好了

**Comment by LeenHawk** [comment]
可以看我在render.com上的[部署过程](https://zhuanlan.zhihu.com/p/667881783)

**Comment by ccbikai** [comment]
> 有一个办法，你改一下部署命令，把外置项目的config.yml复制到容器里就好了

这个可以，但是不想这么折腾了。  我部署 Pleroma 的时候使用的这种方式

**Comment by qwqcode** [comment]
你好，新版已修复这个问题，v2.8.4 将包含该更新。可以关注 [Releases](https://github.com/ArtalkJS/Artalk/releases) 页面，感谢反馈！❤️

<img width="1174" alt="image" src="https://github.com/ArtalkJS/Artalk/assets/22412567/37459eaa-8453-45c9-a82f-9f4ada96b98b">

---

此外，配置可以通过环境变量设置替代文件：

https://artalk.js.org/guide/backend/config.html#%E9%80%9A%E8%BF%87%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F%E9%85%8D%E7%BD%AE

容器启动后可通过执行 `artalk admin` 设置管理员账号：

<img width="670" alt="image" src="https://github.com/ArtalkJS/Artalk/assets/22412567/8d5bc45f-9d00-44aa-a51c-71006d321b9b">
