### ISSUE TITLE
未来有提供计数功能的打算吗？

### ISSUE THREAD

**Issue by inkss** [ArtalkJS/Artalk#62]
评论页面的  UV，PV 等。

**Comment by qwqcode** [comment]
是的，在计划中

**Comment by inkss** [comment]
到时候，选择器可以做成自拟吗？加一个配置项。

**Comment by qwqcode** [comment]
没问题

**Comment by xiamuguizhi** [comment]
@qwqcode 添加好了 效果很棒啊！ 来体验一下？ https://xn--qpru0x.cn/post/271  我就刷新了这个 哈哈！！ 如果没显示强制刷新看看！

**Comment by inkss** [comment]
> @qwqcode 添加好了 效果很棒啊！ 来体验一下？ https://xn--qpru0x.cn/post/271 我就刷新了这个 哈哈！！ 如果没显示强制刷新看看！

等这个整完后，我就迁移过去，嘿嘿那个嘿嘿

**Comment by qwqcode** [comment]
https://github.com/ArtalkJS/Artalk/commit/fa5703d6e0e70f064cf8d8a3e526f957cd826c03

**Comment by xiamuguizhi** [comment]
@qwqcode  是不是js 也要更新啊 <span id="ArtalkPV"></span>

**Comment by xiamuguizhi** [comment]
@inkss 来试试看  哈哈 很好用！！

**Comment by inkss** [comment]
我试试部署到自己服务器上
