### ISSUE TITLE
评论置顶功能

### ISSUE THREAD

**Issue by qwqcode** [ArtalkJS/Artalk#63]

**Comment by qwqcode** [comment]
@xiamuguizhi

**Comment by qwqcode** [comment]
https://github.com/ArtalkJS/Artalk/commit/2fc24ef7535773c7d9df47dfbcd3ff610790b158
https://github.com/ArtalkJS/ArtalkGo/commit/3538d6a7c89f8921d2fbaea561dfebd0949b418b

![image](https://user-images.githubusercontent.com/22412567/163010743-3e67d1ce-b444-4bfa-a7ad-3d7a6b13e4ac.png)

**Comment by xiamuguizhi** [comment]
收到了，今天体验了一下很强！！

但是因为用的美化版前端js ，只能等大佬更新最新版本 我在用上了。哈哈。

**Comment by qwqcode** [comment]
@xiamuguizhi 哈哈，以后可以开个仓库，收集魔改版 CSS 样式预设

**Comment by qwqcode** [comment]
确实挺好看的，我可以帮忙更新下

**Comment by xiamuguizhi** [comment]
@qwqcode  因为你更新太频繁了，@[Anghunk](https://imhan.cn/) 决定等你稳定了，在进行魔改 哈哈。

我现在后端是最新版本，前端还是用之前的2.6版本好像  很多新功能体验不到了 ，如果你能更新一下界面 我可以期待了 哈哈。
