### ISSUE TITLE
启动失败，提示：FATAL tls: provide a valid cert or key path

### ISSUE THREAD

**Issue by yydschen** [ArtalkJS/Artalk#639]
Artalk Error
Error: 请求超时或意外终止，无法获取评论列表数据
点击重新获取
 我的授权域名也填写是的啊？

**Comment by yydschen** [comment]
time="2023-11-11T19:18:03+08:00" level=warning msg="config `locale` is not set, now it is: \"zh-CN\""
time="2023-11-11T19:18:03+08:00" level=warning msg="未找到 IP 数据库文件：\"./data/ip2region.xdb\"，IP 归属地功能已禁用，参考链接：https://artalk.js.org/guide/frontend/ip-region.html"

 ________  ________  _________  ________  ___       ___  __
|\   __  \|\   __  \|\___   ___\\   __  \|\  \     |\  \|\  \
\ \  \|\  \ \  \|\  \|___ \  \_\ \  \|\  \ \  \    \ \  \/  /|_
 \ \   __  \ \   _  _\   \ \  \ \ \   __  \ \  \    \ \   ___  \
  \ \  \ \  \ \  \\  \|   \ \  \ \ \  \ \  \ \  \____\ \  \\ \  \
   \ \__\ \__\ \__\\ _\    \ \__\ \ \__\ \__\ \_______\ \__\\ \__\
    \|__|\|__|\|__|\|__|    \|__|  \|__|\|__|\|_______|\|__| \|__|

Artalk (v2.6.4/8867eb2)

 -> A Selfhosted Comment System.
 -> https://artalk.js.org

-------------------------------

FATAL tls: provide a valid cert or key path

**Comment by yydschen** [comment]
已经解决，谢谢！可以删除该条问题。

**Comment by qwqcode** [comment]
不用谢！😁
