### ISSUE TITLE
[Bug] The position of the comment box appears incorrectly when replying someone

### ISSUE THREAD

**Issue by qwqcode** [ArtalkJS/Artalk#643]
![2023-11-16_19-39-05](https://github.com/ArtalkJS/Artalk/assets/119997727/b4f0ec9b-5813-43d8-bb54-04f9d1ec05a0)

The position of the comment box appears incorrectly?

When I reply to Comment A, the comment box value is pushed down, not below comment A

_Originally posted by @bibicadotnet in https://github.com/ArtalkJS/Artalk/discussions/640#discussioncomment-7587839_

**Comment by LeenHawk** [comment]
其实也可以不修这个，就是贴吧那样；修的话，像reddit，超过三层要跳转到另一个界面，要不然容易过于右边了（或者设计成超过五次回复变成不缩进直接向下）

**Comment by LeenHawk** [comment]
qwq，外国人可能更适应reddit那样的，知乎和贴吧都是不缩进的，不过微博似乎也缩进？

**Comment by qwqcode** [comment]
> qwq，外国人可能更适应reddit那样的，知乎和贴吧都是不缩进的，不过微博似乎也缩进？

缩进后评论的顺序以后可以增加一个设置项自由配置。

本 issue 解决的问题是点回复按钮后，评论框出现位置，应该出现在评论的内容之后，而不是评论的最后一个子评论之后，我觉得确实应该修改一下，你觉得呢 🤔️

![image](https://github.com/ArtalkJS/Artalk/assets/22412567/eb0507df-b9ea-4980-b20e-4145ed782e91)

因为回复者需要看着需要回复的内容进行回复，而现在评论框并没有跟在回复内容之后。

**Comment by bibicadotnet** [comment]
是的，正如 qwqcode 所解释的那样

我在 comment42、commentario、Commento、Commento++ 中没有收到此错误

**Comment by bibicadotnet** [comment]
希望这个错误能够尽快修复，目前我很难回复评论，具体情况可以关注这里 [here](https://bibica.net/cai-dat-artalk-comment-systems-cho-bibica-net/)

**Comment by LeenHawk** [comment]
> > qwq，外国人可能更适应reddit那样的，知乎和贴吧都是不缩进的，不过微博似乎也缩进？
> 
> 缩进后评论的顺序以后可以增加一个设置项自由配置。
> 
> 本 issue 解决的问题是点回复按钮后，评论框出现位置，应该出现在评论的内容之后，而不是评论的最后一个子评论之后，我觉得确实应该修改一下，你觉得呢 🤔️
> 
> ![image](https://github.com/ArtalkJS/Artalk/assets/22412567/eb0507df-b9ea-4980-b20e-4145ed782e91)
> 
> 因为回复者需要看着需要回复的内容进行回复，而现在评论框并没有跟在回复内容之后。

有道理，我望图生义了

**Comment by qwqcode** [comment]
OK 感谢对 Artalk 关注和讨论，非常欢迎提出更多宝贵的建议哦 😉

---

Thank you for your interest in Artalk and for discussing. Feel free to share more valuable insights!

**Comment by bibicadotnet** [comment]
@qwqcode: I have some issues discussed [here](https://github.com/ArtalkJS/Artalk/discussions), could you take a look?

**Comment by bibicadotnet** [comment]
Are there any new developments on this issue?

**Comment by bibicadotnet** [comment]
How can I update commit 4e9afd9 for docker-compose?
