### ISSUE TITLE
可以考虑增加自定义头像或者缓存头像功能吗？

### ISSUE THREAD

**Issue by dianso** [ArtalkJS/Artalk#653]
可以考虑增加自定义头像或者缓存头像功能吗？

**Comment by qwqcode** [comment]
你好，自定义头像可以在前端配置 `avatarURLBuilder`

参考文档：https://artalk.js.org/guide/frontend/config.html#avatarurlbuilder

**Comment by dianso** [comment]
看了看，不懂如何用。。。

**Comment by dianso** [comment]
> 你好，自定义头像可以在前端配置 `avatarURLBuilder`
> 
> 参考文档：https://artalk.js.org/guide/frontend/config.html#avatarurlbuilder

感觉有点复杂，我看到前端配置可以指定API 地址和API 参数

由于不懂go，所以和chatgpt3.5对话了50分钟，按照要求做出了类似的功能。

go写了个小程序，开个http端口，访问 a.com:8080 将请求代理到https://cravatar.cn/avatar/

第一次请求将webp格式头像保存到本地，之后的请求就用本地图片

想自定义头像了，就将邮箱hash设定个白名单，不请求代理。

**Comment by bibicadotnet** [comment]
根据你的问题，我认为最正确的解决方案是使用 `Reverse Proxy + FastCgi Cache`

但操作较多且耗时，如果单纯的目的是为了更快地加载头像，可以使用Jetpack Photon等简单的CDN形式。

`https://gravatar.com/avatar/` -> `https://i0.wp.com/gravatar.com/avatar/`

`https://gravatar.com/avatar/` -> `https://resizer.pictures/auto/gravatar.com/avatar/`

**Comment by dianso** [comment]
> 根据你的问题，我认为最正确的解决方案是使用 `Reverse Proxy + FastCgi Cache`
> 
> 但操作较多且耗时，如果单纯的目的是为了更快地加载头像，可以使用Jetpack Photon等简单的CDN形式。
> 
> `https://gravatar.com/avatar/` -> `https://i0.wp.com/gravatar.com/avatar/`
> 
> `https://gravatar.com/avatar/` -> `https://resizer.pictures/auto/gravatar.com/avatar/`

主要是想增加自定义头像功能，但也需要https://cravatar.cn的头像服务，优先级是本地>cravatar.cn

**Comment by bibicadotnet** [comment]
将头像从 gravatar、cravatar... 缓存到本地的想法非常有用，它有助于更​​快地加载图像，这应该是默认功能。

作为一个简单的修复，我还使用“反向代理 + FastCgi 缓存”将用户上传的图像和头像带到本地（通过 Cloudinary 进行图像压缩）

**Comment by dianso** [comment]
那样太麻烦了吧，不会弄。

找gpt写了个go小程序，几十行代码，编译后单文件，也实现了：

请求头像时候，先查看本地是否有，如果有，直接显示本地的。

如果没有，从cravatar.cn下载，现在2400个头像，已经全部缓存到本地了。

为了防止有人在cravatar.cn更新了头像，本地还是旧的，每个月清理一次缓存，重新来一次。

![Uploading Snipaste_2023-12-17_15-23-51.png…]()

**Comment by bibicadotnet** [comment]
嗯，一般都是用头像，我觉得用CDN服务就够了 `https://i0.wp.com/gravatar.com/avatar/`

我使用“Reverse Proxy + FastCgi Cache”的原因是因为我也将它用于用户上传的图像，部分原因是我还通过 Nginx 运行该网站

![LYSGE5oSKI](https://github.com/ArtalkJS/Artalk/assets/119997727/ac985d80-0e0f-4dff-af3e-4a17e0a8599c)

通过这种形式，图像也将被压缩并转换为.webp格式......
