### ISSUE TITLE
【求助】artalk出现乱码

### ISSUE THREAD

**Issue by misaka-fans** [ArtalkJS/Artalk#657]
我的artalk编码方式貌似出现了一点小问题，但我近期并没有修改过配置。乱码是这样的
![BB2936BF-DF5E-4332-A974-265AB14080F1](https://github.com/ArtalkJS/Artalk/assets/104608787/f1e6c2ee-ee10-4657-bea5-bfb9ee0562e7)

我有配置好地区
![A5B42EEF-106F-4038-94D6-3D77E5AACC5F](https://github.com/ArtalkJS/Artalk/assets/104608787/62dd8dd1-52d4-4110-a927-309a048ca961)
求助应该如何解决
artalk v2.6.4

**Comment by qwqcode** [comment]
你好，可以提供一下出现问题的网页地址吗？

**Comment by misaka-fans** [comment]
> 你好，可以提供一下出现问题的网页地址吗？

https://mhs2603.space/pages/about/

输114514进

后端在comment.mhs2603.space

**Comment by qwqcode** [comment]
已查明原因是 [BootCDN](https://www.bootcdn.cn/) 的静态资源存在乱码问题，已写信反馈这个问题。

可将

`<script src="https://cdn.bootcdn.net/ajax/libs/artalk/2.6.4/Artalk.js"></script>`

替换为

`<script src="你的后端地址/dist/Artalk.js"></script>`

或者选择国内其他的前端静态资源公共 CDN。

例如：`https://lib.baomitu.com/artalk/2.6.4/Artalk.js`

**Comment by misaka-fans** [comment]
感谢帮助！问题已解决
