### ISSUE TITLE
Adjust "Image link base path"

### ISSUE THREAD

**Issue by bibicadotnet** [ArtalkJS/Artalk#659]
For example, the Artalk link I am using is `https://comment.bibica.net`

The default image link when uploaded will be `https://comment.bibica.net//static/images/`

I want to use through CDN `https://img.bibica.net/static/`

Follow instructions [here](https://artalk.js.org/guide/backend/img-upload.html#path)

Image link base path, I replaced it with `https://img.bibica.net/static/`

![cjsiDq1qOy](https://github.com/ArtalkJS/Artalk/assets/119997727/21d25a36-7868-4e00-89f1-86d7155bae90)

The link created after upload will appear correctly as `https:/img.bibica.net/static/20231215-213709.862.png`

![kChWO3SkKb](https://github.com/ArtalkJS/Artalk/assets/119997727/2ed3e312-79ea-4daa-ac79-f73aa16897a0)

The problem is that at this time, the image has the domain load Artalk added to the front, becoming `https://bibica.net/img.bibica.net/static/20231215-213709.862.png`

Is this problem due to my misconfiguration, or is this a bug from Artalk?

**Comment by qwqcode** [comment]
Hello, your configuration is correct. Indeed, this is a bug. In previous versions, this configuration item did not support configuring the full URL; it only supported relative paths.

Thank you for your feedback. This issue has been fixed in the upcoming version. Please stay tuned for the release!

**Comment by bibicadotnet** [comment]
Yes, I see there have been quite a few new updates, when will v2.6.5 be released?

**Comment by qwqcode** [comment]
Yes, there have been many updates recently. I'll skip version 2.6.5 and move directly to 2.7.0. 🤣

**Comment by bibicadotnet** [comment]
Yes, I'm really looking forward to the new version, because it fixes a lot of the bugs I encountered :(

**Comment by bibicadotnet** [comment]
Fixed in 2.7.1
