### ISSUE TITLE
[HELP]  update Frontend to 2.7

### ISSUE THREAD

**Issue by bibicadotnet** [ArtalkJS/Artalk#668]
![1AcR08H3fn](https://github.com/ArtalkJS/Artalk/assets/119997727/ec0ff55d-79a4-433d-960e-7f8235da28e4)
```Artalk Warn
请更新 Artalk Frontend以获得完整体验 ([帮助文档](https://artalk.js.org/))
当前版本：Frontend 2.6.4 / Backend 2.7.0
忽略
```
I updated docker to version 2.7 but got this error

How to update Frontend to 2.7?

**Comment by qwqcode** [comment]
Hello, you might need to refresh the CDN cache or the browser's JavaScript file cache.

**Comment by bibicadotnet** [comment]
![SZpl8RnjA1](https://github.com/ArtalkJS/Artalk/assets/119997727/3f809b4f-ff5b-4cd4-958f-e8b76c52e03d)
After clearing all caches, the comment section displays a blank page

**Comment by qwqcode** [comment]
This is indeed a significant issue. You could temporarily modify `Artalk.init` to `Artalk.default.init`. I'm working on fixing this problem. 🤯

**Comment by bibicadotnet** [comment]
Yes, I think it can be temporarily fixed by turning off the "Version check" option inside the admin :(

**Comment by bibicadotnet** [comment]
有没有修复此错误的 docker 版本？:(

**Comment by qwqcode** [comment]
It's currently in the process of automatically compiling via GitHub Actions. Once the compilation is complete, version 2.7.1 will be automatically released, which should fix this issue.

<img width="1128" alt="image" src="https://github.com/ArtalkJS/Artalk/assets/22412567/dc74df54-b008-431a-af2e-2ad45d17ea3a">

Thank you for your feedback. Without it, I would have overlooked this situation entirely. :)

**Comment by bibicadotnet** [comment]
What is the image link? I tried `image:artalk/artalk-go:2.7.1` but it didn't work :D

**Comment by bibicadotnet** [comment]
![dPEKtqHrhr](https://github.com/ArtalkJS/Artalk/assets/119997727/f41bef2d-c350-46a9-9fb9-ad0cad0038f6)

After updating to 2.7.1, I saw in the docker log that the file Artalk.js.map could not be found.
`ERROR 404: GET /dist/Artalk.js.map `

For now, everything is working quite normally

**Comment by rebron1900** [comment]
我也出现了这个问题，目前镜像缓存还没有更新，我暂时将前端退回了2.6.3

**Comment by shaoyaoqian** [comment]
Might be 404 error of `Artalk.js.map`,  it is useless in product environment.

**Comment by Nikarhub** [comment]
这个问题在2.9.1也没有解决啊。为什么就关闭了呢？

**Comment by bibicadotnet** [comment]
我手动处理，方法是创建新的 Artalk.js 和 Artalk.css 文件，然后直接调用此 URL，例如：
```
https://bibica.net/artalk/2.9.1/Artalk.css
https://bibica.net/artalk/2.9.1/Artalk.js
```
或者，您也可以调用此 URL：
```
https://cdnjs.cloudflare.com/ajax/libs/artalk/2.9.1/Artalk.js
https://cdnjs.cloudflare.com/ajax/libs/artalk/2.9.1/Artalk.css
```
