### ISSUE TITLE
Flatten mode true and false infected

### ISSUE THREAD

**Issue by bibicadotnet** [ArtalkJS/Artalk#671]
![ZKMsmZbfqR](https://github.com/ArtalkJS/Artalk/assets/119997727/931654e4-4a3c-4c3c-b3f9-efc06bf442c1)

v2.7.1, Flatten mode feature, 2 options `true` and `false` have duplicate features, they both work like `true`
The `auto` option works correctly

**Comment by qwqcode** [comment]
Hello, thank you for your feedback. The issue has been fixed now, and the next version will include this fix! ❤️

https://github.com/ArtalkJS/Artalk/issues/677#issuecomment-1864418574

**Comment by qwqcode** [comment]
新版 v2.7.2 已发布，包括了这个问题的修复 😀

---

The new version v2.7.2 has been released, which includes a fix for this issue.

**Comment by bibicadotnet** [comment]
Well, if possible you can review [this topic](https://github.com/ArtalkJS/Artalk/discussions/644)

I think you forgot, because the new versions don't see any updates

**Comment by bibicadotnet** [comment]
Fixed in 2.7.2

**Comment by dianso** [comment]
> 新版 v2.7.2 已发布，包括了这个问题的修复 😀
> 
> The new version v2.7.2 has been released, which includes a fix for this issue.

设置里平铺模式选择：false

前端是嵌套评论了，sidebar里面，一会变化一次，我发现有两种：

一种是：

![image](https://github.com/ArtalkJS/Artalk/assets/1454808/282b3051-a239-485a-8c2d-2ef728b50350)

还有一种是：

![image](https://github.com/ArtalkJS/Artalk/assets/1454808/44d42393-f790-41ac-9181-7c8309f191fe)


我记得之前几个版本不是这样的啊

**Comment by bibicadotnet** [comment]
- Flatten mode = false

![cYYrvYd4hQ](https://github.com/ArtalkJS/Artalk/assets/119997727/27d2f39c-ac5c-4116-97bc-36aab930b599)

- Flatten mode = true

![saxCMmRH3N](https://github.com/ArtalkJS/Artalk/assets/119997727/f0a0ab85-7ae0-4209-bf77-4f819ad497a0)

- Flatten mode = auto

1. 如果设备具有大屏幕 (> 768px)，如桌面，请使用 Flatten 模式 = false
2. 对于手机等大屏幕设备 (< 768px)，请使用 Flatten 模式 = true

**Comment by qwqcode** [comment]
> > 新版 v2.7.2 已发布，包括了这个问题的修复 😀
> 
> > 
> 
> > The new version v2.7.2 has been released, which includes a fix for this issue.
> 
> 
> 
> 设置里平铺模式选择：false
> 
> 
> 
> 前端是嵌套评论了，sidebar里面，一会变化一次，我发现有两种：
> 
> 
> 
> 一种是：
> 
> 
> 
> ![image](https://github.com/ArtalkJS/Artalk/assets/1454808/282b3051-a239-485a-8c2d-2ef728b50350)
> 
> 
> 
> 还有一种是：
> 
> 
> 
> ![image](https://github.com/ArtalkJS/Artalk/assets/1454808/44d42393-f790-41ac-9181-7c8309f191fe)
> 
> 
> 
> 
> 
> 我记得之前几个版本不是这样的啊
> 
> 
> 
> 我发的两个截图是同一个评论，每过一会就变成另一种模式

手动检查下 artalk.yml 配置文件，把 `"true"` 字符串改为 `true`

**Comment by dianso** [comment]
> > > 新版 v2.7.2 已发布，包括了这个问题的修复 😀
> > 
> > 
> > > 
> > 
> > 
> > > The new version v2.7.2 has been released, which includes a fix for this issue.
> > 
> > 
> > 设置里平铺模式选择：false
> > 前端是嵌套评论了，sidebar里面，一会变化一次，我发现有两种：
> > 一种是：
> > ![image](https://private-user-images.githubusercontent.com/1454808/291986248-282b3051-a239-485a-8c2d-2ef728b50350.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMjkyNzQsIm5iZiI6MTcwMzEyODk3NCwicGF0aCI6Ii8xNDU0ODA4LzI5MTk4NjI0OC0yODJiMzA1MS1hMjM5LTQ4NWEtOGMyZC0yZWY3MjhiNTAzNTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjFUMDMyMjU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTA4Mzg5NDQ3ZTYwOGI4YmE5NThlYTBlNjljMTc4MzVkMDU0MTMwODc1NGVjYmQxYmEzOGE4ZDNlZjEyNDEyZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YAEBNcR0-YzP5RXHIiliSrpJ9Dpk8GyJnluI2Knn4W8)
> > 还有一种是：
> > ![image](https://private-user-images.githubusercontent.com/1454808/291986551-44d42393-f790-41ac-9181-7c8309f191fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMjkyNzQsIm5iZiI6MTcwMzEyODk3NCwicGF0aCI6Ii8xNDU0ODA4LzI5MTk4NjU1MS00NGQ0MjM5My1mNzkwLTQxYWMtOTE4MS03YzgzMDlmMTkxZmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjFUMDMyMjU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjZjNGRmNmI4MGI3ZWE2NWQ4ODVhODRlOGQzMTg2OTE1NTFkNzllNWI2ODQyZDUxODZmNzgwNjQ1OWY5NWM4NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.46hRtE_VErplRg-qviQzpVxyTV7LX3KeME2FSs4z0Ro)
> > 我记得之前几个版本不是这样的啊
> > 我发的两个截图是同一个评论，每过一会就变成另一种模式
> 
> 手动检查下 artalk.yml 配置文件，把 `"true"` 字符串改为 `true`

我看了配置文件：

preview: false
  # 平铺模式 ["auto", true, false]


我想要的就是评论以嵌套形式展示，电脑手机端都是，所以设置的false，sidebar里面有时候是平铺有时候是嵌套，前端都正常。

**Comment by bibicadotnet** [comment]
如果您想要 PC 和 Phone 的嵌套注释，请使用 flatMode: false 选项

![6PnPrAiyI1](https://github.com/ArtalkJS/Artalk/assets/119997727/4ec50b0c-67de-4484-afb6-166c87296d66)

现在在移动设备上显示的问题会很糟糕

我也谈过这个话题 #640
