### ISSUE TITLE
sidebar面板默认是英语了，我语言设置是zh-cn

### ISSUE THREAD

**Issue by dianso** [ArtalkJS/Artalk#678]
sidebar面板默认是英语了，我语言设置是zh-cn

还有个问题：

回复评论后，不能聚焦到原评论了，不像以前那样。

**Comment by bibicadotnet** [comment]
![Uf2OA8Tot3](https://github.com/ArtalkJS/Artalk/assets/119997727/8b8112ad-b253-481a-99e9-1b91abb36db1)

/sidebar/#/settings

通过更改为英语然后切换回 zh-CH 进行简单处理

记得按应用

**Comment by dianso** [comment]
> ![Uf2OA8Tot3](https://private-user-images.githubusercontent.com/119997727/291165876-8b8112ad-b253-481a-99e9-1b91abb36db1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4Nzk4NjAsIm5iZiI6MTcwMjg3OTU2MCwicGF0aCI6Ii8xMTk5OTc3MjcvMjkxMTY1ODc2LThiODExMmFkLWIyNTMtNDgxYS05OWU5LTFiOTFhYmIzNmRiMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOFQwNjA2MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDA5ZGU5OWM5MTg4MDhiYWEwYmEyYzdlNzQ5NmIxODcxN2ViMTM0YjU2YjU0ZWU2MmQzNzg4MTRmZDZmNjgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._p5UfQuIB7xTULizCVYn1IVsrvYohUeZuxzie6Dw1dU)
> 
> /sidebar/#/settings
> 
> 通过更改为英语然后切换回 zh-CH 进行简单处理
> 
> 记得按应用

感谢，新版小问题不少呢。



刚发现，回复评论后，不能聚焦到原评论了，不像以前那样。

**Comment by bibicadotnet** [comment]
![boYcPP8sD7](https://github.com/ArtalkJS/Artalk/assets/119997727/de25ae3a-1920-4f0a-95b0-9b1d3ebc037f)

一切正常

**Comment by dianso** [comment]
> ![boYcPP8sD7](https://private-user-images.githubusercontent.com/119997727/291166993-de25ae3a-1920-4f0a-95b0-9b1d3ebc037f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4ODAxNzAsIm5iZiI6MTcwMjg3OTg3MCwicGF0aCI6Ii8xMTk5OTc3MjcvMjkxMTY2OTkzLWRlMjVhZTNhLTE5MjAtNGYwYS05NWIwLTliMWQzZWJjMDM3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOFQwNjExMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDgyM2M4NGE2OWQwOWNkZGNiZmFjOTNmNGJjZDA3ZDc3MzBmOTE1MDI1MmU2M2IzMDFlMjc2YjQxM2YyODQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bXFkz-IMhkiVnnjlZyILvcD47b8Lnia2M5LxIsMlzEQ)
> 
> 一切正常

你的确实正常，我反复试了几次，显示是英文。

**Comment by bibicadotnet** [comment]
您的浏览器也可能正在存储旧的缓存，请尝试 Ctrl + F5 清除缓存，看看会发生什么

**Comment by dianso** [comment]
> 您的浏览器也可能正在存储旧的缓存，请尝试 Ctrl + F5 清除缓存，看看会发生什么

试过了，换了台电脑访问还是如此。

![image](https://github.com/ArtalkJS/Artalk/assets/1454808/e3a95df0-56ff-4ac9-9752-fc0b43793617)

**Comment by bibicadotnet** [comment]
我只是在考虑最后一种情况，即您在 Artalk 上打开缓存功能

![OfmRtFaTj8](https://github.com/ArtalkJS/Artalk/assets/119997727/21dc8393-53a6-47ce-99fc-47c64c22d2eb)

关闭缓存功能并重启docker

**Comment by dianso** [comment]
> 我只是在考虑最后一种情况，即您在 Artalk 上打开缓存功能
> 
> ![OfmRtFaTj8](https://private-user-images.githubusercontent.com/119997727/291169242-21dc8393-53a6-47ce-99fc-47c64c22d2eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4ODA5NDEsIm5iZiI6MTcwMjg4MDY0MSwicGF0aCI6Ii8xMTk5OTc3MjcvMjkxMTY5MjQyLTIxZGM4MzkzLTUzYTYtNDdjZS05OWZjLTQ3YzY0YzIyZDJlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOFQwNjI0MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZWMxMDk2NDMyYjFkODNmNWM3OTc1YzM2NTkzMmQzNDhhMTQ3NWQzYWM5MjY3YjM5OGIzN2NjNDkxOTI0NDYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D5lvd-wbDCfJKGmyug1jcycZX4lSgSKip-frcwqbSFQ)
> 
> 关闭缓存功能并重启docker

也试了，不管用。

倒是也不影响使用，还有评论翻页的上一页 下一页 一直是英文显示，你那也是吗？

**Comment by bibicadotnet** [comment]
![Z5LPIIxIef](https://github.com/ArtalkJS/Artalk/assets/119997727/42259380-27c1-4bb0-a6b8-328d4959eca7)

一切正常:D

**Comment by rebron1900** [comment]
哈啰，你也出问题拉。

可以在无痕窗口里试试看是不是缓存的问题，ctrl+f5有时候不太管用。

**Comment by dianso** [comment]
> 哈啰，你也出问题拉。
> 
> 可以在无痕窗口里试试看是不是缓存的问题，ctrl+f5有时候不太管用。

试了不行，清除cookie，换浏览器都试过

**Comment by rebron1900** [comment]
> > 哈啰，你也出问题拉。
> > 可以在无痕窗口里试试看是不是缓存的问题，ctrl+f5有时候不太管用。
> 
> 试了不行，清除cookie，换浏览器都试过

试试大写的 `zh-CN` 呢？

**Comment by qwqcode** [comment]
@dianso 我刚刚测了，如果配置文件里的 locale 是小写的 zh-cn 侧边栏确实会变成英文，可以检查一下配置文件改为 `"zh-CN"`

<img width="358" alt="image" src="https://github.com/ArtalkJS/Artalk/assets/22412567/b44a82f6-2cd0-4f23-8ea5-28e9fd7fae75">

**Comment by qwqcode** [comment]
我改进一下，自动转换 `-` 后面的字符为大写

**Comment by dianso** [comment]
> 我改进一下，自动转换 `-` 后面的字符为大写

感谢~

**Comment by qwqcode** [comment]
新版 v2.7.2 已发布，包括了这个问题的修复 😀

---

The new version v2.7.2 has been released, which includes a fix for this issue.
