### ISSUE TITLE
如何从 WordPress 导入数据

### ISSUE THREAD

**Issue by Ice-Hazymoon** [ArtalkJS/Artalk#68]
如题，文档中 “通过安装 WordPress 插件，导出 Artrans 格式的数据文件。”
应该用什么插件导出

**Comment by qwqcode** [comment]
【挖的一个坑，暂时还没填】敬请期待，说不定哪天就填了

**Comment by xiamuguizhi** [comment]
@qwqcode  绝的  哈哈哈  ！！

**Comment by qwqcode** [comment]
不过 typecho 的坑填了，而且还填得挺满的

**Comment by xiamuguizhi** [comment]
@qwqcode 插件写好了？可以啊

**Comment by Ice-Hazymoon** [comment]
催更 wordpress 插件

**Comment by qwqcode** [comment]
现已支持从 WordPress 导入评论

https://artalk.js.org/guide/transfer.html
