### ISSUE TITLE
翻页bug，点下一页不断的跳转

### ISSUE THREAD

**Issue by dianso** [ArtalkJS/Artalk#693]
如果一个页面，评论有3页以上，越多越容易复现。

比如123.com/1 这个页面打开后，可以正常点下一页，到第二页也能正常点上一页和下一页。

如果是从sidebar点开链接，一般url是这种的：123.com/1#atk-comment-10486

此刻，点击下一页，会不断跳转，我看了下，一小会跳转了几十页了。

----------

评论的 上一页 下一页，我看是直接写到代码中的，就是prev和next，似乎不在语言包中，无论什么语言都是这个。

**Comment by dianso** [comment]
一个页面有3000条评论，就评论基本无法找到了，跳转一会就卡住了。

之前的版本正常

**Comment by dianso** [comment]
[2023-12-20.13:44:38.299946]  INFO 服务重启完毕
[2023-12-20.13:48:21.294219]  INFO 服务重启完毕
[2023-12-20.13:48:34.209142]  INFO 服务重启完毕
[2023-12-20.13:48:47.516859]  INFO 服务重启完毕


一旦翻页就会卡住崩溃重启。

**Comment by qwqcode** [comment]
旧的解决方案：根据链接的 hashtag `#atk-comment-xxxx`，一直找评论，如果当前页没有找到评论，自动点击翻页，直到找到为止。如果评论已删除，或者评论在太靠后的位置，或者网站的评论数量太多，浏览器可能会卡住。

新的解决方案：后端计算评论所在的页码，直接跳到某一页，而不是一页页的翻。

在新的解决方案完成之前，将暂时删除这个功能以解决问题。

---

关于后端程序，测试暂时没有发现后端问题。`[2023-12-20.13:44:38.299946] INFO 服务重启完毕` 这个日志仅会出现在你手动在控制中心操作，修改配置的时候重启，并不是程序崩溃自动重启。

**Comment by dianso** [comment]
> 旧的解决方案：根据链接的 hashtag `#atk-comment-xxxx`，一直找评论，如果当前页没有找到评论，自动点击翻页，直到找到为止。如果评论已删除，或者评论在太靠后的位置，或者网站的评论数量太多，浏览器可能会卡住。
> 
> 新的解决方案：后端计算评论所在的页码，直接跳到某一页，而不是一页页的翻。
> 
> 在新的解决方案完成之前，将暂时删除这个功能以解决问题。
> 
> 关于后端程序，测试暂时没有发现后端问题。`[2023-12-20.13:44:38.299946] INFO 服务重启完毕` 这个日志仅会出现在你手动在控制中心操作，修改配置的时候重启，并不是程序崩溃自动重启。

感谢回复，如果后端计算完，直接跳转的话比较合理。

目前在前段不断翻页跳转，我发现每次跳转，当前页面浏览量+1，跳转到一个较早的评论通常会增加几十的浏览量，实际上为1比较合理。

**Comment by dianso** [comment]
> 旧的解决方案：根据链接的 hashtag `#atk-comment-xxxx`，一直找评论，如果当前页没有找到评论，自动点击翻页，直到找到为止。如果评论已删除，或者评论在太靠后的位置，或者网站的评论数量太多，浏览器可能会卡住。
> 
> 新的解决方案：后端计算评论所在的页码，直接跳到某一页，而不是一页页的翻。
> 
> 在新的解决方案完成之前，将暂时删除这个功能以解决问题。
> 
> 关于后端程序，测试暂时没有发现后端问题。`[2023-12-20.13:44:38.299946] INFO 服务重启完毕` 这个日志仅会出现在你手动在控制中心操作，修改配置的时候重启，并不是程序崩溃自动重启。

请问2.7.3解决了这个问题了吗

**Comment by qwqcode** [comment]
2.8.1 已优化评论跳转功能

**Comment by dianso** [comment]
> 2.8.1 已优化评论跳转功能

感谢，辛苦了~

现在跳转评论确实很快，有个小问题

我在界面配置里面平铺模式设置的是false

从sidebar跳转到页面后，默认不是嵌套评论展示，而是平铺。

![image](https://github.com/ArtalkJS/Artalk/assets/1454808/0bb200c5-6dad-4676-bcf6-f997434c93bb)
