### ISSUE TITLE
2.7.2 前端修改设置后无法保存，提示：Setting save failed: [object Object]

### ISSUE THREAD

**Issue by dianso** [ArtalkJS/Artalk#708]
2.7.2 前端修改设置后无法保存，提示：Setting save failed: [object Object]

**Comment by qwqcode** [comment]
看看控制台报什么错

**Comment by dianso** [comment]
是这样的，升级新版本后，sidebar页面的导航栏又变成英文了，我打开前段，选择其他语言保存，就提示这个。

控制台，是看这个吗？

![image](https://github.com/ArtalkJS/Artalk/assets/1454808/03243be3-d089-4abb-b9f1-5bb59f290baf)

**Comment by qwqcode** [comment]
![image](https://github.com/ArtalkJS/Artalk/assets/22412567/e088f22e-b0af-49ac-ab39-dce08fba8682)

看看这里有没有红色的字

**Comment by qwqcode** [comment]
你可以手动检查一下配置文件 artalk.yml，你有做过修改吗 🤔️

**Comment by dianso** [comment]
配置文件没修改，我用# docker compose pull && docker compose up -d升级artalk2.7.2后，sidebar那就变成英文的了，我打算切换语言，再换回来试试，就成这样。

![image](https://github.com/ArtalkJS/Artalk/assets/1454808/e7e5def4-a8ec-40f7-815f-5f4f957c9e5c)

**Comment by qwqcode** [comment]
😅 这又是个新bug，哎，升级我先撤回一下

**Comment by dianso** [comment]
![image](https://github.com/ArtalkJS/Artalk/assets/1454808/c57677ab-55ea-437b-ac02-933d40e37f3f)
![image](https://github.com/ArtalkJS/Artalk/assets/1454808/228ed468-8f26-4be0-9a7b-8c5defe1b2cb)

 配置文件里面是zh-CN，但是sidebar里面是英文

**Comment by qwqcode** [comment]
重启 docker 了吗

**Comment by dianso** [comment]
> 重启 docker 了吗

试了不管用，我退回旧版了

**Comment by bibicadotnet** [comment]
升级到 2.7.2 后出现一些错误，我什至无法返回到 2.7.1 版本

![NdAr533JJc](https://github.com/ArtalkJS/Artalk/assets/119997727/ec214a2c-ae1b-4202-b34e-685b13986959)

**Comment by dianso** [comment]
> 升级到 2.7.2 后出现一些错误，我什至无法返回到 2.7.1 版本
> 
> ![NdAr533JJc](https://private-user-images.githubusercontent.com/119997727/291964612-ec214a2c-ae1b-4202-b34e-685b13986959.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwOTI0MTMsIm5iZiI6MTcwMzA5MjExMywicGF0aCI6Ii8xMTk5OTc3MjcvMjkxOTY0NjEyLWVjMjE0YTJjLWFlMWItNDIwMi1iMzRlLTY4NWIxMzk4Njk1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMFQxNzA4MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNWQ0Njc2ZDcyYjViMmJlMWViODMxNTIzZDBkNmQxOTNlYWIxNTI5NmQ2ODNiMGQ4YzdhNmNiZGZiMjRmZGJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aS1Z5-9bzulQgQ2PJdJEhcE5H3fYcoUt2V7fJAxqswM)

DOCKGE最近的版本有问题，你需要做的是备份artalk文件夹，然后去DOCKGE里面删除artalk项目。

记得提前备份好数据，然后重新将artalk文件夹上传

修改docker-compose.yml

将版本号退回2.7.1

image: artalk/artalk-go:2.7.1


保存文件

cd artalk

docker compose pull && docker compose up -d

这样就可以解决

**Comment by bibicadotnet** [comment]
![6dmmdRoEIv](https://github.com/ArtalkJS/Artalk/assets/119997727/8a3dd3c6-21bf-4c32-80c7-ad6abc51dd91)

我对 DOCKGE 没有任何问题

我降级到2.6.4，它再次正常工作:(

**Comment by qwqcode** [comment]
问题已找到并修复，之前的的 v2.7.2 (d81715b) 保存配置会污染已有的配置项 🥲，正在重新编译修复后的 v2.7.2 (0a89426) 版本并发布。

如果有操作过升级 docker 镜像的请重新 pull 并确保进入后台页面是：

<img width="858" alt="image" src="https://github.com/ArtalkJS/Artalk/assets/22412567/1270bf8b-6aa7-437b-b33e-f2fc027238a2">

---

The issue has been identified and fixed. In the previous version, v2.7.2 (d81715b), saving configurations was causing contamination of existing configuration items 🥲. We are currently recompiling the fixed version, v2.7.2 (0a89426), and will release it shortly.

If you have performed a Docker update, please re-pull and ensure that when you access the backend page, it displays as follows: [IMAGE]

**Comment by dianso** [comment]
> 问题已找到并修复，之前的的 v2.7.2 ([d81715b](https://github.com/ArtalkJS/Artalk/commit/d81715b9a421ce96738f78b424860fa3fe9d8d8e)) 保存配置会污染已有的配置项 🥲，正在重新编译修复后的 v2.7.2 ([0a89426](https://github.com/ArtalkJS/Artalk/commit/0a89426c935e0897f401750979ee07277a861b3a)) 版本并发布。
> 
> 如果有操作过升级 docker 镜像的请重新 pull 并确保进入后台页面是：
> 
> <img alt="image" width="858" src="https://private-user-images.githubusercontent.com/22412567/291969903-1270bf8b-6aa7-437b-b33e-f2fc027238a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwOTM2NDAsIm5iZiI6MTcwMzA5MzM0MCwicGF0aCI6Ii8yMjQxMjU2Ny8yOTE5Njk5MDMtMTI3MGJmOGItNmFhNy00MzdiLWIzM2UtZjJmYzAyNzIzOGEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDE3MjkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxMjE5OGYyODI5NjdlMmQ2MjE1Y2E4NWYwYzU5ZDBjN2EwNGYxZTg5NjZiYjU4YjdiOGQ4YTRjYTllMDZkZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BkiJLfuejMp_6Cbw9HS2FhjG1qT_N71XHLGUuj-2m_o">
> The issue has been identified and fixed. In the previous version, v2.7.2 ([d81715b](https://github.com/ArtalkJS/Artalk/commit/d81715b9a421ce96738f78b424860fa3fe9d8d8e)), saving configurations was causing contamination of existing configuration items 🥲. We are currently recompiling the fixed version, v2.7.2 ([0a89426](https://github.com/ArtalkJS/Artalk/commit/0a89426c935e0897f401750979ee07277a861b3a)), and will release it shortly.
> 
> If you have performed a Docker update, please re-pull and ensure that when you access the backend page, it displays as follows: [IMAGE]

感谢，辛苦了，这么晚还修复bug。

**Comment by bibicadotnet** [comment]
好吧，我会等待 docker hub 更新到版本 2.7.2，然后重试

**Comment by qwqcode** [comment]
😭 代码写懵了，错了几个单词 7a026ef0e2208267ca5e97353e09679ce9ad73ed

我睡觉了，明天还要上早八的课

**Comment by qwqcode** [comment]
I plan to introduce a nightly build for testing purposes (potentially unstable) going forward. After comprehensive testing, we will then release the official version to ensure its stability as much as possible. This way, hope to avoid last-minute errors and recompiling before the release! 🤣 Thanks for testing and submitting issues.

**Comment by bibicadotnet** [comment]
祖国功劳 :D

**Comment by eallion** [comment]
有个新问题，前端提示：
```
Artalk Error
TypeError: t.getCommentList is not a function，无法获取评论列表数据
点击重新获取
```

**Comment by qwqcode** [comment]
> 有个新问题，前端提示：
> 
> ```
> 
> Artalk Error
> 
> TypeError: t.getCommentList is not a function，无法获取评论列表数据
> 
> 点击重新获取
> 
> ```

你的主题代码有使用 Artalk.use 吗，如果是主题，可以试试改一下，改为 `ctx.get('list').getCommentNodes().forEach(comment => {`

**Comment by eallion** [comment]
定位到问题了，是因为开启了 `artalk-plugin-lightbox.js` 插件，但插件版本没升级导致的。
