### ISSUE TITLE
建议回复评论时采用嵌套式的评论框，而不是在主评论框 "@回复者" 的类型

### ISSUE THREAD

**Issue by Ice-Hazymoon** [ArtalkJS/Artalk#71]
如题，目前的回复框很不友好，如果评论过多，直接从底部跳到顶部了，稍微不注意也不知道回复的哪一条评论，建议改为嵌套的输入框

**Comment by Ice-Hazymoon** [comment]
新版本找到了个 editorTravel 配置

**Comment by qwqcode** [comment]
哈哈，近期功能在持续更新中，新版 editorTravel 为默认配置

**Comment by qwqcode** [comment]
Duplicate of #61
