### ISSUE TITLE
可否在 Sidebar 中查找用户？

### ISSUE THREAD

**Issue by rebron1900** [ArtalkJS/Artalk#710]
目前想编辑某个用户只能手动翻页查找。

**Comment by rebron1900** [comment]
或在管理员可以在评论界面快捷给用户上标签。

**Comment by dianso** [comment]
是的，现在这一点很麻烦，期待在sidebar可以操作。

我目前是用脚本检索用户米所对应的user表id，然后执行sql来实现，有点麻烦。


sqlite3 /root/docker/artalk/data/artalk.db "UPDATE users SET badge_name = 'joy', badge_color = '#E3537B' WHERE id = 2067;"

**Comment by rebron1900** [comment]
> 是的，现在这一点很麻烦，期待在sidebar可以操作。
> 
> 我目前是用脚本检索用户名所对应的user表id，然后执行sql来实现，有点麻烦。
> 
> sqlite3 /root/docker/artalk/data/artalk.db "UPDATE users SET badge_name = 'joy', badge_color = '#E3537B' WHERE id = 2067;"

有点麻烦，我选择等后续开发组跟进了再弄吧

**Comment by rebron1900** [comment]
这个特性不知道啥时候能上线，催一催

**Comment by rebron1900** [comment]
这个特性是在下一版更新吗？
