### ISSUE TITLE
In version 2.7.x, mergeDeep causes some configurations to be overridden by the default configuration.

### ISSUE THREAD

**Issue by syfxlin** [ArtalkJS/Artalk#718]
## Description

最近我升级了博客中 Artalk 版本到 2.7.2，出现了死循环的问题，从而导致 Artalk 无法正常显示 (Issue 1)，如下：

![image](https://github.com/ArtalkJS/Artalk/assets/28844480/92f1384a-ee46-4dac-9dd5-17f54beb89fb)

但是这个问题已经在 https://github.com/ArtalkJS/Artalk/pull/717 中修复，我尝试修改 node_modules 写入该补丁。然后我发现无法正常显示的问题被修复了，却出现了另一个问题，Artalk 请求的 API 变成了当前的 domain (Issue 2)。

![image](https://github.com/ArtalkJS/Artalk/assets/28844480/37299f27-841d-4b1a-b686-68f46ebc1985)

### Issue 1

- https://stackblitz.com/edit/stackblitz-starters-qwrvkw
- 运行 `npm install && npm run dev`

### Issue 2

- 在 Issue 1 的基础上，修改 `node_modules/artalk/dist/Artalk.es.js#4336` 行，将 `const conf = mergeDeep(defaults, customConf);` 改成 `const conf = mergeDeep({ ...defaults }, customConf);`
- 运行 `npm run dev`

### Issue 1

死循环会导致调用 [Context.updateConf](https://github.com/ArtalkJS/Artalk/blob/v2.7.2/ui/packages/artalk/src/context.ts#L136-L139) 失败，而 Artalk 在 [conf-remoter.ts#L26](https://github.com/ArtalkJS/Artalk/blob/v2.7.2/ui/packages/artalk/src/plugins/conf-remoter.ts#L26) 调用了该方法，失败后转到 [conf-remoter.ts#28](https://github.com/ArtalkJS/Artalk/blob/v2.7.2/ui/packages/artalk/src/plugins/conf-remoter.ts#L28)，此时会再次失败进入 [conf-remoter.ts#L53](https://github.com/ArtalkJS/Artalk/blob/v2.7.2/ui/packages/artalk/src/plugins/conf-remoter.ts#L53)，此后不再更新 UI，导致显示空白。

### Issue 2

在 Artalk 初始化过程中会多次调用 [Context.updateConf](https://github.com/ArtalkJS/Artalk/blob/v2.7.2/ui/packages/artalk/src/context.ts#L136-L139)，当首次进入时 `this.conf` 是自定义的配置，而 `nConf` 仅包含需要更新的配置，如下（请关注 `server` 和 `site` 字段）：

![image](https://github.com/ArtalkJS/Artalk/assets/28844480/c6ed1334-00ea-4338-a5e4-d8002b309e21)

![image](https://github.com/ArtalkJS/Artalk/assets/28844480/ba97dde1-8b0a-4915-a2c8-ca1a66771cd9)

之后进入了 `handelCustomConf` 方法，由于 `nConf` 并不包含 `server` 和 `site` 字段，因此在 `mergeDeep` 之后会被默认的配置覆盖，如下：

![image](https://github.com/ArtalkJS/Artalk/assets/28844480/15704914-3940-4ffe-b243-3dc42614da86)

在出了 `handelCustomConf` 方法后，`mergeDeep` 会将 `this.conf` 中的 `server` 和 `site` 字段设置成默认配置，如下：

![image](https://github.com/ArtalkJS/Artalk/assets/28844480/ed9caa08-6f89-498b-b225-55eb9901fc26)

## Versions

- Artalk UI：2.7.2
- Artalk API：2.7.2

## Possible solutions

合并默认配置的流程在 `new Artalk(config)` 处理一次即可，在处理一次之后 Artalk 中维护的配置已经是完整的，因此后续更新的时候可以去掉合并默认配置的流程。

另外 https://github.com/ArtalkJS/Artalk/pull/717 的修复并不完整，由于默认配置中包含了嵌套的对象，展开语法是浅拷贝，因此默认值中的嵌套对象可能被新的配置覆盖。

**Comment by qwqcode** [comment]
感谢仔细检查！！(´இ皿இ｀)
