### ISSUE TITLE
后端程序自动更新 + 前端后端版本匹配检测

### ISSUE THREAD

**Issue by qwqcode** [ArtalkJS/Artalk#72]

**Comment by qwqcode** [comment]
![artalk-go-upgrade](https://user-images.githubusercontent.com/22412567/163324169-fc471082-fdbc-4cf1-898b-56df49e571de.gif)

https://github.com/ArtalkJS/ArtalkGo/commit/ba7c366b97d683c4dd92f2fb105c6c7245b13635

**Comment by xiamuguizhi** [comment]
强啊 升级 升级！！
