### ISSUE TITLE
升级到2.7.2出现Artalk Error无法展示评论列表

### ISSUE THREAD

**Issue by liub1934** [ArtalkJS/Artalk#725]
TypeError: Cannot read properties of undefined (reading 'version')，无法获取评论列表数据
点击重新获取
![4719ba6a686b54444f4a27bdea0b7ad3](https://github.com/ArtalkJS/Artalk/assets/29849550/998d6bbd-823a-4778-84ff-c982c215d49d)

**Comment by qwqcode** [comment]
你好，可以发下出现错误的页面链接吗

**Comment by liub1934** [comment]
> 你好，可以发下出现错误的页面链接吗

https://liubing.me/friends/

**Comment by qwqcode** [comment]
你的后端程序还是 v2.6.4，后端也要升级到 v2.7.2

**Comment by liub1934** [comment]
> 你的后端程序还是 v2.6.4，后端也要升级到 v2.7.2

感谢 后端升级到最新就可以了。
