### ISSUE TITLE
验证码的字太小了看不清。

### ISSUE THREAD

**Issue by xiamuguizhi** [ArtalkJS/Artalk#73]
之前有人给我反馈过验证码的事情，我一直没碰到就没在意。

昨天登录管理账户 弹出一个验证码  把我搞不会了。

那个字实在是太小了，我还带眼镜 不然 估计都看不清。

在 4 次尝试后 我才正常...

**Comment by xiamuguizhi** [comment]
还有一个问题，就是  谷歌插件  广告拦截那个ADS  有时候会拦截评论到导致无法正常显示 ，只要添加到白名单就正常显示了。

目前 就收到两个反馈  很奇怪， 我也装了这个  没任何问题  目前 不知道触发 原因。

**Comment by qwqcode** [comment]
![image](https://user-images.githubusercontent.com/22412567/162915447-eb8fce40-cb3c-4fe4-8e0e-d2604e6292e8.png)
![image](https://user-images.githubusercontent.com/22412567/162915468-910436d1-21b2-4db7-884b-d84aa5331eff.png)

已修改，应该比之前容易辨认些了

https://github.com/ArtalkJS/ArtalkGo/commit/eda9ae4fd99ba5650ee4023db8c85268432b8df3
https://github.com/ArtalkJS/Artalk/commit/edd9a277209806003bdc36e89e3e59b96758e4d8
