### ISSUE TITLE
设置嵌套论评后，手机端看不到超过评论限制后的越多更多按钮。

### ISSUE THREAD

**Issue by dianso** [ArtalkJS/Artalk#733]
设置嵌套论评后，手机端看不到超过评论限制后的越多更多按钮。

**Comment by qwqcode** [comment]
可以提供下复现的网页吗，我这边复现不了 😢

**Comment by dianso** [comment]
> 可以提供下复现的网页吗，我这边复现不了 😢

https://beitai.cc

电脑端可以，手机端看不到超过限制的更多按钮和嵌套评论

**Comment by qwqcode** [comment]
试试升级 v2.8.0 呢，也许修复了

**Comment by dianso** [comment]
感谢，2.8.1 此BUG已修复。
