### ISSUE TITLE
[2..7.3] Sidebar always show Chinese

### ISSUE THREAD

**Issue by bibicadotnet** [ArtalkJS/Artalk#736]
![2024-01-03_16-45-56](https://github.com/ArtalkJS/Artalk/assets/119997727/794236a2-951f-499a-94e9-eb2ef8e56e7a)

No matter what language you choose, in the latest version 2.7.3, the Chinese language is always displayed

**Comment by qwqcode** [comment]
Hi, the next version v2.8.0, which includes the commit 0d35e66, will fix this issue. Thanks for your feedback! 😃
