### ISSUE TITLE
评论列表无法加载

### ISSUE THREAD

**Issue by UPToZ-Core** [ArtalkJS/Artalk#738]
![image](https://github.com/ArtalkJS/Artalk/assets/73866989/a8a542c8-472e-44a3-8e58-fc9cdad5a682)
![image](https://github.com/ArtalkJS/Artalk/assets/73866989/a8a2eefd-1da6-465f-8d51-9fdaedcda43e)
评论列表无法加载

**Comment by qwqcode** [comment]
试试更新一下 Latex 或图片灯箱插件
