### ISSUE TITLE
之前版本的getCommentList()方法改成什么了

### ISSUE THREAD

**Issue by chengzhongxue** [ArtalkJS/Artalk#739]
是弃用了？，还是修改了，文档里面没有看到

**Comment by qwqcode** [comment]
不好意思，忘记在 CHANGELOG 里面写了

改成 `getCommentNodes` 了

```js
ctx.get('list').getCommentNodes().forEach(comment => {
      const $content = comment.getRender().$content
```

参考 plugin-lightbox：https://github.com/ArtalkJS/Artalk/blob/master/ui/plugin-lightbox/main.ts#L18

**Comment by chengzhongxue** [comment]
好的
