### ISSUE TITLE
如果页面有pajax可能会导致mask反复创建

### ISSUE THREAD

**Issue by rebron1900** [ArtalkJS/Artalk#741]
https://github.com/ArtalkJS/Artalk/blob/889adc6bae2226a8e9e7a9f700a6dd990e642ecc/ui/artalk/src/layer/wrap.ts#L11C1-L11C1

我博客使用了taxi做为pajax工具，每次请求完成后会重载页面初始化脚本，这会导致artalk重复向页面添加mask元素。

https://1900.live/yet-another-rss-reader/

**Comment by rebron1900** [comment]
是否该做个判断呢？

**Comment by qwqcode** [comment]
你好，可以在页面切换前尝试执行 `artalk.destroy()` 销毁原有元素，或者在切换时不执行 `init` 而是 `update` + `reload`
