### ISSUE TITLE
评论列表里头像不显示，通知中心却显示qq头像

### ISSUE THREAD

**Issue by toyo2333** [ArtalkJS/Artalk#749]
两个问题：

1. 不挂代理的情况，头像显示不出来。挂了代理 都显示小灰人 这正常么？如果不正常，请指条路，怎么能改下，哪怕做到都显示小灰人也可以啊

2.我用qq邮箱留言评论，然后通知中心（侧边栏）里"左上角"可以看到我的qq邮箱头像（qq头像），请问这属于正常情况么？我只填邮箱，然后用户名随便填，也可以看到头像，只不过没内容，用户名填之前发过评论的用户名，可以看到之前评论的内容。这头像既然取到了，为啥没有在评论区显示出来？还有这种取头像是否合理？

**Comment by qwqcode** [comment]
QQ 邮箱获取 QQ 头像是因为 gravatar 镜像默认是用的：https://cravatar.cn

（参考：https://github.com/ArtalkJS/Artalk/issues/490）

你可以把 gravatar 镜像改成其他的，可参考文档：https://artalk.js.org/guide/frontend/config.html#gravatar-mirror

> 没有在评论区显示出来？

目前是这样的：昵称不同但邮箱相同，是不同的用户。

**Comment by toyo2333** [comment]
> QQ 邮箱获取 QQ 头像是因为 gravatar 镜像默认是用的：https://cravatar.cn
> 
> （参考：#490 ）
> 
> 你可以把 gravatar 镜像改成其他的，可参考文档：https://artalk.js.org/guide/frontend/config.html#gravatar-mirror
> 
> > 没有在评论区显示出来？
> 
> 目前是这样的：昵称不同但邮箱相同，是不同的用户。

默认的不是那个cn的，是后台里写的是gravatar，那个我不开代理，图就全是X。

我后台按文档说明改为https://cravatar.cn/avatar/    就正常了。以后都可以保持这样用了么？
