### ISSUE TITLE
Error: Param `ua` is required in v2.8.0, v2.8.1

### ISSUE THREAD

**Issue by bibicadotnet** [ArtalkJS/Artalk#767]
![2024-02-05_09-22-20](https://github.com/ArtalkJS/Artalk/assets/119997727/5b11359d-addb-4bcb-a1ac-30427d0ff3bb)
When I edited old comments, an error message appeared
```Failed to comment: Error: Param `ua` is required```

**Comment by dianso** [comment]
我也发现这个问题了

还有，我修改每页评论数，会导致artalk重启，nginx直接502了

**Comment by bibicadotnet** [comment]
Fixed in the latest version 2.8.2
