### ISSUE TITLE
artalk/artalk-go 镜像在 2.8.1 以后 在启动后无法获取 /api/conf 接口

### ISSUE THREAD

**Issue by xxholly32** [ArtalkJS/Artalk#770]
2.7版本都是好的

**Comment by qwqcode** [comment]
你好，v2.8.0 重构了 HTTP API.

- `GET /api/conf` 修改为 `GET /api/v2/conf`

- 同样还有常用的 `POST /api/stat` 修改为 `GET /api/v2/stats/{type}`

我们提供 Swagger.json 和 API 文档供参考：https://artalk.js.org/http-api

可以看下 CHANGELOG.md:

> For Developers: The HTTP API has now been updated to version v2, with a lot of adjustments made, such as changing to Restful API style, request type, request body, response body, etc. data structure, adding error response codes. You can refer to #735 or https://artalk.js.org/http-api Please update all your existing clients to adapt to the new v2 server. The new base path is /api/v2/. The UI package's HTTP client has been implemented to auto-generate based on Swagger.json, and there have been a lot of adjustments to the artalk.ctx.getApi() related code. In addition, the HTTP API no longer enforces checks on the header's Origin and Referer (to implement strict isolation of different sites) but still maintains the original CORS origin check.

**Comment by xxholly32** [comment]
您好，非常感谢您的快速回复，问题已经得到解决了，确实忘记更新了我前端的npm仓库

have a nice day
