### ISSUE TITLE
艾特用户前后端不一致

### ISSUE THREAD

**Issue by penndu** [ArtalkJS/Artalk#771]
前端：
![image](https://github.com/ArtalkJS/Artalk/assets/46226528/e590308b-888f-487d-8040-de6ad51ad710)
后端：
![image](https://github.com/ArtalkJS/Artalk/assets/46226528/947e4304-0b04-4616-9485-59628b6ebe65)

**Comment by qwqcode** [comment]
v2.8.5 已修复该问题
