### ISSUE TITLE
请求 access_token 时发送密码用的是明文

### ISSUE THREAD

**Issue by pkufool** [ArtalkJS/Artalk#776]
很棒的项目，一个小问题，如题。

**Comment by qwqcode** [comment]
你好，很高兴你对这个项目感兴趣！😃

`/api/v2/user/access_token` 接口的 `password` 字段是明文，可以通过更安全的 HTTPS (TLS/SSL) 协议加密传输，防止中间人攻击。在 Artalk 中可以通过修改配置项 `ssl.enabled` 启用该协议。
