### ISSUE TITLE
获取到的操作系统版本不准确

### ISSUE THREAD

**Issue by hiifong** [ArtalkJS/Artalk#78]
![image](https://user-images.githubusercontent.com/89133723/151705774-8198f7eb-4755-470e-8294-ed1b40354821.png)

**Comment by imycard** [comment]
我的也不准，win11识别成win10

**Comment by monsterxcn** [comment]
关于操作系统版本问题，你们使用的浏览器发送请求时带的 `user-agent` 是什么？

我也是 Windows 11 识别成 Windows 10，我观察了下我所用的 Chrome 浏览器 `user-agent` 如下：

```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
```

目前的版本识别代码是这样的，考虑 Windows 11 可能是包含 `Windows NT 10.0;`？

https://github.com/ArtalkJS/Artalk/blob/9193ad4f983c4c089c536db02e646b3da07cb84a/src/lib/detect.js#L97-L110
