### ISSUE TITLE
登录发生异常

### ISSUE THREAD

**Issue by ShaoyuWang1** [ArtalkJS/Artalk#781]
<img width="630" alt="image" src="https://github.com/ArtalkJS/Artalk/assets/40138256/d55033d6-2f67-4d17-af3f-41d6232b43ad">
#bug

**Comment by qwqcode** [comment]
有错误日志吗？检查下密码是否正确呢？

Docker 可以通过 `docker exec -it artalk artalk admin --name="用户名" --email="邮箱" --password="密码"` 重置密码

**Comment by dianso** [comment]
我的也是，这个现象存在很久了，密码是正确的。

现在评论页面登录管理员，然后打开侧栏，然后打开sidebar就可以了。

**Comment by ShaoyuWang1** [comment]
> 有错误日志吗？检查下密码是否正确呢？
> 
> Docker 可以通过 `docker exec -it artalk artalk admin --name="用户名" --email="邮箱" --password="密码"` 重置密码

密码是正确的，日志的path我记不起来了，是什么来着？

**Comment by ShaoyuWang1** [comment]
> 我的也是，这个现象存在很久了，密码是正确的。
> 
> 现在评论页面登录管理员，然后打开侧栏，然后打开sidebar就可以了。

侧栏 没找到打开sidebar的选项诶

**Comment by qwqcode** [comment]
编辑器填了昵称、邮箱，会提示输入密码，然后会出现控制中心按钮，点一下就进侧边栏了

**Comment by qwqcode** [comment]
> 我的也是，这个现象存在很久了，密码是正确的。
> 
> 
> 
> 现在评论页面登录管理员，然后打开侧栏，然后打开sidebar就可以了。

奇怪的问题 🤔️

回头我检查下代码

**Comment by ShaoyuWang1** [comment]
> > 我的也是，这个现象存在很久了，密码是正确的。
> > 现在评论页面登录管理员，然后打开侧栏，然后打开sidebar就可以了。
> 
> 奇怪的问题 🤔️
> 
> 回头我检查下代码

我找了下log，这是我刚刚尝试登陆了下的log：
[2024-02-26.22:35:10.655402] ERROR Response: POST /api/v2/user/access_token ==> "需要验证码" host=www.vvindsky.xyz id= ip=58.250.174.72 referer= status=200 user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
[2024-02-26.22:35:10.655728] ERROR 403: POST /api/v2/user/access_token    2.571434ms 58.250.174.72   Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
[2024-02-26.22:35:16.318482] ERROR Response: POST /api/v2/captcha/verify ==> "验证码错误" host=www.vvindsky.xyz id= ip=58.250.174.72 referer= status=200 user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
[2024-02-26.22:35:16.318779] ERROR 403: POST /api/v2/captcha/verify     2.44904ms 58.250.174.72   Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
[2024-02-26.22:35:21.175635] ERROR Response: POST /api/v2/user/access_token ==> "需要验证码" host=www.vvindsky.xyz id= ip=58.250.174.72 referer= status=200 user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
[2024-02-26.22:35:21.175930] ERROR 403: POST /api/v2/user/access_token    2.262352ms 58.250.174.72   Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

**Comment by dianso** [comment]
> > > 我的也是，这个现象存在很久了，密码是正确的。
> > > 现在评论页面登录管理员，然后打开侧栏，然后打开sidebar就可以了。
> > 
> > 
> > 奇怪的问题 🤔️
> > 回头我检查下代码
> 
> 我找了下log，这是我刚刚尝试登陆了下的log： [2024-02-26.22:35:10.655402] ERROR Response: POST /api/v2/user/access_token ==> "需要验证码" host=www.vvindsky.xyz id= ip=58.250.174.72 referer= status=200 user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 [2024-02-26.22:35:10.655728] ERROR 403: POST /api/v2/user/access_token 2.571434ms 58.250.174.72 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 [2024-02-26.22:35:16.318482] ERROR Response: POST /api/v2/captcha/verify ==> "验证码错误" host=www.vvindsky.xyz id= ip=58.250.174.72 referer= status=200 user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 [2024-02-26.22:35:16.318779] ERROR 403: POST /api/v2/captcha/verify 2.44904ms 58.250.174.72 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 [2024-02-26.22:35:21.175635] ERROR Response: POST /api/v2/user/access_token ==> "需要验证码" host=www.vvindsky.xyz id= ip=58.250.174.72 referer= status=200 user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 [2024-02-26.22:35:21.175930] ERROR 403: POST /api/v2/user/access_token 2.262352ms 58.250.174.72 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

按照我发的试一下，就是在评论界面，输入用户邮箱，弹出密码框，输入后，在发送按钮下面有控制中心，就是侧边栏，打开后，然后打开后端sidebar。

**Comment by ShaoyuWang1** [comment]
> > > > 我的也是，这个现象存在很久了，密码是正确的。
> > > > 现在评论页面登录管理员，然后打开侧栏，然后打开sidebar就可以了。
> > > 
> > > 
> > > 奇怪的问题 🤔️
> > > 回头我检查下代码
> > 
> > 
> > 我找了下log，这是我刚刚尝试登陆了下的log： [2024-02-26.22:35:10.655402] ERROR Response: POST /api/v2/user/access_token ==> "需要验证码" host=www.vvindsky.xyz id= ip=58.250.174.72 referer= status=200 user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 [2024-02-26.22:35:10.655728] ERROR 403: POST /api/v2/user/access_token 2.571434ms 58.250.174.72 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 [2024-02-26.22:35:16.318482] ERROR Response: POST /api/v2/captcha/verify ==> "验证码错误" host=www.vvindsky.xyz id= ip=58.250.174.72 referer= status=200 user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 [2024-02-26.22:35:16.318779] ERROR 403: POST /api/v2/captcha/verify 2.44904ms 58.250.174.72 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 [2024-02-26.22:35:21.175635] ERROR Response: POST /api/v2/user/access_token ==> "需要验证码" host=www.vvindsky.xyz id= ip=58.250.174.72 referer= status=200 user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 [2024-02-26.22:35:21.175930] ERROR 403: POST /api/v2/user/access_token 2.262352ms 58.250.174.72 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
> 
> 按照我发的试一下，就是在评论界面，输入用户邮箱，弹出密码框，输入后，在发送按钮下面有控制中心，就是侧边栏，打开后，然后打开后端sidebar。

是不是咱们的配置不一样？我的评论区是不需要输入密码的，即便我输入的是管理员邮箱也没有输入密码的那一步诶？

**Comment by ShaoyuWang1** [comment]
> > > > 我的也是，这个现象存在很久了，密码是正确的。
> > > > 现在评论页面登录管理员，然后打开侧栏，然后打开sidebar就可以了。
> > > 
> > > 
> > > 奇怪的问题 🤔️
> > > 回头我检查下代码
> > 
> > 
> > 我找了下log，这是我刚刚尝试登陆了下的log： [2024-02-26.22:35:10.655402] ERROR Response: POST /api/v2/user/access_token ==> "需要验证码" host=www.vvindsky.xyz id= ip=58.250.174.72 referer= status=200 user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 [2024-02-26.22:35:10.655728] ERROR 403: POST /api/v2/user/access_token 2.571434ms 58.250.174.72 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 [2024-02-26.22:35:16.318482] ERROR Response: POST /api/v2/captcha/verify ==> "验证码错误" host=www.vvindsky.xyz id= ip=58.250.174.72 referer= status=200 user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 [2024-02-26.22:35:16.318779] ERROR 403: POST /api/v2/captcha/verify 2.44904ms 58.250.174.72 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 [2024-02-26.22:35:21.175635] ERROR Response: POST /api/v2/user/access_token ==> "需要验证码" host=www.vvindsky.xyz id= ip=58.250.174.72 referer= status=200 user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 [2024-02-26.22:35:21.175930] ERROR 403: POST /api/v2/user/access_token 2.262352ms 58.250.174.72 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
> 
> 按照我发的试一下，就是在评论界面，输入用户邮箱，弹出密码框，输入后，在发送按钮下面有控制中心，就是侧边栏，打开后，然后打开后端sidebar。

噢噢是的朋友，我之前没把用户名输入正确（大小写记错了。。），当管理员用户名 和管理员邮箱同时输入正确时就会弹出密码界面然后可以正常输入密码，并进入sdiebar

**Comment by saramand9** [comment]
我昨天也出现了。 但是严重怀疑是因为我在执行docker restart的时候，切换了工作目录导致的。 我发现本地有多个/data目录了

**Comment by ShaoyuWang1** [comment]
我本地只有一个/data诶，而且我的log文件还在正常写入对应的path, 我的问题应该不是切换工作目录导致的。

这是我第二次出现了，第一次出现后我直接docker删容器重新配置了一次，结果重新配置了刚半天之后又出现了（并且到第二次出现时并未restart过）。

两次出现这个问题的开始都是在artalk的后端网页出现一个bug 一样的登陆界面（现在我找不到了不知道如何复现），具体为让我输入密码（类似于在评论区登录时弹出的那个界面），但是又没有给我用户名的输入位而且输入密码也提示密码错误。


我怀疑是不是我在评论区测试是用了正确的管理员邮箱+错误的管理员id导致出现了问题？，但我清楚浏览器缓存之后问题还存在，不知道为何

**Comment by ShaoyuWang1** [comment]
> > > > 我的也是，这个现象存在很久了，密码是正确的。
> > > > 现在评论页面登录管理员，然后打开侧栏，然后打开sidebar就可以了。
> > > 
> > > 
> > > 奇怪的问题 🤔️
> > > 回头我检查下代码
> > 
> > 
> > 我找了下log，这是我刚刚尝试登陆了下的log： [2024-02-26.22:35:10.655402] ERROR Response: POST /api/v2/user/access_token ==> "需要验证码" host=www.vvindsky.xyz id= ip=58.250.174.72 referer= status=200 user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 [2024-02-26.22:35:10.655728] ERROR 403: POST /api/v2/user/access_token 2.571434ms 58.250.174.72 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 [2024-02-26.22:35:16.318482] ERROR Response: POST /api/v2/captcha/verify ==> "验证码错误" host=www.vvindsky.xyz id= ip=58.250.174.72 referer= status=200 user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 [2024-02-26.22:35:16.318779] ERROR 403: POST /api/v2/captcha/verify 2.44904ms 58.250.174.72 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 [2024-02-26.22:35:21.175635] ERROR Response: POST /api/v2/user/access_token ==> "需要验证码" host=www.vvindsky.xyz id= ip=58.250.174.72 referer= status=200 user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 [2024-02-26.22:35:21.175930] ERROR 403: POST /api/v2/user/access_token 2.262352ms 58.250.174.72 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
> 
> 按照我发的试一下，就是在评论界面，输入用户邮箱，弹出密码框，输入后，在发送按钮下面有控制中心，就是侧边栏，打开后，然后打开后端sidebar。

我现在几乎确定了bug的来源，管理员邮箱对应了2个不同的id，你登陆管理员账户之后去用户那个界面检查下，删除重复邮箱的账户应该就问题解决了，我删除之后问题就下市了

**Comment by ShaoyuWang1** [comment]
> > 我的也是，这个现象存在很久了，密码是正确的。
> > 现在评论页面登录管理员，然后打开侧栏，然后打开sidebar就可以了。
> 
> 奇怪的问题 🤔️
> 
> 回头我检查下代码

你试一下，在评论区用管理员邮箱但非管理员id 评论，应该就会出现问题了

**Comment by qwqcode** [comment]
检查了下代码，问题确实存在，v2.8.3 应该修复了这个问题，感谢反馈！！❤️

**Comment by yanue** [comment]
问题同样存在, 用普通的id加上管理员邮箱评论,就会出现

**Comment by ShaoyuWang1** [comment]
> 问题同样存在, 用普通的id加上管理员邮箱评论,就会出现

新版应该已经更新解决了，或者你用上述老哥提到的方法先进后台再把重复的管理员账户删除
