### ISSUE TITLE
无法获取评论列表数据Error: Site name不能为空

### ISSUE THREAD

**Issue by superBiuBiuMan** [ArtalkJS/Artalk#787]
* 请求好像是site name没有传参过去,这个是什么情况啊
![](https://s2.loli.net/2024/03/04/t6YMFDjmQPriI4J.png)
![](https://s2.loli.net/2024/03/04/vs1LynIVMzdOgKC.png)

**Comment by qwqcode** [comment]
你好，你可以试试手动设置一下 `Artalk.init({ site: '站点名' })` 的 `site` 字段为你的站点名

**Comment by dianso** [comment]
新版本的邮箱验证徽章如何启用呀？

**Comment by superBiuBiuMan** [comment]
> 你好，你可以试试手动设置一下 `Artalk.init({ site: '站点名' })` 的 `site` 字段为你的站点名
> 
> 也许是这个问题，可以参考下：[#763 (comment)](https://github.com/ArtalkJS/Artalk/issues/763#issuecomment-1925582233)

对,就是这样,解决了,感谢
