### ISSUE TITLE
访问量大的时候评论经常加载不出来，有没有可能是sqlite的同时写入导致？

### ISSUE THREAD

**Issue by dianso** [ArtalkJS/Artalk#794]
访问量大的时候评论经常加载不出来，有没有可能是sqlite的同时写入导致？

通常刷新一次就正常了

vps是4核16G内存，应该不会是内存不够。

现在一天有几百条评论，有时候同时评论的人多了，就加载不出来评论了。

有没有可能是并发读写问题？写入数据时锁死，无法读。

我见许多项目的sqlite数据库都改成了WAL（Write-Ahead Logging）模式，这种模式可以让多个连接同时进行写入操作。

**Comment by qwqcode** [comment]
SQLite不是专为高并发设计的，它是一个轻量级的数据库，当并发写入量增加时，SQLite可能会出现性能下降的问题，由于它的默认事务模式是Rollback Journal，切换使用WAL（Write-Ahead Logging）模式可以帮助改善这个问题。

（据SQLite官方文档介绍，WAL模式下的并发读写性能可能比传统的Rollback Journal模式快2到3倍）

我可以尝试在Artalk中加入SQLite WAL的支持，你可以通过修改配置启用它。如果有需要，实际性能提升可以自行压测对比相关接口。:)

另外，虽然WAL模式可以改善并发性能，但在高并发环境下，这种提升可能仍然有限。**如果你的应用经常需要处理大量并发读写请求，那么可能需要考虑使用更适合高并发环境的DB，比如PostgreSQL或MySQL。另外可以打开Redis高速缓存以缓解DB压力。**

最后，虽然你的VPS有16GB的内存，但SQLite的性能问题更多的是和磁盘I/O有关，而不是内存容量。所以，增加内存并不能直接解决这个问题，需要修改SQLite配置，例如增大它的缓存、启用批量插入、切换WAL模式来减少磁盘I/O的需求，也许就会有提升。:)

参考内容：

> 对比区别：Rollback Journal模式是SQLite的默认事务管理模式，在此模式下，一个写事务可能会阻塞其他读写事务，因为它需要记录所有将要被修改的数据库页的原始内容，以便在事务失败时恢复；而Write-Ahead Logging (WAL)模式，事务改变先写入单独的WAL文件，待事务成功后才合并到数据库，其优势在于它允许一个写事务和多个读事务同时进行，减少了阻塞，提高了并发性能，同时在系统崩溃时可从WAL中恢复数据。
>
> 对比劣势：Rollback Journal模式的劣势在于，当一个写事务在进行时，可能会阻塞其他的读写事务，因为它需要独占数据库来记录所有将要被修改的数据库页的原始内容，这在并发环境下可能会导致性能瓶颈。而Write-Ahead Logging (WAL)模式，尽管减少了阻塞并提高了并发性能，但其劣势在于，它需要额外的磁盘空间来存储WAL文件，并且在处理大量小事务时，WAL模式可能不如Rollback Journal模式高效，因为它需要频繁地写入和合并WAL文件。
>
> 从SQLite版本3.7.0开始，SQLite提供了另一种日志模式：Write-Ahead Logging (WAL)。在WAL模式下，所有的更改都首先被写入一个单独的日志文件，然后在事务提交时，这些更改才被写入主数据库文件。这种方式可以提供更好的并发性能，因为读取操作和写入操作可以同时进行，而不需要等待对方完成。虽然WAL模式提供了一些优势，但是SQLite仍然默认使用Rollback Journal模式，因为WAL模式有一些限制，例如在网络文件系统上可能不可用，并且需要定期进行日志清理（checkpointing）操作。

**Comment by dianso** [comment]
> SQLite不是专为高并发设计的，它是一个轻量级的数据库，当并发写入量增加时，SQLite可能会出现性能下降的问题，由于它的默认事务模式是Rollback Journal，切换使用WAL（Write-Ahead Logging）模式可以帮助改善这个问题。
> 
> （据SQLite官方文档介绍，WAL模式下的并发读写性能可能比传统的Rollback Journal模式快2到3倍）
> 
> 我可以尝试在Artalk中加入SQLite WAL的支持，你可以通过修改配置启用它。如果有需要，实际性能提升可以自行压测对比相关接口。:)
> 
> 另外，虽然WAL模式可以改善并发性能，但在高并发环境下，这种提升可能仍然有限。**如果你的应用经常需要处理大量并发读写请求，那么可能需要考虑使用更适合高并发环境的DB，比如PostgreSQL或MySQL。另外可以打开Redis高速缓存以缓解DB压力。**
> 
> 最后，虽然你的VPS有16GB的内存，但SQLite的性能问题更多的是和磁盘I/O有关，而不是内存容量。所以，增加内存并不能直接解决这个问题，需要修改SQLite配置，例如增大它的缓存、启用批量插入、切换WAL模式来减少磁盘I/O的需求，也许就会有提升。:)
> 
> 参考内容：
> 
> > 对比区别：Rollback Journal模式是SQLite的默认事务管理模式，在此模式下，一个写事务可能会阻塞其他读写事务，因为它需要记录所有将要被修改的数据库页的原始内容，以便在事务失败时恢复；而Write-Ahead Logging (WAL)模式，事务改变先写入单独的WAL文件，待事务成功后才合并到数据库，其优势在于它允许一个写事务和多个读事务同时进行，减少了阻塞，提高了并发性能，同时在系统崩溃时可从WAL中恢复数据。
> > 对比劣势：Rollback Journal模式的劣势在于，当一个写事务在进行时，可能会阻塞其他的读写事务，因为它需要独占数据库来记录所有将要被修改的数据库页的原始内容，这在并发环境下可能会导致性能瓶颈。而Write-Ahead Logging (WAL)模式，尽管减少了阻塞并提高了并发性能，但其劣势在于，它需要额外的磁盘空间来存储WAL文件，并且在处理大量小事务时，WAL模式可能不如Rollback Journal模式高效，因为它需要频繁地写入和合并WAL文件。
> > 从SQLite版本3.7.0开始，SQLite提供了另一种日志模式：Write-Ahead Logging (WAL)。在WAL模式下，所有的更改都首先被写入一个单独的日志文件，然后在事务提交时，这些更改才被写入主数据库文件。这种方式可以提供更好的并发性能，因为读取操作和写入操作可以同时进行，而不需要等待对方完成。虽然WAL模式提供了一些优势，但是SQLite仍然默认使用Rollback Journal模式，因为WAL模式有一些限制，例如在网络文件系统上可能不可用，并且需要定期进行日志清理（checkpointing）操作。

感谢你的回复，如果添加了WAL我试试吧，不行了我换成mysql或者postgresql

**Comment by qwqcode** [comment]
你好，修改 `db.file` 配置项为 `./data/artalk.db?_journal=WAL` 就可以开启 `WAL`

更多参数可提高性能例如：

```
./data/artalk.db?_busy_timeout=10000&_journal_mode=WAL&_synchronous=NORMAL&_cache_size=-16000
```

参考 `mattn/go-sqlite3` 这个上游依赖的文档：https://github.com/mattn/go-sqlite3?tab=readme-ov-file#connection-string

---

经过测试，WAL 被正常启用：

<img width="530" alt="image" src="https://github.com/ArtalkJS/Artalk/assets/22412567/2bb87178-cfba-4534-9834-e3290d994eb9">

<img width="177" alt="image" src="https://github.com/ArtalkJS/Artalk/assets/22412567/a29b5bbb-1dc5-494c-a47d-1bc55fcfb0bc">

**Comment by dianso** [comment]
> 你好，修改 `db.file` 配置项为 `./data/artalk.db?_journal=WAL` 就可以开启 `WAL`
> 
> 更多参数可提高性能例如：
> 
> ```
> ./data/artalk.db?_busy_timeout=10000&_journal_mode=WAL&_synchronous=NORMAL&_cache_size=-16000
> ```
> 
> 参考 `mattn/go-sqlite3` 这个上游依赖的文档：https://github.com/mattn/go-sqlite3?tab=readme-ov-file#connection-string
> 
> 经过测试，WAL 被正常启用：
> 
> <img alt="image" width="530" src="https://private-user-images.githubusercontent.com/22412567/312459831-2bb87178-cfba-4534-9834-e3290d994eb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMzg2NDIsIm5iZiI6MTcxMDMzODM0MiwicGF0aCI6Ii8yMjQxMjU2Ny8zMTI0NTk4MzEtMmJiODcxNzgtY2ZiYS00NTM0LTk4MzQtZTMyOTBkOTk0ZWI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDEzNTkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmNTRiYzNkNDNiNzQwNWIzOTBlYTdlMjRhZTI1Yjk2ZjQ3NDc0ZDgyYzk0YjNiMGYyZDgyMzk2M2JhZGJmZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5qIayiOeQCLd13dJF0uQ-iPYL_sC333ez57rcrbFFNQ"> <img alt="image" width="177" src="https://private-user-images.githubusercontent.com/22412567/312459806-a29b5bbb-1dc5-494c-a47d-1bc55fcfb0bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMzg2NDIsIm5iZiI6MTcxMDMzODM0MiwicGF0aCI6Ii8yMjQxMjU2Ny8zMTI0NTk4MDYtYTI5YjViYmItMWRjNS00OTRjLWE0N2QtMWJjNTVmY2ZiMGJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDEzNTkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliZDZkZTVlNGQ1NjAzNGJjOTIzNjg2ODE4YTM1ZmQwNDM0YzRlNmY4ZDYxZDM0NzBkYzYwYjgxMWNmNTZjZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vWJ0EuJMg7U3N1PYUm4R3XhiHq4bpFx5ZAHWVI2DeVU">

😅

我还是不会操作，期待以后更新加到配置文件里傻瓜式操作。

**Comment by qwqcode** [comment]
<img width="435" alt="image" src="https://github.com/ArtalkJS/Artalk/assets/22412567/540d982c-2730-4130-b499-2c15999e046c">

填到这里手动重启 Docker 容器就可以

**Comment by dianso** [comment]
非常感谢！

我关闭这个了。

测试了一天，之前频繁出现的，今天没有出现了。

Artalk Error
Failed to load comments
TypeError: Failed to fetch

**Comment by dianso** [comment]
> <img alt="image" width="435" src="https://private-user-images.githubusercontent.com/22412567/312487348-540d982c-2730-4130-b499-2c15999e046c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0OTQwMDMsIm5iZiI6MTcxMDQ5MzcwMywicGF0aCI6Ii8yMjQxMjU2Ny8zMTI0ODczNDgtNTQwZDk4MmMtMjczMC00MTMwLWI0OTktMmMxNTk5OWUwNDZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDA5MDgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhYTViNDI0YjRkNWVkYWNiMzg3NmMxMjk2ZjU1NTg4YjcxZGU3NDY3MmY0ZGM2MTE5NTdhOTc4MjA1OTgwNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xxKU2OQhc-vq6xzhlZjnmnxvhACuUjYsZGDGFyBCX1w">
> 填到这里手动重启 Docker 容器就可以

我发现按照你发的，2个配置没有生效

_synchronous=NORMAL 这样还是会以FULL模式运行

sqlite进入数据库输入PRAGMA synchronous;查询是2，FULL模式

看了下文档

0 | OFF
1 | NORMAL
2 | FULL
3 | EXTRA

我发现无论
_synchronous=NORMAL还是_synchronous=1都无法生效


还有_cache_size这个是负数的话没效果，看文档，早期会以绝对值转换成正数，现在3.7的版本只能是正整数，默认是缓存2000页。
