### ISSUE TITLE
总是需要验证码参数有BUG

### ISSUE THREAD

**Issue by imycard** [ArtalkJS/Artalk#80]
# 验证码
captcha:
  enabled: true # 总开关
  always: true # 总是需要验证码

将总是需要验证码打开后，即使验证输入正确也不会跳回评论界面，还继续要求输入验证码。log文件提示ERROR 响应: POST /api/add ==> "需要验证码"

**Comment by qwqcode** [comment]
最新版后端已修复，感谢反馈
https://github.com/ArtalkJS/ArtalkGo/releases/tag/v2.0.6
