### ISSUE TITLE
后台登录时提示Need to select username

### ISSUE THREAD

**Issue by Cocojcc** [ArtalkJS/Artalk#803]
今天后台登录时，一直登录失败，提示信息为
```
{"msg":"Need to select username","need_name_select":["***","***"]}
```
登录界面也没看到可以填username的地方，请问这种情况是怎么回事呀？

**Comment by Cocojcc** [comment]
知道了，是因为同一个邮箱创建了多个不同用户名的用户
我新建一个全新的管理员账户把之前的那个重复的删掉就可以了
如何避免创建重复的账户呢，即邮箱和用户名一样的账户

**Comment by qwqcode** [comment]
你好，可以尝试升级到最新版，也许修复了这个问题 :)
