### ISSUE TITLE
粘贴的图片点击后无法放大

### ISSUE THREAD

**Issue by penndu** [ArtalkJS/Artalk#806]
![img_v3_028r_a7785863-dad1-463b-9e65-f9a32f21f71g](https://github.com/ArtalkJS/Artalk/assets/46226528/190583fe-fe89-4891-9e29-ecbb08ffcf64)
![img_v3_028r_4b4b6c89-5ce5-487f-bd36-3c2ef8157c4g](https://github.com/ArtalkJS/Artalk/assets/46226528/998c2ba4-d903-4ef5-8c16-8f691b18b16b)

问题复现：https://dusays.com/517/?atk_comment=36281&atk_notify_key=6BHLZ

**Comment by dianso** [comment]
是的，我也发现了。

提供一个js，可以放大，找gpt3.5写的。

```
// 为所有图片添加点击事件监听器
document.querySelectorAll('img:not([src$=".svg"])').forEach(img => img.addEventListener('click', (event) => {
    event.stopPropagation(); // 阻止事件冒泡，防止点击图片时触发下面的点击事件处理程序
  
    // 创建遮罩层
    const overlay = document.createElement('div');
    overlay.style.cssText = 'position: fixed; top: 0; left: 0; width: 100%; height: 100%; background-color: rgba(0, 0, 0, 0.8); display: flex; align-items: center; justify-content: center; z-index: 9999;';
  
    // 创建图片容器
    const imageContainer = document.createElement('div');
    imageContainer.style.cssText = 'position: relative; overflow: auto;';
  
    // 创建图片元素
    const image = document.createElement('img');
    image.setAttribute('src', img.getAttribute('src'));
    image.style.cssText = 'display: block; margin: 0 auto;';
  
    // 将图片添加到容器中
    imageContainer.appendChild(image);
    overlay.appendChild(imageContainer);
    document.body.appendChild(overlay);
  
    // 定义函数用于移除遮罩层
    const removeOverlay = () => {
      document.body.removeChild(overlay);
      document.removeEventListener('click', removeOverlay);
    };
  
    // 5秒后自动移除遮罩层
    setTimeout(removeOverlay, 5000);
  
    // 添加点击事件监听器，当点击遮罩层以外的区域时移除遮罩层
    document.addEventListener('click', (event) => {
      if (event.target !== image) {
        removeOverlay();
      }
    });
  
    // 定义闪光边框的颜色数组
    const colors = ['red', 'orange', 'yellow', 'green', 'blue', 'indigo', 'violet', 'pink', 'cyan', 'lime'];
    let currentIndex = 0;
  
    // 定义函数用于实现闪光边框效果
    const animateBorder = () => {
      image.style.border = `5px solid ${colors[currentIndex]}`;
      currentIndex = (currentIndex + 1) % colors.length;
      setTimeout(animateBorder, 200);
    };
  
    // 启动闪光边框动画
    animateBorder();
  
    // 根据设备类型设置图片大小
    const isMobile = window.matchMedia('(max-width: 600px)').matches;
    if (isMobile) {
      image.style.maxWidth = '90%';
      image.style.maxHeight = '90%';
      imageContainer.style.maxWidth = '90%';
      imageContainer.style.maxHeight = '90%';
    } else {
      image.style.maxWidth = '900px';
      image.style.maxHeight = '900px';
      imageContainer.style.maxWidth = '900px';
      imageContainer.style.maxHeight = '900px';
    }
  }));  
```

**Comment by penndu** [comment]
> 是的，我也发现了。
> 
> 提供一个js，可以放大，找gpt3.5写的。
> 
> ```
> // 为所有图片添加点击事件监听器
> document.querySelectorAll('img:not([src$=".svg"])').forEach(img => img.addEventListener('click', (event) => {
>     event.stopPropagation(); // 阻止事件冒泡，防止点击图片时触发下面的点击事件处理程序
>   
>     // 创建遮罩层
>     const overlay = document.createElement('div');
>     overlay.style.cssText = 'position: fixed; top: 0; left: 0; width: 100%; height: 100%; background-color: rgba(0, 0, 0, 0.8); display: flex; align-items: center; justify-content: center; z-index: 9999;';
>   
>     // 创建图片容器
>     const imageContainer = document.createElement('div');
>     imageContainer.style.cssText = 'position: relative; overflow: auto;';
>   
>     // 创建图片元素
>     const image = document.createElement('img');
>     image.setAttribute('src', img.getAttribute('src'));
>     image.style.cssText = 'display: block; margin: 0 auto;';
>   
>     // 将图片添加到容器中
>     imageContainer.appendChild(image);
>     overlay.appendChild(imageContainer);
>     document.body.appendChild(overlay);
>   
>     // 定义函数用于移除遮罩层
>     const removeOverlay = () => {
>       document.body.removeChild(overlay);
>       document.removeEventListener('click', removeOverlay);
>     };
>   
>     // 5秒后自动移除遮罩层
>     setTimeout(removeOverlay, 5000);
>   
>     // 添加点击事件监听器，当点击遮罩层以外的区域时移除遮罩层
>     document.addEventListener('click', (event) => {
>       if (event.target !== image) {
>         removeOverlay();
>       }
>     });
>   
>     // 定义闪光边框的颜色数组
>     const colors = ['red', 'orange', 'yellow', 'green', 'blue', 'indigo', 'violet', 'pink', 'cyan', 'lime'];
>     let currentIndex = 0;
>   
>     // 定义函数用于实现闪光边框效果
>     const animateBorder = () => {
>       image.style.border = `5px solid ${colors[currentIndex]}`;
>       currentIndex = (currentIndex + 1) % colors.length;
>       setTimeout(animateBorder, 200);
>     };
>   
>     // 启动闪光边框动画
>     animateBorder();
>   
>     // 根据设备类型设置图片大小
>     const isMobile = window.matchMedia('(max-width: 600px)').matches;
>     if (isMobile) {
>       image.style.maxWidth = '90%';
>       image.style.maxHeight = '90%';
>       imageContainer.style.maxWidth = '90%';
>       imageContainer.style.maxHeight = '90%';
>     } else {
>       image.style.maxWidth = '900px';
>       image.style.maxHeight = '900px';
>       imageContainer.style.maxWidth = '900px';
>       imageContainer.style.maxHeight = '900px';
>     }
>   }));  
> ```

额额，能力有限，不知道怎么用~

**Comment by penndu** [comment]
fix by version 2.8.4
