### ISSUE TITLE
Github奇怪问题导致Artalk.js无法使用

### ISSUE THREAD

**Issue by echs-top** [ArtalkJS/Artalk#814]
复现bug文章：https://echs.top/art/261
ps:并非bug，只是请教一下开发者是否知道原因
进过github在线编辑器后js无法使用

**Comment by inkss** [comment]
全角字符了。

```
https://cdn.echs.top/bug/Artalk2.js
```

<img width="672" alt="24-04-08_104642" src="https://github.com/ArtalkJS/Artalk/assets/31947043/3390279f-ac14-40ad-8974-31864f7cef25">

**Comment by Mister-Hope** [comment]
Seems that you some how break the file content, see comment above

**Comment by echs-top** [comment]
> 全角字符了。
> 
> ```
> https://cdn.echs.top/bug/Artalk2.js
> ```
> 
> <img alt="24-04-08_104642" width="672" src="https://private-user-images.githubusercontent.com/31947043/320339977-3390279f-ac14-40ad-8974-31864f7cef25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MDU2OTEsIm5iZiI6MTcxMjYwNTM5MSwicGF0aCI6Ii8zMTk0NzA0My8zMjAzMzk5NzctMzM5MDI3OWYtYWMxNC00MGFkLTg5NzQtMzE4NjRmN2NlZjI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDE5NDMxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4NDA4MGI5ODQ3MGRmNTJlYWFlYjhjYzIyZTU4MWNhNjIyYzRjNDM3Yjc4YTY2NDE3ZWVjZWFjN2U0NjdhYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KfotZduWqqGtr4HbEeAwuOv0l_QcCtMnW_Ahb_VcwMY">

github有点逆天啊
