### ISSUE TITLE
"412 Request Entity Too Large" in uploading the migration file

### ISSUE THREAD

**Issue by syhily** [ArtalkJS/Artalk#834]
<img width="1181" alt="image" src="https://github.com/ArtalkJS/Artalk/assets/1761698/61c2bf3f-1388-49c8-92d0-20eccaa51b9c">

The file size exceed 4,975,036 bytes (5 MB)

**Comment by qwqcode** [comment]
Hello, the issue has been fixed in version 2.8.5. Thank you for your feedback! ❤️

**Comment by syhily** [comment]
Thanks. I have tested it locally. It has been fixed.
