### ISSUE TITLE
希望支持飞书推送卡片消息

### ISSUE THREAD

**Issue by HeLongaa** [ArtalkJS/Artalk#839]
飞书推送是纯文字，希望支持卡片推送：
例：
发送消息卡片仅需要将消息体的 content 字符串替换为 card 结构体。

请求消息体示例
{
    "msg_type": "interactive",
    "card": {
        "elements": [{
                "tag": "div",
                "text": {
                        "content": "**西湖**，位于浙江省杭州市西湖区龙井路1号，杭州市区西部，景区总面积49平方千米，汇水面积为21.22平方千米，湖面面积为6.38平方千米。",
                        "tag": "lark_md"
                }
        }, {
                "actions": [{
                        "tag": "button",
                        "text": {
                                "content": "更多景点介绍 :玫瑰:",
                                "tag": "lark_md"
                        },
                        "url": "https://www.example.com",
                        "type": "default",
                        "value": {}
                }],
                "tag": "action"
        }],
        "header": {
                "title": {
                        "content": "今日旅游推荐",
                        "tag": "plain_text"
                }
        }
    }
}

**Comment by HeLongaa** [comment]
![image](https://github.com/ArtalkJS/Artalk/assets/71657914/b032b23a-8ab9-4b52-b78d-db9bb3c2ef83)

**Comment by qwqcode** [comment]
你好，新版将支持飞书卡片消息，可以把 `admin_notify.notify_tpl` (多元推送 > 通知模版) 设置为：

```
💬 [{{site_name}}] 有新评论

@{{reply_nick}}: {{reply_content}}

{{link_to_reply}}
```

第一行内容将作为卡片的标题，最后一行内容将作为“回复”按钮的链接。

通过 `admin_notify.lark.msg_type`（多元推送 > 飞书 > 消息类型） 设置为 `card` 启用这个功能。

感谢反馈！

<img width="396" alt="image" src="https://github.com/ArtalkJS/Artalk/assets/22412567/97f2ddce-de7b-4ca7-8a0e-bba55da3e09c">

**Comment by HeLongaa** [comment]
感谢回复，祝好

**Comment by qwqcode** [comment]
你好，刚刚 v2.8.6 版本已发布了，包含了这个更新

**Comment by HeLongaa** [comment]
感谢开发者，祝好
