### ISSUE TITLE
[Feature] 登录验证功能

### ISSUE THREAD

**Issue by clsty** [ArtalkJS/Artalk#840]
目前 Artalk 不支持对普通用户的邮箱进行验证，也不支持 OAuth（第三方登录验证），因此无法防止身份盗用。
希望能添加此机制。

**Comment by qwqcode** [comment]
目前这个功能正在开发当中，之后待完善和测试稳定后将作为插件这个功能，一些相关的 issue：#728 #711 #279

https://github.com/ArtalkJS/Artalk/assets/22412567/05aee7e5-f4ff-4680-a6af-057c64ef68f9

https://github.com/ArtalkJS/Artalk/assets/22412567/6441e2e7-0d1f-4ae2-a1d5-19bde0a273b7

https://github.com/ArtalkJS/Artalk/assets/22412567/9336a722-2e1d-4a7a-8d63-55cb3ebc376a

**Comment by penndu** [comment]
希望允许登录用户与非登录用户并存。
允许访客可以通过用户名和邮箱，认领已留言非注册用户。
允许已登录用户自定义头衔，如果可以的话，自定义后需管理员审核后再显示。

**Comment by gxres042** [comment]
这个功能好像跟 todo 里的 “开放用户注册” 相关吧？

**Comment by clsty** [comment]
非常感谢如此积极的回复！我希望能尽快有一个基础的（比如发验证码到邮箱），更丰富的功能可以从长计议。

**Comment by clsty** [comment]
我简单测试了一下，目前邮箱验证功能已可用，谢谢你 @qwqcode 

---

题外话，我测试所使用的是自行构建得到的二进制程序；GitHub 自动构建的那个 nightly build，我用完全相同的方式运行，会得到 `./artalk: no such file or directory` 的奇怪报错，运行权限什么的也是给了的。普通的 Release 比如 v2.3.5，以及我自己构建的，都不会有这种问题。

当然如果要展开说，就应当属于另一个 issue 了。由于这不是什么大问题（不用 nightly build 或者自己构建就行了），我就简单提一句。

**Comment by aak1247** [comment]
有没有可能搞一下qq？
