### ISSUE TITLE
更改站点名称后在sidbar里点击评论跳转的是artalk.xxxx.com地址

### ISSUE THREAD

**Issue by rebron1900** [ArtalkJS/Artalk#847]
如题，没改站点名称之前是跳的博客网站，我那里没操作对吗？

**Comment by qwqcode** [comment]
你好，可以尝试将站点URL修改为你的博客网址，例如 `blog.xxxx.com` 而不是 `artalk.xxxx.com`

**Comment by rebron1900** [comment]
> 你好，可以尝试将站点URL修改为你的博客网址，例如 `blog.xxxx.com` 而不是 `artalk.xxxx.com`

siderbar中站点url已经是我的博客网址了。
artalk实例的url必须是artalk.xxx.com把？
