### ISSUE TITLE
upgit配置问题

### ISSUE THREAD

**Issue by HeLongaa** [ArtalkJS/Artalk#859]
已配置upgit，并将upgit执行文件放置在服务器/usr/bin/目录下，且在服务器可以正常上传图片，Artalk上传失败，如下

![image](https://github.com/ArtalkJS/Artalk/assets/71657914/45ebbb14-6310-4597-ac6d-9fb795d90bba)

log：
`
{"level":"ERROR","ts":"2024-05-08T16:04:58.971+0800","caller":"[handler/upload.go:221]","msg":"[IMG_UPLOAD] [upgit] cmd.Start: exec: \"upgit\": executable file not found in $PATH"}
{"level":"ERROR","ts":"2024-05-08T16:04:58.971+0800","caller":"[handler/upload.go:177]","msg":"[IMG_UPLOAD] [upgit] upgit output: "}
{"level":"ERROR","ts":"2024-05-08T16:04:58.971+0800","caller":"[handler/upload.go:178]","msg":"通过 upgit 上传图片失败","id":"7f5f467f-60ad-4c83-bbea-10b09bc0356f","path":"/api/v2/upload","method":"POST","ip":"117.136.73.145","remote_addr":"111.6.43.106:38794","host":"artalk.duolaa.asia","referer":"","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0","status":500}
{"level":"ERROR","ts":"2024-05-08T16:04:58.971+0800","msg":"[HTTP] 16:04:58 | 500 |    4.682093ms | 117.136.73.145 | POST | /api/v2/upload | - | 7f5f467f-60ad-4c83-bbea-10b09bc0356f"}
`
配置

![image](https://github.com/ArtalkJS/Artalk/assets/71657914/cf3027b0-ffc0-4700-aab5-e3d455685e6a)

upgit配置文件路径正确。

**Comment by jiayan586** [comment]
试试删除命令行参数后面的  -t /artalk-img
代码里已经拼接了

**Comment by monsterxcn** [comment]
是 Docker 部署的吗？是的话润一下看看，估计没挂载吧

```bash
docker exec artalk bash -c "which upgit"
```

**Comment by HeLongaa** [comment]
> 是 Docker 部署的吗？是的话润一下看看，估计没挂载吧
> 
> ```shell
> docker exec artalk bash -c "which upgit"
> ```
> 
> 输出 就对，没输出就不对。`/usr/bin/upgit`
> 
> 我的 ：`compose.yaml`
> 
> ```yaml
> version: '3.5'
> services:
>   artalk:
>     container_name: artalk
>     image: artalk/artalk-go:nightly
>     restart: always
>     ports:
>       - 23366:23366
>     volumes:
>       - ./data:/data
>       - ./upgit/upgit:/usr/bin/upgit
> ```
> 
> 再不行就把 upgit 权限给高点，777！
> 
> ```shell
> sudo chmod -R 777 ./upgit/upgit
> ```



果然是没挂载，感谢！
