### ISSUE TITLE
建议，将跳过不验证添加到上方登录框中

### ISSUE THREAD

**Issue by echs-top** [ArtalkJS/Artalk#863]
![Screenshot_2024-05-09-15-06-53-840_mark via](https://github.com/ArtalkJS/Artalk/assets/88482848/abbbcbbc-812b-4283-9642-123ac4beb4a8)

**Comment by echs-top** [comment]
可以放到上方登录字样旁边，放在底部字体容易看不清
![IMG_20240509_151353](https://github.com/ArtalkJS/Artalk/assets/88482848/66bb918f-7603-454c-bb0a-17967a3b5bdb)

**Comment by echs-top** [comment]
或者直接添加一个跳过不验证的选项

**Comment by Doradx** [comment]
附议。建议：
白色背景填充下来，弄个匿名图标 “匿名评论”or “跳过验证” or “不想验证”，均可。
![image](https://github.com/user-attachments/assets/f1b201b2-6e55-4198-a830-f488c4e6cb99)
目前这个提示位置不够明显，很难发现。

**Comment by qwqcode** [comment]
<img width="698" alt="SCR-20240831-szxi" src="https://github.com/user-attachments/assets/31dcea57-ed24-4d13-9110-4122b47964a4">

新版已修改
