### ISSUE TITLE
内容限高有些问题

### ISSUE THREAD

**Issue by UPToZ-Core** [ArtalkJS/Artalk#865]
内容被折叠的时候，展开会被内容限高给固定住高度。折叠的内容没有超过限高大小，但是展开后，变成了限高的固定高度。
另外能不能加个代码块的开关，我发现artalk的代码块与我博客主题的代码块产生了冲突，导致无法复制代码块的内容。

**Comment by monsterxcn** [comment]
说的什么看不懂，看看你的博客

**Comment by UPToZ-Core** [comment]
https://blog.uptoz.cn/you-lian
我将部分内容进行折叠 后台设置了内容限高500px，但是实际内容未达到500px时，也会被强制变成500px的高度，另外是不是不能单独设置子评论的内容限高呢？

**Comment by qwqcode** [comment]
v2.8.7 已发布，修复了这个问题，感谢反馈~
