### ISSUE TITLE
导入数据，email 为空的情况下， nick 数据会变成空

### ISSUE THREAD

**Issue by immyw** [ArtalkJS/Artalk#866]
导入 waline 的数据
按照文档迁移的数据模板改了数据
通过后台的导入功能
导入数据

发现 如果email 为空， 导入的数据， Nick 数据会被删掉，也变成为 空

还有后台可以看到回复的数据
为什么网页里看不到回复人的数据？

**Comment by jerryc127** [comment]
这是不是 Bug 还是我操作有问题
管理员看到回下啊
