### ISSUE TITLE
邮件与webhook都无法正常收到通知

### ISSUE THREAD

**Issue by eryajf** [ArtalkJS/Artalk#869]
不知从哪个版本开始，评论通知始终无法收到。
我配置了email，和webhook两个通知，现在两个都无法正常发出。看日志里也没有报错信息，请问该如何排查呢？

**Comment by eryajf** [comment]
找到原因了，是关闭了待审评论通知的选项，又因为默认新评论都是待审的，所以没有通知出来

**Comment by qwqcode** [comment]
原来如此 👀

**Comment by eryajf** [comment]
哈哈哈，不知道在哪次升级的时候，这个选项莫名其妙的变成false了(也可能是自己什么时候误点了)，就无法正常使用了。前几天打开一看，积攒了十几条评论😂
