### ISSUE TITLE
在评论的时候不可以@多个人吗？

### ISSUE THREAD

**Issue by rebron1900** [ArtalkJS/Artalk#878]
如题，多个评论发起了同一个相关想法，我只能单独对某一个人进行@回复，如果想通知其他有同样想法的人就只能再发起一条回复，但是不太想这么做。

**Comment by Mister-Hope** [comment]
If you can ping any amount of person in one comment I'm afraid these can lead to abuse use.  Strangers might use scripts to send ads post to anyone on the page with an automatic script.

**Comment by rebron1900** [comment]
emmm，的确有这个问题。
那么，多人@不推送或者控制是否推送通知呢？
又或者这个权限只给管理员？

**Comment by qwqcode** [comment]
duplicate of #878
