### ISSUE TITLE
[建议] 夜间模式需要优化

### ISSUE THREAD

**Issue by jerryc127** [ArtalkJS/Artalk#890]
目前的 artalk 似乎是先加载评论框，然后在判断夜间模式，给父元素添加 夜间模式的 class name,
这样会导致夜间模式下，会出现白色的评论框，然后再变黑

建议是加载评论框前，先判断夜间模式，

![recording](https://github.com/ArtalkJS/Artalk/assets/16351105/8fb42950-4401-4ad3-b195-5d848b11bfe6)

**Comment by white0dew** [comment]
+1，在我的网站上，也遇到了这个问题
