### ISSUE TITLE
你好，一般可以参考 https://artalk.js.org/guide/frontend/pv.html 查询访问量。

### ISSUE THREAD

**Issue by white0dew** [ArtalkJS/Artalk#895]
你好，一般可以参考 https://artalk.js.org/guide/frontend/pv.html 查询访问量。

如果你想一次性获取多个页面的访问量 JSON 格式数据，可以通过直接请求 API 的方式获取，可以参考 OpenAPI 文档：https://artalk.js.org/http-api#tag/Statistic/operation/GetStats

示例：

```
GET https://artalk.qwqaq.com/api/v2/stats/page_pv?page_keys=a,b,c&site_name=ArtalkDocs

{"data":{"a":0,"b":0,"c":0}}
```

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>获取页面访问量示例</title>
</head>
<body>
    <h1>页面访问量统计</h1>
    <div id="stats"></div>

    <script>
        // 构建请求
        var pageKeys = ["a", "b", "c"]; // 要获取访问量的页面关键字列表
        var siteName = "ArtalkDocs"; // 站点名称
        var apiUrl = "https://artalk.your_domain.com/api/v2/stats/page_pv?page_keys=" + pageKeys.join(",") + "&site_name=" + siteName;

        // 发送请求
        fetch(apiUrl)
            .then(response => response.json())
            .then(data => {
                // 处理返回的数据
                var statsDiv = document.getElementById("stats");
                statsDiv.innerHTML = "<h2>页面访问量统计结果：</h2>";

                // 遍历每个页面的访问量，并显示在页面上
                for (var pageKey in data.data) {
                    statsDiv.innerHTML += "<p>页面 '" + pageKey + "' 的访问量为：" + data.data[pageKey] + "</p>";
                }
            })
            .catch(error => console.error("获取页面访问量数据时出错：", error));
    </script>
</body>
</html>
```

_Originally posted by @qwqcode in https://github.com/ArtalkJS/Artalk/issues/881#issuecomment-2132161963_
            
# 请问这些接口不需要鉴权吗？会不会造成数据丢失或者数据篡改

**Comment by qwqcode** [comment]
> ```
>           你好，一般可以参考 https://artalk.js.org/guide/frontend/pv.html 查询访问量。
> ```
> 
> 如果你想一次性获取多个页面的访问量 JSON 格式数据，可以通过直接请求 API 的方式获取，可以参考 OpenAPI 文档：https://artalk.js.org/http-api#tag/Statistic/operation/GetStats
> 
> 示例：
> 
> ```
> GET https://artalk.qwqaq.com/api/v2/stats/page_pv?page_keys=a,b,c&site_name=ArtalkDocs
> 
> {"data":{"a":0,"b":0,"c":0}}
> ```
> 
> ```
> <!DOCTYPE html>
> <html lang="en">
> <head>
>     <meta charset="UTF-8">
>     <meta name="viewport" content="width=device-width, initial-scale=1.0">
>     <title>获取页面访问量示例</title>
> </head>
> <body>
>     <h1>页面访问量统计</h1>
>     <div id="stats"></div>
> 
>     <script>
>         // 构建请求
>         var pageKeys = ["a", "b", "c"]; // 要获取访问量的页面关键字列表
>         var siteName = "ArtalkDocs"; // 站点名称
>         var apiUrl = "https://artalk.your_domain.com/api/v2/stats/page_pv?page_keys=" + pageKeys.join(",") + "&site_name=" + siteName;
> 
>         // 发送请求
>         fetch(apiUrl)
>             .then(response => response.json())
>             .then(data => {
>                 // 处理返回的数据
>                 var statsDiv = document.getElementById("stats");
>                 statsDiv.innerHTML = "<h2>页面访问量统计结果：</h2>";
> 
>                 // 遍历每个页面的访问量，并显示在页面上
>                 for (var pageKey in data.data) {
>                     statsDiv.innerHTML += "<p>页面 '" + pageKey + "' 的访问量为：" + data.data[pageKey] + "</p>";
>                 }
>             })
>             .catch(error => console.error("获取页面访问量数据时出错：", error));
>     </script>
> </body>
> </html>
> ```
> 
> _Originally posted by @qwqcode in [#881 (comment)](https://github.com/ArtalkJS/Artalk/issues/881#issuecomment-2132161963)_
> 
> # 请问这些接口不需要鉴权吗？会不会造成数据丢失或者数据篡改

评论数、页面浏览量是公开数据，不需要登录

你说的这些接口指哪些？需要鉴权的接口当然需要，请参考 OpenAPI 文档中的 AUTHORIZATIONS 部分
