### ISSUE TITLE
API 接口 `stats/site_pv` 响应数据格式错误

### ISSUE THREAD

**Issue by white0dew** [ArtalkJS/Artalk#896]
你好，这个功能已经存在了，GET 请求 `https://artalk.xxx.com/api/v2/stats/site_comment?site_name=站点名` 可以得到 `{"data":957}`

```js
const siteName = '站点名'; // 替换为实际的站点名
const url = `https://artalk.xxx.com/api/v2/stats/site_comment?site_name=${encodeURIComponent(siteName)}`;

fetch(url)
  .then(response => {
    if (!response.ok) {
      throw new Error('Network response was not ok');
    }
    return response.json();
  })
  .then(({ data }) => {
    console.log(data); // 输出获取的数据
  })
  .catch(error => {
    console.error('There was a problem with the fetch operation:', error);
  });
```

https://artalk.js.org/http-api.html#tag/Statistic/operation/GetStats

_Originally posted by @qwqcode in https://github.com/ArtalkJS/Artalk/issues/811#issuecomment-2089461374_
            

# site_pv 经测试，无法使用？请问是什么原因呢

**Comment by white0dew** [comment]
> [https://artalk.xxx.com/api/v2/stats/site_comment?site_name=站点名](https://artalk.xxx.com/api/v2/stats/site_comment?site_name=%E7%AB%99%E7%82%B9%E5%90%8D)
> 
> 這個也不是獲取 site_pv 啊

我是指，将原本的site_comment换成site_pv，获取的数据是undefined

**Comment by qwqcode** [comment]
fixed https://github.com/ArtalkJS/Artalk/commit/2dfee533da05a2793161b9481603ff98eb82310a#diff-bfd1d3bc6f5c7dfb9d9067277a515af148a796cbab8198882f2ffde5cf917519R157-R159
