### ISSUE TITLE
突然想到一个功能：当前在线人数

### ISSUE THREAD

**Issue by white0dew** [ArtalkJS/Artalk#898]
这个artalk最近已经开始深度使用了，想到一个新的功能：在线人数
基本实现思路可以通过前端每隔一段时间进行心跳检测，统计当前网站在线人数
功能实现起来应该不复杂

**Comment by awaae001** [comment]
站点在线人数多的时候会带来服务器高负载吧
毕竟是发心跳包

**Comment by white0dew** [comment]
> 站点在线人数多的时候会带来服务器高负载吧 毕竟是发心跳包
