### ISSUE TITLE
邮件模版表情包图片 HTML 标签会被转义

### ISSUE THREAD

**Issue by qwqcode** [ArtalkJS/Artalk#90]
@qwqcode 邮件通知 带表情图片地址  会被转A链接  导致表情不显示，有办法在后端设置吗？

https://vkceyugu.cdn.bspapp.com/VKCEYUGU-2fa930c8-feec-4942-ac88-ba3781377bb0/b377313c-3d14-4bfc-bba9-78f37d19462f.png

_Originally posted by @xiamuguizhi in https://github.com/ArtalkJS/Artalk/issues/70#issuecomment-1094657790_

**Comment by xiamuguizhi** [comment]
@qwqcode 

``` html
<div id="qm_con_body">
  <div id="mailContentContainer" class="qmbox qm_con_body_content qqmail_webmail_only" style="opacity: 1;">
    <style type="text/css"></style>
    <div id="qm_con_body">
      <div id="mailContentContainer" class="qmbox qm_con_body_content qqmail_webmail_only" style="">
        <div style="background: white; width: 90%; margin: 100px auto; border-radius: 5px; border:#e91e639e 1px solid; overflow: hidden; -webkit-box-shadow: 0px 0px 20px 0px rgba(0, 0, 0, 0.12); box-shadow: 0px 0px 20px 0px rgba(0, 0, 0, 0.18);">
          <header style="overflow: hidden;">
            <a href="https://xn--qpru0x.cn/" target="_blank" rel="noopener">
              <img style="width:100%;" src="https://api.btstu.cn/sjbz/api.php" /></a>
          </header>
          <div style="padding: 5px 20px;">
            <p style="position: relative; color: white; float: left; background: #e91e63; padding: 5px 30px; margin: -25px auto 0 ; box-shadow: 5px 5px 5px rgba(0, 0, 0, 0.30)">Dear:{{nick}}</p>
            <br />
            <h3 style="margin-bottom: 32px">您在
              <a style="text-decoration: none;color: #e91e63 " target="_blank" href="{{page_url}}" rel="noopener">《{{page_title}}》</a>的评论收到了回复</h3>
            <p style="font-size:14px;">您发表的评论:</p>
            <p style="border-bottom:#ddd 1px solid;border-left:#ddd 1px solid;padding-bottom:20px;background-color:#eee;margin:15px 0px;padding-left:20px;padding-right:20px;border-top:#ddd 1px solid;border-right:#ddd 1px solid;padding-top:20px">{{parent_comment.content_raw}}</p>
            <p style="font-size: 14px;">"{{reply_nick}}" 给您的回复如下：</p>
            <p style="border-bottom:#ddd 1px solid;border-left:#ddd 1px solid;padding-bottom:20px;background-color:#eee;margin:15px 0px;padding-left:20px;padding-right:20px;border-top:#ddd 1px solid;border-right:#ddd 1px solid;padding-top:20px">{{comment.content_raw}}</p>
            <div style="text-align: center;">
              <a style="text-transform: uppercase; text-decoration: none; font-size: 14px; border: 2px solid #6c7575; color: #2f3333; padding: 10px; display: inline-block; margin: 10px auto 0; " target="_blank" href="{{link_to_reply}}" rel="noopener">查看回复的完整内容</a></div>
            <br />
            <p style="font-size: 14px;text-align: center;">(本邮件为系统自动发送，请勿直接回复。tip:图片显示不了的添加信任即可! 欢迎再次光临
              <a style="text-decoration: none;color: #e91e63" target="_blank" href="{{site_url}}" rel="noopener">叶开楗博客</a>)</p></div>
        </div>
      </div>
    </div>
    <style type="text/css">.qmbox style, .qmbox script, .qmbox head, .qmbox link, .qmbox meta {display: none !important;}</style></div>
</div>
```

**Comment by xiamuguizhi** [comment]
@qwqcode 如果能解决了 艾特我一下哈，晚上不知道会不会上线 我会看邮件通知的。

**Comment by qwqcode** [comment]
@xiamuguizhi 

尝试将：

- `{{parent_comment.content_raw}}` 修改为 `{{parent_comment.content}}`
- `{{comment.content_raw}}` 修改为 `{{comment.content}}`

两处，去掉 `_raw`

**Comment by xiamuguizhi** [comment]
@qwqcode  你提供的方法我一开始就试过了 ，行不通的。


而且我发现你可能颠倒了。

- 带_raw 邮件通知是 只显示html 

{{parent_comment.content_raw}
{{comment.content_raw}}

- 不带_raw 邮件通知是 只支持显示文字好像

{{parent_comment.content}}
{{comment.content}}

使用 {{parent_comment.content}} 以后邮件通知连 img src xx表情地址都没有了。

![image](https://user-images.githubusercontent.com/19650297/162740885-41f05893-8b0d-4d1c-9f03-1d4ed1b709ee.png)

**Comment by xiamuguizhi** [comment]
@qwqcode  是不是 可以取消 对 网址链接([https://i.xiamuyourenzhang.cn/heo/生病.png](https://i.xiamuyourenzhang.cn/heo/%E7%94%9F%E7%97%85.png)) 自动转换 成 a链接这样的。

`<a href="https://i.xiamuyourenzhang.cn/heo/生病.png" rel="noopener" target="_blank">https://i.xiamuyourenzhang.cn/heo/生病.png</a>`

不转换网址为a链接，估计表情就能正常显示了。

**Comment by qwqcode** [comment]
刚刚测了下，确实存在问题，需要修改后端代码
`<img>` HTML 标签会被直接过滤掉
`![](图片链接)` Markdown 语法可以正常生成

**Comment by xiamuguizhi** [comment]
@qwqcode 问题说大也不大，就看有没有需求了，我是挺需要的哈哈，我感觉邮件通知看到表情包就很好玩。

不然我使用下面两个只输出 文字就好了。

{{parent_comment.content}}
{{comment.content}}

**Comment by qwqcode** [comment]
后端新版已修复 https://github.com/ArtalkJS/ArtalkGo/commit/aa902601fb8594ce8a0a59973c49c7f35f866236

请将邮件模版：

- {{parent_comment.content_raw}} 修改为 {{parent_comment.content}}
- {{comment.content_raw}} 修改为 {{comment.content}}

两处，去掉 _raw，不然会造成 XSS 漏洞

**Comment by xiamuguizhi** [comment]
@qwqcode 测试成功   就是邮箱获取好像反了 我在去看看 哈哈。

![image](https://user-images.githubusercontent.com/19650297/162855301-046e18e6-a82e-45b7-8436-a4dff2e71171.png)

**Comment by liub1934** [comment]
> @qwqcode 测试成功 ~就是邮箱获取好像反了 ~ 尴尬 输入错邮箱了 哈哈。我在去看看 哈哈。
> 
> ![image](https://user-images.githubusercontent.com/19650297/162855301-046e18e6-a82e-45b7-8436-a4dff2e71171.png)

能提供下模版代码吗👍
