### ISSUE TITLE
[Help]: 设置 countEL和 pvEl 无效

### ISSUE THREAD

**Issue by everfu** [ArtalkJS/Artalk#905]
我是这么设置的，但是不生效
<img width="658" alt="image" src="https://github.com/ArtalkJS/Artalk/assets/74389842/540c682f-b03c-480b-8f6a-ed6d74cb749b">

**Comment by everfu** [comment]
<img width="496" alt="image" src="https://github.com/ArtalkJS/Artalk/assets/74389842/de1e90fb-0115-4025-8d89-5c0a80f97e8b">

**Comment by everfu** [comment]
后台设置比前台绑定优先级高
<img width="1753" alt="image" src="https://github.com/ArtalkJS/Artalk/assets/74389842/46299188-b701-48d1-a726-18afdad66b37">

**Comment by qwqcode** [comment]
🤔️ 我猜测可能是后端程序把前端的配置覆盖了的问题，界面配置目前的优先级是这样的：https://artalk.js.org/guide/frontend/config.html

**Comment by qwqcode** [comment]
也许我应该将优先级改为：

```
前端代码 > 后端配置文件
```

修改后，提供一个选项“强制覆盖前端配置”，默认优先级是：`前端代码 > 后端配置文件`，启用这个选项后才是`后端配置文件 > 前端代码`。

这样能方便主题更好地适配 Artalk。

不过这会是一个破坏性变更，需要考虑社区的历史版本兼容性问题

**Comment by qwqcode** [comment]
> 我的建议是不要给后端任何DOM相关的能力
> 
> 

确实，`pvEl`、`countEl`、`statPageKeyAttr` 这些操作 DOM 的选项可以在后端设置列表中移除，不允许在后端配置，因为一般也没有动态修改的需求

**Comment by everfu** [comment]
> > 我的建议是不要给后端任何DOM相关的能力
> 
> 确实，`pvEl`、`countEl`、`statPageKeyAttr` 这些操作 DOM 的选项可以在后端设置列表中移除，不允许在后端配置，因为一般也没有动态修改的需求

是的，交给前端，没有指定就是默认的设置
