### ISSUE TITLE
注册邮件标题模板里的code未能正确替换

### ISSUE THREAD

**Issue by MatchaCabin** [ArtalkJS/Artalk#910]
![image](https://github.com/ArtalkJS/Artalk/assets/170641850/bce2bbdb-acb7-41a3-b03d-04cd43233060)
哪怕默认配置也一样的问题

原因在于这行，code替换在i18n.T方法就已经执行了，后续才和配置文件中的模板进行比较
如果模板存在，则直接使用了模板字符串，而这字符串中的code是没有进行过替换的
https://github.com/ArtalkJS/Artalk/blob/f8f509c0def9f025f4c461316fdfd5a3c1444d02/server/handler/auth_email_send.go#L86

**Comment by qwqcode** [comment]
[v2.8.7](https://github.com/ArtalkJS/Artalk/releases/tag/v2.8.7) 已发布，应该修复了这个问题，感谢反馈~
