### ISSUE TITLE
bug: nighly 版本头像源不生效

### ISSUE THREAD

**Issue by wenjing-xin** [ArtalkJS/Artalk#911]
![image](https://github.com/ArtalkJS/Artalk/assets/130843859/a8ea9ae7-bb70-4b9b-94f8-208c53b746c4)
wo de我的配置如上，在V2.8.6及其之前是合适的，升级了 nightly版本后就不能用了

**Comment by devhaozi** [comment]
因为自带的头像源不支持 sha256，可以考虑使用 weavatar.com

**Comment by qwqcode** [comment]
fixed by #912
