### ISSUE TITLE
bug：nightly版本设置了平铺模式为false之后出现评论缺少的问题

### ISSUE THREAD

**Issue by wenjing-xin** [ArtalkJS/Artalk#914]
![image](https://github.com/ArtalkJS/Artalk/assets/130843859/99f0c874-7871-4682-871d-80345c922516)
升级了 nightly 版本之后，设置平铺模式为 false 后，发现以前设置为平铺模式为 true 时的评论无法显示了，具体可查看我[站点的页面](https://blog.wenjing.xin/links)

**Comment by qwqcode** [comment]
看看是不是这个问题：https://github.com/ArtalkJS/Artalk/issues/891#issuecomment-2132285751

**Comment by wenjing-xin** [comment]
谢谢 已经完美解决
