### ISSUE TITLE
Error: 请求响应 404，无法获取评论列表数据

### ISSUE THREAD

**Issue by aayorishy** [ArtalkJS/Artalk#916]
![image](https://github.com/ArtalkJS/Artalk/assets/171849287/6be84ff4-bdd7-4af7-86b2-2fbaf0911626)

**Comment by aayorishy** [comment]
后端也正常访问
![image](https://github.com/ArtalkJS/Artalk/assets/171849287/dd2e8caa-61b4-4a98-8663-3f82f3a6f4e0)
后端网址也设置好了

**Comment by aayorishy** [comment]
![image](https://github.com/ArtalkJS/Artalk/assets/171849287/0e863279-1ff2-4505-8bad-bf90f7e9b0f2)

**Comment by qwqcode** [comment]
前端 JS 版本太老了，升级前端到最新版
