### ISSUE TITLE
[高危漏洞]:未登录账户的情况下可以影响已设置密码的同一邮箱账户

### ISSUE THREAD

**Issue by GoodBoyboy666** [ArtalkJS/Artalk#921]
版本：2.8.7

漏洞描述：一个启用邮箱登录的账户（已设置密码）的`网址`一栏内容可以在未登录的情况下通过匿名评论的方式进行修改。

影响：此漏洞可能会导致某些用户的`网址`一栏内容被恶意修改，重定向至恶意网站。

先决条件：允许匿名评论。

漏洞复现：只需在匿名评论下填写被攻击者的完整邮箱，修改`网址`一栏内容并随便提交一条评论即可完成修改。

**Comment by qwqcode** [comment]
**“先决条件：允许匿名评论。” 补充说明**

默认情况下（没有开启用户登录功能），不需要登录就可以评论，所以只要填写了 “邮箱”、“昵称”，就可以修改“网址”这一栏的内容。（网址数据具有记忆功能）

开启了用户登录功能后，以上这个操作仍然被允许，所以这个漏洞出现了。

**漏洞修复措施：**

后续更新版本：开启社交登录功能后，阻止未登录的用户设置“网址”（以及其他具有记忆功能的用户资料字段）。

---

另：对于不想开启“社交登录”的 Artalk 用户，建议不使用网上公开的邮箱地址（转而使用隐私邮箱、邮件转发等方式，生成新的邮箱地址），避免使用如 QQ 号 `@qq.com` 这种容易被别人猜到的地址，可能会存在被冒名等风险。管理员用户由于始终需要输入密码，尽管没有开启“社交登录”功能，也不受该问题影响。
