### ISSUE TITLE
[Help]: 登录失败

### ISSUE THREAD

**Issue by everfu** [ArtalkJS/Artalk#926]
日志：
```log
2024/06/12 11:14:33.685 ERROR [handler/user_login.go:76] 登录失败 {"id": "***********", "path": "/api/v2/user/access_token", "method": "POST", "ip": "my ip", "remote_addr": "my ip:59334", "host": "art.efu.me", "referer": "", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36", "status": 401}
2024/06/12 11:14:33.685 ERROR [HTTP] 11:14:33 | 401 |   84.415971ms | 35.220.233.124 | POST | /api/v2/user/access_token | - | ***********
```

**Comment by everfu** [comment]
<img width="925" alt="image" src="https://github.com/ArtalkJS/Artalk/assets/74389842/caf2205b-934a-41a6-8c9a-ed1a14c95ed8">

**Comment by GoodBoyboy666** [comment]
> <img alt="image" width="925" src="https://private-user-images.githubusercontent.com/74389842/338814008-caf2205b-934a-41a6-8c9a-ed1a14c95ed8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MjYyODQsIm5iZiI6MTcxODYyNTk4NCwicGF0aCI6Ii83NDM4OTg0Mi8zMzg4MTQwMDgtY2FmMjIwNWItOTM0YS00MWE2LThjOWEtZWQxYTE0Yzk1ZWQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDEyMDYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjYzhlNTRhZTZlZDU3MjllOWIzMDdhMjE1ZDI2NDMwOTJhNDU0NzIzOWI2MmY2NGVhZGFmOGQ1ZDVmY2Q4NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wAHwEhEbqxiRLDq6pJeDJKf-6M-zJ4YF3RM_eJjz5DQ">

无效打码警告

**Comment by qwqcode** [comment]
登录失败实际上应该是用户名或邮箱或密码错误，可以核对下数据库中实际的数据，因为你的截图没有完全打码，我把你的回复删了，防止信息泄露，谢谢 @GoodBoyboy666 的提醒
