### ISSUE TITLE
[bug]社交登录-微软账号-配置完不显示登录按钮

### ISSUE THREAD

**Issue by Doradx** [ArtalkJS/Artalk#929]
配置并勾选开启微软登录后，在登录页面不显示微软账号登录按钮。

**Comment by qwqcode** [comment]
你好，忘记回复了 😂 目前 Nightly 版已经补充了缺失的微软账号配置，问题解决了吗

**Comment by Doradx** [comment]
尝试了，报错："Field to complete user auth"
且登录按钮不显示图标，如下图：
![image](https://github.com/user-attachments/assets/83532018-4a22-489a-beb5-d605fd77d18a)

**Comment by qwqcode** [comment]
> 尝试了，报错："Field to complete user auth" 且登录按钮不显示图标，如下图： ![image](https://private-user-images.githubusercontent.com/23170065/348148627-83532018-4a22-489a-beb5-d605fd77d18a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NTQ5MTIsIm5iZiI6MTcyMDg1NDYxMiwicGF0aCI6Ii8yMzE3MDA2NS8zNDgxNDg2MjctODM1MzIwMTgtNGEyMi00ODlhLWJlYjUtZDYwNWZkNzdkMThhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDA3MTAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjOTgxZDcyNjA2YWNhY2Y2NTVjYzhiMTNhYTE1MzUyOTM1NWQxNjYxYTZjZThmMWY3MTcwNDdiNzU5YWRjZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YMdk6gPGsVtKOKPqWxmD1911RYbr1ousv7WZb_glXdY)

可以看看日志文件 artalk.log `[SocialLogin]` 报错具体错误信息是什么

**Comment by Doradx** [comment]
> > 尝试了，报错："Field to complete user auth" 且登录按钮不显示图标，如下图： ![image](https://private-user-images.githubusercontent.com/23170065/348148627-83532018-4a22-489a-beb5-d605fd77d18a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NTQ5MTIsIm5iZiI6MTcyMDg1NDYxMiwicGF0aCI6Ii8yMzE3MDA2NS8zNDgxNDg2MjctODM1MzIwMTgtNGEyMi00ODlhLWJlYjUtZDYwNWZkNzdkMThhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDA3MTAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjOTgxZDcyNjA2YWNhY2Y2NTVjYzhiMTNhYTE1MzUyOTM1NWQxNjYxYTZjZThmMWY3MTcwNDdiNzU5YWRjZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YMdk6gPGsVtKOKPqWxmD1911RYbr1ousv7WZb_glXdY)
> 
> 可以看看日志文件 artalk.log `[SocialLogin]` 报错具体错误信息是什么

日志详情：
```text
{"level":"INFO","ts":"2024-07-13T21:14:48.271+0800","caller":"[handler/setting_apply.go:63]","msg":"[Apply Settings] 服务重启完毕"}
{"level":"ERROR","ts":"2024-07-13T21:15:18.479+0800","caller":"[handler/auth_social_login.go:74]","msg":"[SocialLogin] no provider for microsoft exists"}
{"level":"ERROR","ts":"2024-07-13T21:15:18.502+0800","caller":"[handler/auth_social_login.go:75]","msg":"Field to complete user auth","id":"585cebaa-e380-4151-b491-e7101ce1782e","path":"/api/v2/auth/microsoft/callback","method":"GET","ip":"59.XX.XXX.XX","remote_addr":"172.31.0.1:34106","host":"comments.cuger.cn","referer":"https://login.microsoftonline.com/","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0","status":500}
{"level":"ERROR","ts":"2024-07-13T21:15:18.507+0800","msg":"[HTTP] 21:15:18 | 500 |   33.185788ms | 59.XX.XXX.XX | GET | /api/v2/auth/microsoft/callback | - | 585cebaa-e380-4151-b491-e7101ce1782e"}
```
网页提示：
```json
{
    "msg": "Field to complete user auth"
}
```

**Comment by qwqcode** [comment]
😢 不好意思，我之前没有注意到。可以再试试升级到 Nightly 版本，然后微软那边回调地址填写 `https://xxx.com/api/v2/auth/microsoftonline/callback`（把`microsoft` 替换为 `microsoftonline`）

**Comment by Doradx** [comment]
亲测已OK。
辛苦了！
