### ISSUE TITLE
邮箱获取 QQ 头像

### ISSUE THREAD

**Issue by qwqcode** [ArtalkJS/Artalk#93]

**Comment by xiamuguizhi** [comment]
这个你可以看看 https://cravatar.cn/  

独有的三级头像匹配机制
当访客请求自己的头像时，我们会按此顺序分三级匹配头像：Cravatar->Gravatar->QQ 头像，对于博客站，这平均可以为 70% 的访客提供准确的头像

**Comment by qwqcode** [comment]
@xiamuguizhi 这样很棒

那可以直接修改 Artalk 前端配置：

```js
new Artalk({
  gravatar: {
    default: 'mp',
    mirror: 'https://cravatar.cn/avatar/',
  }
})
```

即可启用 Cravatar，这样就不需要再写 QQ API 的专门适配代码
