### ISSUE TITLE
单独的评论管理员可以收到邮件通知，但是回复管理员的评论收不到邮件通知

### ISSUE THREAD

**Issue by Einstein-schrodinger** [ArtalkJS/Artalk#934]
普通用户单独的评论管理员可以收到邮件通知，但是回复管理员的评论收不到邮件通知。这是怎么回事，bug还是配置的问题？

**Comment by MooWantFree** [comment]
https://artalk.js.org/guide/backend/admin_notify.html#%E5%98%88%E6%9D%82%E6%A8%A1%E5%BC%8F-noise-mode
这个是否有开? 有log可以看下吗

**Comment by laomaiorg** [comment]
我还以为是我配置的问题
期待早点修复。
