### ISSUE TITLE
图片上传功能

### ISSUE THREAD

**Issue by qwqcode** [ArtalkJS/Artalk#94]
支持图片上传，并接入 https://github.com/pluveto/upgit 支持上传到 GitHub 仓库或各种图床

**Comment by xiamuguizhi** [comment]
不错 不错

**Comment by qwqcode** [comment]
https://github.com/ArtalkJS/Artalk/pull/95

**Comment by mrmign** [comment]
docker镜像里没有看到打upgit命令呐，请问用镜像怎么配置这个功能？
