### ISSUE TITLE
社交登录模式开启、访客注册后，无法再次修改自己的信息

### ISSUE THREAD

**Issue by gxres042** [ArtalkJS/Artalk#942]
假设我在 [杜老师说](https://dusays.com) 注册了一个账号。而注册时，Artalk 未要求用户填写他们的网站地址。

注册并评论后，在杜老师的提醒下，访客发现自己没有留下自己网站的链接（未开启社交登录下，匿名访客可选择填写网站地址），遂尝试修改自己的个人信息。

一看通知中心，除了能看自己的评论和相关内容，Artalk 没有提供一个供访客再次修改自己个人信息的通道。

望 Artalk 团队能够在下一个版本添加相对应的通道~

**Comment by yoghurtlee-thu** [comment]
同意，期待开发团队能够添加这个实用的功能。Best regards.

**Comment by qwqcode** [comment]
感谢反馈，这个功能开发已在计划中

duplicate of #922
