### ISSUE TITLE
[功能请求] 文章点赞功能

### ISSUE THREAD

**Issue by white0dew** [ArtalkJS/Artalk#944]
能不能增加一i个点赞功能，是指给文章点赞，而不是评论。

这个实现起来应该很快的

**Comment by Liumingxun** [comment]
@qwqcode I notice that [`page` entity](https://github.com/ArtalkJS/Artalk/blob/adcb75a2e2a9611afdd1a84bf9d6e9427bf186b0/internal/entity/page.go#L22) has `VoteUp` field like `comment`, and `vote()` also can vote up/down `page` or `comment`, or maybe also need to update count widget for `page` vote?

As well as, kindly to ask if there is someone working for this? If not, I'm glad to undertake it. 😉

**Comment by white0dew** [comment]
> @qwqcode I notice that [`page` entity](https://github.com/ArtalkJS/Artalk/blob/adcb75a2e2a9611afdd1a84bf9d6e9427bf186b0/internal/entity/page.go#L22) has `VoteUp` field like `comment`, and `vote()` also can vote up/down `page` or `comment`, or maybe also need to update count widget for `page` vote?@qwqcode我注意到[`page`实体](https://github.com/ArtalkJS/Artalk/blob/adcb75a2e2a9611afdd1a84bf9d6e9427bf186b0/internal/entity/page.go#L22)有像`comment`这样的`VoteUp`字段，并且`vote()`也可以向上/向下`page`或`comment`投票，或者可能还需要更新`page`投票的计数小部件？
> 
> As well as, kindly to ask if there is someone working for this? If not, I'm glad to undertake it. 😉另外，请问是否有人为此工作？如果没有，我很乐意承担。 😉

thanks，you can do it

**Comment by JIeJaitt** [comment]
@white0dew 指的是给文章点赞能长期存在并且累加的功能吗，这样的话可能得在数据库存一个字段才行
