### ISSUE TITLE
admin无法回复和编辑用户评论

### ISSUE THREAD

**Issue by candiceatwb** [ArtalkJS/Artalk#952]
<img width="519" alt="截屏2024-08-12 16 07 10" src="https://github.com/user-attachments/assets/220862d1-1bbd-4691-a99e-69213c256dff">
Docker部署后，admin登入后台，点击 每条评论的 “回复” 和 “编辑” 没有任何反应，请问是哪里问题？

**Comment by qwqcode** [comment]
你好，我无法复现这个问题，你的浏览器是什么浏览器？

**Comment by candiceatwb** [comment]
Chrome浏览器
admin回复功能是在后台就可以操作，还是要打开评论所在 文章才能回复？
________________________________
发件人: qwqcode ***@***.***>
发送时间: 2024年8月28日 11:38
收件人: ArtalkJS/Artalk ***@***.***>
抄送: Candice Yang ***@***.***>; Author ***@***.***>
主题: Re: [ArtalkJS/Artalk] admin无法回复和编辑用户评论 (Issue #952)


你好，我无法复现这个问题，你的浏览器是什么浏览器？

―

**Comment by qwqcode** [comment]
直接在后台就可以操作

**Comment by candiceatwb** [comment]
> 直接在后台就可以操作
那很奇怪，我在后台 点击 “回复” 和 “编辑” 一点反应也没有

**Comment by qwqcode** [comment]
你换个浏览器试试？浏览器控制台有报错信息吗？

**Comment by candiceatwb** [comment]
你好，查看了控制台没有错误日志的，特意录屏你可以帮忙看下
在后台点击“回复”和“编辑”，都没反应;
点击评论item会跳到评论对应的文章那里。

________________________________
发件人: qwqcode ***@***.***>
发送时间: 2024年9月7日 16:42
收件人: ArtalkJS/Artalk ***@***.***>
抄送: Candice Yang ***@***.***>; Author ***@***.***>
主题: Re: [ArtalkJS/Artalk] admin无法回复和编辑用户评论 (Issue #952)


你换个浏览器试试？浏览器控制台有报错信息吗？

―

**Comment by candiceatwb** [comment]
我今天升级到2.9.1版本，admin后台点击“回复”和“编辑”都有反应了，太👍了
