### ISSUE TITLE
在一条评论下有多个回复时，回复的引用名都是主评论用户的名称

### ISSUE THREAD

**Issue by rebron1900** [ArtalkJS/Artalk#958]
![image](https://github.com/user-attachments/assets/b39c1b0b-ef98-497c-85aa-e9d25a78f020)

如图，比如yolo回复的是我的消息，但是显示的引用是子蛇的。

**Comment by qwqcode** [comment]
你好，已在 v2.8.5 版本修复这个问题，可以升级 Artalk 到最新版

https://github.com/ArtalkJS/Artalk/issues/771

**Comment by rebron1900** [comment]
Lite是还没更新版本吗？我更新包后发现还是2.8.3

**Comment by rebron1900** [comment]
不用lite版是正常的了，先切回去把。谢谢。

**Comment by qwqcode** [comment]
ArtalkLite 和 Artalk 目前 NPM 推送的最新版为 2.8.7

可以检查浏览器、CDN 缓存或者其他问题

**Comment by rebron1900** [comment]
我是 `import Artalk from "artalk/dist/ArtalkLite.js";` 这样引用的，是不是方式不对？

**Comment by qwqcode** [comment]
对的

**Comment by rebron1900** [comment]
@qwqcode 大佬，搜索用户的功能是不是还没发布出来？

**Comment by qwqcode** [comment]
你下载 nightly 版就有了

**Comment by rebron1900** [comment]
谢谢，那我等正式版把。 😀
