### ISSUE TITLE
Blank page for SQL syntax error in using PostgreSQL

### ISSUE THREAD

**Issue by syhily** [ArtalkJS/Artalk#969]
When I upgrade the Artalk to the latest 2.9.0. I meet the SQL syntax error in using PostgreSQL.

```
2024/09/04 13:32:05.313 ERROR [v2@v2.52.5/router.go:145] [DB] {"error": "ERROR: missing FROM-clause entry for table \"pages\" (SQLSTATE 42P01)", "elapsed": 0.000486761, "rows": 0, "sql": "SELECT count(*) FROM \"atk_pages\" WHERE (LOWER(pages.key) LIKE LOWER('%%') OR LOWER(title) LIKE LOWER('%%')) AND \"atk_pages\".\"deleted_at\" IS NULL"}
```

**Comment by syhily** [comment]
https://github.com/ArtalkJS/Artalk/blob/90d8503d0ee07cfe2e633385c487a2b1c72b743d/server/handler/page_list.go#L53C26-L53C31

This should be the root cause. You shouldn't append the where clause directly and the page.key isn't a good reference.

```
if p.Search != "" {
		q = q.Scopes(func(d *gorm.DB) *gorm.DB {
			return d.Where("LOWER(`key`) LIKE LOWER(?) OR LOWER(title) LIKE LOWER(?)",
				"%"+p.Search+"%", "%"+p.Search+"%")
		})
}
```

**Comment by syhily** [comment]
Or you can use GORM built-in method for querying the table name.

```
if p.Search != "" {
	q = q.Scopes(func(d *gorm.DB) *gorm.DB {
		tableName := app.Dao().DB().Model(&entity.Page{}).TableName()
		return d.Where("LOWER("+tableName+".key) LIKE LOWER(?) OR LOWER(title) LIKE LOWER(?)",
				"%"+p.Search+"%", "%"+p.Search+"%")
	})
}

```

**Comment by qwqcode** [comment]
> Or you can use GORM built-in method for querying the table name.
> 
> ```
> if p.Search != "" {
> 	q = q.Scopes(func(d *gorm.DB) *gorm.DB {
> 		tableName := app.Dao().DB().Model(&entity.Page{}).TableName()
> 		return d.Where("LOWER("+tableName+".key) LIKE LOWER(?) OR LOWER(title) LIKE LOWER(?)",
> 			"%"+p.Search+"%", "%"+p.Search+"%")
> 	})
> }
> ```

Thank you for your feedback and suggestions

**Comment by syhily** [comment]
@qwqcode Given this is a regression. I suggest that you should release a new version ASAP.

**Comment by qwqcode** [comment]
The nightly version has been released immediately.
