### ISSUE TITLE
[bug] page重复条目，pv统计失效

### ISSUE THREAD

**Issue by Doradx** [ArtalkJS/Artalk#971]
环境：artalk/artalk-go:nightly
版本：v2.9.0 / 90d8503d

具体问题：
更新后，page数据库会生成重复的条目，导致pv统计失效。详情见下图。

![image](https://github.com/user-attachments/assets/a67fd35a-9528-4686-997d-e873074b5427)

手动合并后，仍会出现。

**Comment by qwqcode** [comment]
刚刚对 `/api/v2/pages/pv` 接口做了压力测试（PgSQL、SQLite），暂时未能复现这个问题  😢

<img width="190" alt="SCR-20240904-supc" src="https://github.com/user-attachments/assets/bbbb9b5a-9db5-4cb1-a2dd-349a2f1126e4">

<img width="1052" alt="SCR-20240904-suqa" src="https://github.com/user-attachments/assets/442c512d-1608-4663-a214-e3447e888d86">

**Comment by Doradx** [comment]
感谢，我手动清理一下看是否会复现

**Comment by Doradx** [comment]
确实开启了redis缓存

**Comment by Doradx** [comment]
手动清理后，未再出现。
感谢。

**Comment by krau** [comment]
在从 2.9.0 升级到 2.9.1 之后出现同样的问题.

**Comment by Doradx** [comment]
重复出现后找到问题。
pages表的id未设置为自增ID，导致其ID为null，产生重复条目。
将其改为自增ID即可。
