### ISSUE TITLE
i18n 有問題

### ISSUE THREAD

**Issue by sao-coding** [ArtalkJS/Artalk#973]
配置
![image](https://github.com/user-attachments/assets/00d33c81-ccde-4f32-831a-ad8b9ef82dbe)
![image](https://github.com/user-attachments/assets/208c4b9f-72c4-4df6-b2c4-caa262e5b296)

前端 Nextjs(React) 

有試過強制加 `locale` 沒用
```tsx
'use client'

import React from 'react'
import { usePathname } from 'next/navigation'
import Artalk from 'artalk'

import 'artalk/dist/Artalk.css'

const ArtalkComment = () => {
  const container = React.useRef<HTMLDivElement>(null)
  const artalk = React.useRef<Artalk>()
  const pathname = usePathname()

  React.useEffect(() => {
    artalk.current = Artalk.init({
      el: container.current!,
      pageKey: pathname,
      pageTitle: '留言板',
      server: 'http://192.168.1.11:23366',
      site: 'TIPX'
      // ...
    })

    return () => {
      artalk.current?.destroy()
    }
  }, [container, pathname])

  return <div ref={container}></div>
}

export default ArtalkComment
```

https://github.com/user-attachments/assets/014e8180-82c8-4b79-8725-956f6bb2017b

結果後面試了一下 html 改 lang 也沒用

後端
![image](https://github.com/user-attachments/assets/033a6ebe-8a0c-4fb1-a34a-61e682280f05)

**Comment by qwqcode** [comment]
你好！一般情況下，只需要設置環境變數 `ATK_LOCALE` 即可切換語言，無需其他操作。

你的 Artalk 後端伺服器是自行編譯的嗎？還是使用官方提供的二進制版本？如果是本地自行編譯，可以嘗試執行腳本 `./scripts/build-frontend.sh` 來預先編譯語言包，然後重新啟動 Artalk 的 Golang 後端伺服器，執行 `make dev`。

我簡單測試了一下，似乎沒有發現問題。我看到你影片中的問題，原因可能是前端沒有引入 `i18n/zh-TW.js` 語言包，導致無法切換到繁體中文。

預設情況下，語言包會自動從後端伺服器引入，像是 `https://artalk.xxx/i18n/zh-TW.js`。你也可以嘗試手動引入：

```js
import ArtalkZhTW from 'artalk/i18n/zh-TW'

Artalk.init({
    locale: ArtalkZhTW,
})
```

另外，我注意到 `zh-TW` 的控制台設定介面顯示的是英文，這是因為 `/conf/` 目錄下的 `artalk.example.yml` 檔案還沒有繁體中文翻譯，後續更新時我會補充上這部分。感謝你的反饋，也歡迎繼續提出問題！

https://github.com/user-attachments/assets/b428ad17-42de-447e-94ca-ef8821559a60
