### ISSUE TITLE
Failed to load comments Error: fetch error

### ISSUE THREAD

**Issue by jawaylog** [ArtalkJS/Artalk#977]
部署了最新版本，后台访问也正常，就是置入hugo博客后，出现了
Artalk Error
Failed to load comments
Error: fetch error

Retry
搞了很久都没明白。实在没法了。有人能说下是什么原因，谢谢了
![image](https://github.com/user-attachments/assets/ca22ec04-213e-4a1a-a17a-648a9746f16f)

**Comment by shaoyaoqian** [comment]
一样的问题，原因是自己没设置好
<img width="607" alt="image" src="https://github.com/user-attachments/assets/3bd5bf29-a59b-4d08-b674-dfbdcc8b42ba">

**Comment by qwqcode** [comment]
检查一下可信域名是否配置正确

https://artalk.js.org/zh/guide/backend/config.html#%E5%8F%AF%E4%BF%A1%E5%9F%9F%E5%90%8D-trusted-domains
