### ISSUE TITLE
[bugs]keyword过滤不生效

### ISSUE THREAD

**Issue by white0dew** [ArtalkJS/Artalk#986]
测试之后发现，通过关键词过滤的不生效

**Comment by white0dew** [comment]
![Uploading image.png…]()
请问这个配置有问题吗？

**Comment by white0dew** [comment]
有大佬可以帮忙解决吗，我可以付费

**Comment by qwqcode** [comment]
我简单测试了，功能是正常可以过滤的，你换一个账号评论试试，因为管理员账号是不会被拦截的

**Comment by white0dew** [comment]
已解决，前端配置json化的问题。
