### ISSUE TITLE
暗黑模式与主题适应

### ISSUE THREAD

**Issue by missuo** [ArtalkJS/Artalk#999]
我现在遇到的问题是，我尝试在 **init** 的时候读取 `local storage` 中站点目前使用的 dark or light 参数。

```html
<script>
  Artalk.init({
    el: '#Comments',
    pageKey: '{{ .Permalink }}',
    pageTitle: '{{ .Title }}',
    server: '{{ $.Site.Params.artalk.server }}',
    site: '{{ $.Site.Params.artalk.site }}',
    darkMode: localStorage.getItem("pref-theme") === "dark",
    uaBadge: true,
    imgUpload: false,
  })
</script>
``` 

但是这样的后果是，当我在某个页面手动切换站点的 light or dark，artalk 并不会跟着变，只能手动刷新页面才会生效。我尝试在切换站点暗黑模式的时候，`artalk.setDarkMode(true)`，但是似乎不起作用。arktalk 是否存在 **reload** 的方法？

**Comment by Mister-Hope** [comment]
it should work, see an example here.

 https://github.com/vuepress/ecosystem/blob/main/plugins%2Fblog%2Fplugin-comment%2Fsrc%2Fclient%2Fcomponents%2FArtalkComment.ts#L106-L111

Listening to the darkmode state and call that method from instance is the expected behavior

**Comment by missuo** [comment]
It works. Thanks! @Mister-Hope
